### ISSUE TITLE
Timer: Unable to Select Secondary Text

### ISSUE THREAD

**Issue by juzz197** [cpvalente/ontime#1002]
Server: Version 3.0.3 on Docker
Client: Safari (17.5) and Firefox  (126.0) on MacOS 14.5

In the settings for Timer display, unable to select any options for Secondary Text, only see 'Select an Option'

Works in Backstage View.

**Comment by alex-Arc** [comment]
Hmm that is strange I do have them
![image](https://github.com/cpvalente/ontime/assets/19875125/38aba6ac-4c22-42e0-a735-db446bd85a8b)

could you bring up the dev console and see if you get the `custom-fields` updates
![image](https://github.com/cpvalente/ontime/assets/19875125/0198c10c-8094-430d-86cb-ddcbb690ec18)

**Comment by juzz197** [comment]
I am getting the custom fields update.

To clarify, when I raised this issue, I didn't have any custom fields defined but I could select the 'Note' as secondary text in the Backstage view but not on the Timer view.

When I create a custom field, this shows on both but 'Note' is still missing on Timer.

**Comment by alex-Arc** [comment]
ahhh, got it
