### ISSUE TITLE
Blackout screen not working

### ISSUE THREAD

**Issue by desertdognl** [cpvalente/ontime#1016]
In version 3.0.4 (mac ARM version) the blackout screen option is not working. Not in the Ontime software, neither via companion commands

**Comment by desertdognl** [comment]
I am using the Simple timer view. Version is Mac ARM 3.0.4. The button in the admin panel is non responsive. When I try to use the blackout option via companion, this is also non responsive

**Comment by cpvalente** [comment]
> I am using the Simple timer view. Version is Mac ARM 3.0.4. The button in the admin panel is non responsive. When I try to use the blackout option via companion, this is also non responsive

Thank you!

It may be that there is an issue with your connection? Do the timers work correctly?
Can you please open the console and see if there are any errors?
Any chance you could send me a video to mail@getontime.no

**Comment by craigreilly** [comment]
In my testing:
It works fine on /timer but does not seem to work on /minimal. 
Blink works on both.

**Comment by cpvalente** [comment]
> In my testing:
> 
> It works fine on /timer but does not seem to work on /minimal. 
> 
> Blink works on both.
> 
> Message works on both.


I see, thank you for this.
Blackout is not supposed to affect other views then blackout. 

The same should be the case for blink

I guess message should also not show in the minimal.

**Comment by cpvalente** [comment]
Closing this as we are unable to confirm an issue.
@desertdognl , please reach out to mail@getontime.no or find us on discord and we can try and help you debug the setup
