### ISSUE TITLE
WebSocket change of duration broken below 24h

### ISSUE THREAD

**Issue by 7omas** [cpvalente/ontime#1017]
When trying to set duration using WebSocket in 3.0.4 anything below 86400 seconds (24h) results in 23:59:59. Anything above 24h works as expected.

**Comment by alex-Arc** [comment]
That was quick, I have a fix for this, but while we are at it
What would we expect to happen if we get a negative number, should we clamp it to 0 or reject the packet

**Comment by 7omas** [comment]
Duration would always be positive. If it's rejcted no change will happen and if it gives an error message the user can know why nothing changed.

**Comment by cpvalente** [comment]
Hi @7omas, the new release addresses your bug report. Would you mind confirming for us that things work well on your side?
