### ISSUE TITLE
OSC messaging enhancement request

### ISSUE THREAD

**Issue by je71175** [cpvalente/ontime#102]
Hi
If the application is in **Unload** mode and I press or trigger **Next Event**, onTime moves to the first cue, but at this time no _OSC Next_ message is triggered.
May I request this event triggers an _OSC Next_ event, same as if onTime was ready to play the first cue
thank you

**Comment by cpvalente** [comment]
Sounds pretty reasonable. I will push that as soon as I am done with some of the other merges (OSC and Mac version).
Will take a few weeks
