### ISSUE TITLE
v 3.0.4 countdown skips the first second

### ISSUE THREAD

**Issue by craigreilly** [cpvalente/ontime#1025]
When starting a countdown, it seems to skip the first second, ie 10:00 to 9:58.

**Comment by lukestein** [comment]
Replication:

https://github.com/cpvalente/ontime/assets/44452336/edb9a22c-13a6-4899-8d8d-03960b48e8b5

**Comment by cpvalente** [comment]
Thank you @lukestein and @craigreilly 

I believe this was introduced in our recent attempts to make the timer more accurate. I am not immune to the irony here...

I will take a look at improving this, meanwhile:
Ontime updates at a minimum rate of 32ms (when nothing is happening), then we go through a bunch of filter to decide when to notify the views. We dont want to do this too much so try and minimise it to once a second.

What is likely happening is that we got some overzealous filter for the first update, should be a simple fix.
However, I believe this does not have any implications to the usage of the app, just looks strange..

**Comment by cpvalente** [comment]
Hi @craigreilly , the new release v3.1.0 includes changes to address this issue.
Do you mind having a look so we can close the ticket?

**Comment by craigreilly** [comment]
It does fix the previous error, though introduces a smaller concern.
If I am in an "event" and it is running and I click "Next", it almost skips the first second of the next timer.
ie: 10:00 and a 20:00 event.
Start running the 10.
Click "Next"
Display shows 20:00 for a millisecond before showing 19:59.

I am not sure this is really a problem. More cosmetic perhaps. I do not think anyone will notice except maybe the Op sitting in front of the laptop.

**Comment by craigreilly** [comment]
This is a solid write up.I was ok with the fix today... but thought I should bring up the behavior just in case.

**Comment by lukestein** [comment]
I think underlying design choice sounds solid and would **not** show subsecond frequencies anywhere.

Even if it's what's used internally, I think we don't want to give users the impression that they should be able to expect high-frequency accuracy (or even enter partial-second timers). And I wouldn't suggest increasing network traffic for this, either.

**Comment by cpvalente** [comment]
Thank you both @craigreilly and @lukestein for your help and for your comments.

@craigreilly , could we close this ticket?

**Comment by craigreilly** [comment]
Please do…
