### ISSUE TITLE
OSC issue when creating a new project

### ISSUE THREAD

**Issue by craigreilly** [cpvalente/ontime#1026]
If OSC was already on and accepting commands from previous project, then the state continues to be on and accepting commands when you start a new project. Then, when you close the software (QUIT) and Reopen it, it opens the previous project but the OSC status is not accepting commands because it is off.

1) Open a new project.
2) Enable QSC
3) Start a new Project
4) OSC appears to be off in the project settings, but will continue to accept commands
5) Quit the program completely
6) Restart ontime
7) OSC is OFF and must be turned on

Perhaps starting a new project would close the OSC port until it is enabled again.

**Comment by cpvalente** [comment]
Thank you for this @craigreilly , we will take a look
