### ISSUE TITLE
onTime Companion Plugin

### ISSUE THREAD

**Issue by craigreilly** [cpvalente/ontime#1028]
Should the Companion Plugin (WS IN) still work with current version? In the logfile I see errors: unhandled message start-next, unhandled message set-timer-blink. unhandled message loadid

Pause and Start both seem to work ok.

**Comment by cpvalente** [comment]
Hi @craigreilly , you need companion module v4 for the new version of Ontime.
To my best knowledge this works well and we have many users using it.

You can ask for help or make a ticket over at the companion module repository
https://github.com/bitfocus/companion-module-getontime-ontime

**Comment by craigreilly** [comment]
My bad.... Companion update. Apologies for the fire drill.

**Comment by cpvalente** [comment]
No worries, I have my fair share of false alarms 😄 

Ontime can only be good with users help, I appreciate you reaching out and please continue to do so if you feel is necessary
