### ISSUE TITLE
Feature: Edit mode "light" for operators 

### ISSUE THREAD

**Issue by kev-ac** [cpvalente/ontime#1041]
We come across the wish that it would be great if operators of the various areas (lighting, sound, video, etc.) have the ability to add notes to "their" custom field themselves without needing to resort to the main edit UI. 
This may lead to issues if someone misclicks. 

This way Ontime can be used as a single source of truth for the rundown and operators can always update and view exactly the notes for every event they want to have. Without having to fear altering other details that could impact others. 

I could imagine to have an optional edit button in the operator view where operators can quickly add notes to their custom field on an event.

**Comment by alex-Arc** [comment]
Unless I'm misunderstanding this is already possible, but could perhaps use some more clear instructions
The trick is that it requires a long click (I believe this was done to make it work easily on mobile)

https://github.com/cpvalente/ontime/assets/19875125/59bb3602-7796-40d0-a5e6-8f4151640567

Or were you thinking of something else?
