### ISSUE TITLE
Roll mode crash when selecting before first event

### ISSUE THREAD

**Issue by daffydwal** [cpvalente/ontime#1042]
If I select roll mode before the first event in my rundown is scheduled to start, I see the message 'Roll: countdown to start' appear in the time view, and the correct time until start shows, but then the whole app crashes. Here's the log from Docker when the crash occurs:

![image](https://github.com/cpvalente/ontime/assets/54780667/0720d19f-961d-4008-b068-bcb927309284)

Love the app, though! Really amazing how versatile it is.

**Comment by alex-Arc** [comment]
@daffydwal thank you for the quick reaction
It should be fixed now the docker image will be up in a couple of minutes.

**Comment by daffydwal** [comment]
Just like that, fixed! That was quick, thanks very much!
