### ISSUE TITLE
Scale message to fit in Timer

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#1067]
## The issue
Currently, the timer view shows the messages from the Editor in a fixed size.
This means that, with enough text content, the view overflows and the messages are not readable.

![too much stuff in timer](https://github.com/cpvalente/ontime/assets/34649812/9df1a54f-9949-4e84-a9f3-0c2e20fc765d)

Since this is screen specific, there is no way for the editor to know of the overflow, which makes matters worse

## The task
The issue task is to modify the message display to always fit the message on the screen

Follow [here for the code entrypoint](https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/viewers/timer/Timer.tsx#L176)
We also have a copy of [useFitText](https://github.com/cpvalente/ontime/blob/master/apps/client/src/common/hooks/useFitText.ts) which could potentially be used here

**Comment by asharonbaltazar** [comment]
Clarification: the text should always fit the screen regardless of how many words it contains. If it contains too many words, the text size should be resized until it can fit the screen. Does that sound correct? 

Is there a limit to the characters? What is someone pastes the entirety of War and Peace?

**Comment by cpvalente** [comment]
> Clarification: the text should always fit the screen regardless of how many words it contains. If it contains too many words, the text size should be resized until it can fit the screen. Does that sound correct? 
> 
> 
> 
> Is there a limit to the characters? What is someone pastes the entirety of War and Peace? 

Hi!

Yes. We should make sure that the text always takes the whole size to fit. The text should be able to break lines as needed though

We don't enforce limits. We likely will need (and want) upper and lower limits for the algorithm. War and peace might not workout...

**Comment by cpvalente** [comment]
Done and released in v3.5.0
