### ISSUE TITLE
Timer messages and OSC

### ISSUE THREAD

**Issue by Mboitnott** [cpvalente/ontime#1095]
Great app!

on my editor, there is a field in the bottom left called “Timer”

Here I can add a message and then flash it on the screen, or blink it, or black the screen.

how do you control this with OSC?
And on the help docs, yours also has a spot for lower thirds message. How do i edit those things?

**Comment by cpvalente** [comment]
Hi, Thank you for reaching out. I am assuming we are talking about v3, 

> Here I can add a message and then flash it on the screen, or blink it, or black the screen.

I see the documentation is unclear about this and I will make some changes.
This is part of the message feature, so you would do 
```
/ontime/message/timer/text add-your-text
/ontime/message/timer/visible true | false
```

> And on the help docs, yours also has a spot for lower thirds message. How do i edit those things?

Can you please show me the link you are following? the newer documentation is at https://docs.getontime.no/ and there should be no mentions to editing the message in the lower thirds from the editor

The lowers are configured by using the settings menu in the view, you can then copy the URL it provides to save your configuration

Hope this helps

**Comment by Mboitnott** [comment]
Sorry was responding on email. Here’s the picture 
![IMG_2840](https://github.com/cpvalente/ontime/assets/88887353/69d344a3-2370-4dbf-a726-b546d9e73fb8)

**Comment by cpvalente** [comment]
> Hello! Thanks for getting back to me. So I am referring to this picture on the app editor section of the documentation. It has a line for lower third and public/backstage screen message. And thanks for sending the OSC info for the timer message. The documentation lists the external message but not that one. Is there a way to flash it or black the screen with OSC?

Thank you, the screenshots is from the betas before we decided to remove the feature, I will update that and the documentation, meanwhile, you can also flash the message and blackout screen. In general, anything the UI can do can be done with the APIs since the UI itself consumes them

```
/ontime/message/timer/text add-your-text
/ontime/message/timer/visible true | false
/ontime/message/timer/blink true | false
/ontime/message/timer/blackout true | false
```

**Comment by Mboitnott** [comment]
Great thanks for the help. I plan to use this with my companion set up. It's an awesome app

**Comment by alex-Arc** [comment]
> Great thanks for the help. I plan to use this with my companion set up. It's an awesome app

Then you should have a look at the companion module
https://github.com/bitfocus/companion-module-getontime-ontime

**Comment by Mboitnott** [comment]
Well don't I feel silly now!
