### ISSUE TITLE
12 Hour Format for Timer Clock

### ISSUE THREAD

**Issue by Mboitnott** [cpvalente/ontime#1112]
Hello! When I set an event in clock mode, it defaults to 24 hour time. How do I get it to show 12 hour time?

I have changed the internal setting to 12 hour but that doesn't seem to change the timer

**Comment by cpvalente** [comment]
Hi @Mboitnott , thank you for reaching out

In Ontime there are two ways of changing the clock format

**You can change it per view.** 
- navigate to the `/clock` view
- open the settings menu in 
- in the `Time format string `enter what you would like to see, possibly something like `hh:mm:ss a`
- click `save`

You should now see the clock formatted as you indicated

You can change the clock settings globally for the app
- navigate to the` /editor` view
- open the settings and navigate to `App settings` > `view settings
`- Select `12 hours` in the dropdown under `Time Format
`- Click `Save`

If you now open any window and navigate to `/clock`, the clock value should be in 12 hour time

I have just tested both and these seem to work fine, is this not the case for you?

**Comment by Mboitnott** [comment]
I do see that with the Clock window.

I am referring to the clock that appears if you go to Stage Timer when the event is set to clock. I can't seem to get it to be in 12 h.

I have attached a couple of pictures![image](https://github.com/cpvalente/ontime/assets/88887353/bc2e6a92-dd60-4f4a-9f10-9f2e6c881730)

**Comment by cpvalente** [comment]
Hi @Mboitnott , thank you for clarifying, I can se that we miss the logic to format the clock when it replaces the timer. 
Thank you for bringing this to my attention

**Comment by Mboitnott** [comment]
Hey! Forgive me because I have no idea how GitHub works. I see that you branched this off to a bug. Will that status change when it's fixed?

Also I understand it wouldn't change until you push a new version.

**Comment by cpvalente** [comment]
> Hey! Forgive me because I have no idea how GitHub works. I see that you branched this off to a bug. Will that status change when it's fixed?
> 
> Also I understand it wouldn't change until you push a new version.

No worries. 

I have created a fix and it has not yet been verified by other developers. Once that happens we merge the fix into the code and make a release

When merging the fix we can automate to close the issue. But we often prefer to have the user that created the issue verify the new release and close the issue manually.

I will reach out once the fix is released. During summer several of us are busy in festival season and things are a bit slower than usual

**Comment by Mboitnott** [comment]
@cpvalente good luck on shows this summer. Things are are slower for us no, but picks back up in Sept. we are mostly corporate

**Comment by Mboitnott** [comment]
Hello! I saw you this was closed. @cpvalente you mentioned reaching out to me to try it out? Will that happen at a later date?

**Comment by cpvalente** [comment]
Hi @Mboitnott , thank you for reminding me.

I see I did the opposite of what I said I would, apologies for this.
The fix is released in the latest version v3.4.0, would you mind taking a look and giving us some feedback?

**Comment by Mboitnott** [comment]
@cpvalente seems to work fine for me! This is exactly what I was looking for!
