### ISSUE TITLE
Local host network limit?

### ISSUE THREAD

**Issue by Mboitnott** [cpvalente/ontime#1118]
Hello! So if I'm hooking on time into a closed network, and network into on multiple devices, is there a limit to how much I can do this?

I am under the impression that OnTime does not use the internet to store the pages, so is there a limit you'll hit on local?

**Comment by alex-Arc** [comment]
Hey @Mboitnott 
Ontime doesn't need internet to work

(Other than the Google sheets import, will of course not work)

**Comment by Mboitnott** [comment]
Right, that makes sense. That's my  question then. Is there a limit for my local network? How many devices can I have accessing the on time program?

**Comment by cpvalente** [comment]
Hi @Mboitnott , thank you for your questions.

I am not sure we can provide a definite answer for you, but maybe this is good enough: 
Ontime infrastructure is the same as many of the web services you use and can theoretically handle a few tenths of thousands of requests a second.

We have no reason to believe that, in normal conditions, you will be hitting limits in the system.

The likely bottlenecks you may find are related to network availability. Potentially processing - if you run Ontime in a low power device like a raspberry Pi which has many responsibilities. 
For all these issues you can scale out of it by upgrading the infrastructure around Ontime.

Having said this you could push its boundaries by making it accessible to the public where the number of users accessing is potentially very large. This is not something you should be doing (with Ontime at least)
In general, we recommend that Ontime is kept in a production network with restricted access. Anyone that can access Ontime can also act maliciously towards the application data.

**Comment by Mboitnott** [comment]
Makes sense. We are fairly small company, so I wouldn't be doing more than 10, and more likely just 2.
