### ISSUE TITLE
Integrations appear to not trigger when in "Roll" mode

### ISSUE THREAD

**Issue by bicciess** [cpvalente/ontime#1125]
Hello there. 
Firstly, thank you very much for this project. 
I've tested this a few different ways, so apologies if I've missed something here.

It appears that some OSC and HTTP integrations do not trigger when in "Roll" mode. 
Specifically it appears that the "On Warning", "On Start" and "On Load" don't play ball during roll mode.

I've tested this by setting up a series of test events and using "Start" and pressing "Next". I can see the integrations triggering in these conditions. But if I then go back to roll mode (making sure to change the time of events so they will run) it doesn't appear that the integrations fire. 

The "Every second" cycle does appear to work in all conditions.

Let me know if you require any more detail

**Comment by cpvalente** [comment]
HI @bicciess , thank you for this.

I just had a quick look and it seems that you are correct.

We have a few tasks on the pipeline which i want to prioritise, but I will be taking a look at the roll mode as soon as that is through.

**Comment by cpvalente** [comment]
Hi @bicciess , I am testing some code that hopefully solves the issue you describe, are you available to help us with the testing?

If so, could you please get in touch on email at mail@getontime.no

**Comment by cpvalente** [comment]
Closing this ticket as completed
