### ISSUE TITLE
Excel Export of Running order

### ISSUE THREAD

**Issue by iainharvey42** [cpvalente/ontime#113]
Would it be possible to add the functionality to export the cue sheet as a PDF?

**Comment by cpvalente** [comment]
Hi @iainharvey42, thank you for taking the time.

This sounds good. I would expect it to be part of the cuesheet view.

Meanwhile: 
Is there a specific reason why the existing excel export is not preferable? It gives you a layer of control before the pdf (styling, branding, data adjustments...
Just trying to understand the use case

**Comment by cpvalente** [comment]
Reusing this issue for a excel export issue which will be part of improvements in cuesheet.
