### ISSUE TITLE
Lower Thirds?

### ISSUE THREAD

**Issue by Mboitnott** [cpvalente/ontime#1147]
Quick question, I was wondering what the use case would be for the lower thirds look? It seems to only pop up when you first open it or when the event starts (I see that in the options)

Would there be a way to just make it stay up there?

Thanks! This program is awesome

**Comment by alex-Arc** [comment]
hey @Mboitnott 
There were more options for the lower thirds previously, but we decided that it was not core to the app
So we stripped it back to a simpler version. And would recommend that if a more complex setup is need that the lower thirds rendering is done in a different program.
You can then use the Ontime API to set contents, fx in VMIX 
https://docs.getontime.no/quick-tips/integrate-with-vmix/#control-vmix-from-ontime

**Comment by Mboitnott** [comment]
Thanks!
