### ISSUE TITLE
Get time from CasparCG

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#115]
Would be nice, if the remaining time of an videoclip out of CasparCG could be displayed in ontime. 
Time is available via OSC: https://github.com/CasparCG/help/wiki/OSC-Protocol

**Comment by cpvalente** [comment]
Hi @Keksstar, thank you for your suggestion.

It is unlikely that I would create a workflow specific for CasparCG.
However, I like the idea of being able to add dynamic text to screens, specially the stage timer screen.

I could create an API for setting this (OSC, HTTP and websocket), you would then need to add a control layer between Caspar and ontime to achieve what you need. what do you think?

**Comment by Keksstar** [comment]
That would be awesome! The Middle-thingy is then done easily...
It would be great if the time of an timer could be set with this too. This would come in handy for situations like:

Speaker on Stage... has 2min for talking... Intro of Event starts, Speaker walks of stage, can see the remaining time backstage, walks in just before the end of the video clip. That´s how it should be...

Sure, speaker could see it also as dynamic text, but this wouldn´t work at the end with my lovely #100 ;-)

**Comment by cpvalente** [comment]
Hi @Keksstar, I have some availability to work on this feature. 
I would create an endpoint in OSC / HTTP / Websocket for setting a custom message. this would effectively shrink the timer slightly to show inline.

![custom message](https://user-images.githubusercontent.com/34649812/188233118-c4028880-c5c9-4acc-9b5d-487298dc0a4d.PNG)

What do you think of the workflow?
Are there any other screens where it would make sense that this should be present?

**Comment by cpvalente** [comment]
Hi @Keksstar ,
We have some reports of ontime views not rendering in Caspar CG.

We also have a release version which increases support for legacy browsers and hopefully fixes the issue. But none of us here use Caspar CG and can test 

Would you be available to report on this?

**Comment by Keksstar** [comment]
You're referring to the topic where the ontime "website" is not rendered in Caspar. (this is 95% due to outdated browser versions in Caspar and not an ontime topic)

Getting time from Caspar via OSC is the same as getting time from Millumin, Mitti, etc.
Little middleware will solve the translation vom Caspar OSC time to ontime.
But therefore it needs an entry point in ontime as discussed in #318
