### ISSUE TITLE
Autostart next timer

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#116]
Would be nice to have the ability to autostart the next timer when the current one finished. Useful for breaks or similar.

**Comment by je71175** [comment]
Yes. I think this would be good to set at the individual cue level - ie “auto start next cue” as a setting

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Keksstar ***@***.***>
Sent: Tuesday, May 17, 2022 7:03:17 AM
To: cpvalente/ontime ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cpvalente/ontime] Autostart next timer (Issue #116)


Would be nice to have the ability to autostart the next timer when the current one finished. Useful for breaks or similar.

**Comment by cpvalente** [comment]
Hi @Keksstar , this has been implemented in v2. Would you be available to participate in the next round of beta testing?
Please get in touch at mail@getontime.no, and I can provide some context. Alternatively you can see the beta releases in GitHub https://github.com/cpvalente/ontime/releases

**Comment by Keksstar** [comment]
Works perfectly and is lovely implemented. Good work there!
