### ISSUE TITLE
Websocket implementation changed in v3.4.0 beta?

### ISSUE THREAD

**Issue by 7omas** [cpvalente/ontime#1182]
Hi

Tested 3.5.0 a few days ago and tried to change events using Chataigne with the OnTime-module. Nothing would update. So today I tried different versions to try and pinpoint when that functionality stopped functioning.
In 3.3.3 it works as expected (as well as the 3.4.0 alpa-timeline-2) but in v3.4.0 beta the change no longer happens.
When sending the websocket request to change you get a response with 'success' but nothing happens.

All other commands I've tried works as expected so this only seems to apply when trying to use 'Make Change'.

**Comment by alex-Arc** [comment]
Hey @7omas thanks for catching this 
I believe we have found the issue

**Comment by 7omas** [comment]
initial testing seems promising.
All change commands works as expected except linkStart, which gave "not permitted".

Thanks for the quick fix @alex-Arc
