### ISSUE TITLE
Items Dont Fit On Screen Properly 

### ISSUE THREAD

**Issue by Dogo69Dog** [cpvalente/ontime#1189]
I think the items on the screen here can be fit better. it looks a little too clustered 
![IMG_12D3E20F767C-1](https://github.com/user-attachments/assets/510cd18a-0e75-4fb3-94d4-cbf54e1022a1)

**Comment by cpvalente** [comment]
> I think the items on the screen here can be fit better. it looks a little too clustered 
> 
> ![IMG_12D3E20F767C-1](https://github.com/user-attachments/assets/510cd18a-0e75-4fb3-94d4-cbf54e1022a1)
> 
> 

Hi! Thank you for this.
This does look strange, what resolution screen are you using and what is the zoom level?

**Comment by cpvalente** [comment]
Thank you @Dogo69Dog 
We do have plans to improve the responsiveness of some of the screens.
However, I believe that, in this case, there should be some tempered expectations on how much we can achieve.

As a workaround, I would suggest removing parts of the UI, like the cards

For now I will close this ticket as we do not plan on making changes here. But I hope that, in not too long, we will have some time to revisit the designs
