### ISSUE TITLE
OnTime Send OSC To QLAB

### ISSUE THREAD

**Issue by Dogo69Dog** [cpvalente/ontime#1190]
is there a way to have OnTime send OSC or MIDI to QLAB? I want to try this locally first but then when Its showitme i would have OnTime on one device and then QLAB on another device so will it still work? How can i send OSC in OnTime?

**Comment by jwetzell** [comment]
Ontime can output OSC if you go into the settings under "Integrations" -> "OSC Settings". I've attached a screenshot with some relevant settings highlighted. The target IP would be the IP of the machine that is running QLab. 


<img width="805" alt="Screenshot 2024-08-25 at 12 59 31 PM" src="https://github.com/user-attachments/assets/c2c551e4-56be-437d-97fe-ae27b723c679">

**Comment by Dogo69Dog** [comment]
Thanks, I took a look at the Docs and saw it there

**Comment by Dogo69Dog** [comment]
Uh i think you could help me more if i explain what im trying to create. In OnTime im trying to have it start cues in qlab and stop them. Ive figured out how to start a cue but for ending one im not sure. Each cue has a different duration so is there a way to seperate each cue in OnTime so its following the order in QLAB

**Comment by jwetzell** [comment]
I'm not sure what you are trying to accomplish but you can use variables in the OSC integrations so something like this `/cue/{{eventNow.cue}}/panic` or `/cue/{{eventNow.cue}}/go` to target specific cues for specific events.

**Comment by jwetzell** [comment]
Yeah, what I sent would do that. Set the cycle to `On Start` and the address to `/cue/{{eventNow.cue}}/go`.

**Comment by Dogo69Dog** [comment]
Im confused on which part i should replace with my cue number

**Comment by jwetzell** [comment]
I hope this helps, I'm not sure I have any other way to explain it if it does not.

**Comment by Dogo69Dog** [comment]
Ok im understanding a little bit more now, Instead of using evenNow.Cue is there a way to specify a cue. So this way i can make a integration for each cue i have in OnTime and have it execute a set cue number in qlab

**Comment by jwetzell** [comment]
So you could do something like this.

Add a custom field called `qlab` (or whatever makes sense for you)
<img width="832" alt="Screenshot 2024-08-25 at 9 12 00 PM" src="https://github.com/user-attachments/assets/4f83e23e-a4d6-457c-a004-9dfec375fb6d">

Then on each event you can specify what QLab cue should be run with the value of this custom field.
<img width="620" alt="Screenshot 2024-08-25 at 9 12 47 PM" src="https://github.com/user-attachments/assets/36c0f6d9-4d6d-473a-aa6f-8d08b8c2ad06">

Then for the address use `/cue/{{eventNow.custom.qlab}}/go`

**Comment by Dogo69Dog** [comment]
Thank you for that method, its working now

**Comment by jwetzell** [comment]
Thanks happy to help!

**Comment by Dogo69Dog** [comment]
Is there a way to have OnTime stop a cue in QLAB? I tried using this Address /cue/{{eventNow.custom.qlab}}/stop but it didnt really work

**Comment by jwetzell** [comment]
You would have to look up the available cue actions  in the QLab [OSC dictionary](https://qlab.app/docs/v5/scripting/osc-dictionary-v5/). `/stop` seemed to work in my local testing (I was using the "On Finish" cycle in the integration).

**Comment by Dogo69Dog** [comment]
thanks, that worked
