### ISSUE TITLE
Remove Dleay

### ISSUE THREAD

**Issue by Dogo69Dog** [cpvalente/ontime#1195]
Is there a way to remove this gap in the screenshot. I think its from a delay. 

<img width="1672" alt="Screenshot 2024-08-27 at 7 47 52 PM" src="https://github.com/user-attachments/assets/d287d0d4-4648-4c05-a061-f74ec7e4a81b">

**Comment by alex-Arc** [comment]
Hey @Dogo69Dog 

This icon
![image](https://github.com/user-attachments/assets/3685487c-84e2-41dd-9aad-cda16126e21b)
means that the start time is not linked to the end time of the pervious 

if you don't want to link the events you will have to adjust the start time manually

**Comment by Dogo69Dog** [comment]
How do I link the events?

**Comment by alex-Arc** [comment]
you just click this icon
![image](https://github.com/user-attachments/assets/3685487c-84e2-41dd-9aad-cda16126e21b)
and it will turn green and become linked to the previous event

in your screen shot it is here
![image](https://github.com/user-attachments/assets/6ffd01f9-6ee4-4082-a5ed-b132fb0d9ab7)

**Comment by cpvalente** [comment]
Closing this as there is no active follow up needed from our side.
Feel free to reach out if you need any further help here
