### ISSUE TITLE
Using Media

### ISSUE THREAD

**Issue by DaRealFrost** [cpvalente/ontime#1199]
I have a question about whether there are any plans to add the ability to link media to an event. The duration of the event would be automatically set to the length of a video and or manually set for a normal image. Maybe you can use a route like http://localhost:4001/Video to access it the live video feed. Whilst I'm here maybe audio too. http://localhost:4001/Audio. Linking that to events would be nice but it could become an issue if you want to stop at a certain time. I'm doing my own implementation of this with the http api but it's kinda tedious. So in general maybe like a feature to have more than one timeline as a part of one project, that would be the ideal scenario.

**Comment by cpvalente** [comment]
Hi @DaRealFrost , thank you for your suggestion.

I feel this would greatly expand the scope of the application into a playout system. That is not where we want to go and there are a lot of very capable systems out there at all sorts of price points.

For now, I think Ontime's mission should be to play well with others, so the real problem to fix here is that it shouldnt be so painful to link Ontime to your playout software

> I'm doing my own implementation of this with the http api but it's kinda tedious

Can you add some details about how are you working here? Maybe there is something in the workflow that we could help with?

> So in general maybe like a feature to have more than one timeline as a part of one project, that would be the ideal scenario.

This seems to me like a different request. It is unlikely that Ontime will ever have multiple timelines. Could you please expand on what would you expect the multiple timelines to give you?
Perhaps what we actually need is multiple playbacks, not multiple rundown. Multiple playbacks is definitely something we want to consider

**Comment by DaRealFrost** [comment]
For context, I'm using OBS to control all my camera feeds and the graphics and audio.

> Can you add some details about how are you working here? Maybe there is something in the workflow that we could help with?

Currently, I am using custom fields to change feeds load graphics and edit audio. I use the on-load and on-start HTTP API that send info to my API and then I process everything from there, but like if I want to do more than one action at once it kinda becomes difficult cos I have to make up some janky way to do that, atm I make events which last 0 seconds and it fills the timeline very fast.
![chrome_8bD275infp](https://github.com/user-attachments/assets/bbb73fb1-669c-4267-8d90-a4eb02110f08)

> This seems to me like a different request. It is unlikely that Ontime will ever have multiple timelines. Could you please expand on what would you expect the multiple timelines to give you?

I think I explained it wrong, but similar to how CuePilot or LiveEdit allow you to have multiple layers of events, that would simplify my issue above very much as I could split everything up. 
![chrome_teKe246Rgs](https://github.com/user-attachments/assets/0dd7bb50-84a0-4e08-bb44-9c7557636ed8)

**Comment by 7omas** [comment]
How would you feel about adding another piece of software in the mix?
Some of these things could perhaps be made using Chataigne.
It has community modules to connect to both Ontime and OBS using websocket connections.

**Comment by DaRealFrost** [comment]
> How would you feel about adding another piece of software in the mix?

I'm not opposed to it as long as it does not overcomplicate things

**Comment by cpvalente** [comment]
Hi @DaRealFrost , we had a sync today and discussed this issue.
We understand the value and appeal of such sequencing interface, but feel that the market is already well served with cuepilot and friends.

The conclusion being that, for now, this is not the right direction for Ontime and this is not something we will work on.

However, as I mentioned before, integrating with your workflow should not be painfuil. 
If you can send your project to mail@getontime.no and detail to us what you are trying to achieve and what roadstops you are finding, we will investigate whether we could simplify the flow

**Comment by cpvalente** [comment]
Closing the ticket as we have no further possible steps
