### ISSUE TITLE
New screen: countdown

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#120]
User request:
We need a way to show a countdown to a specific event

This screen includes a feature to countdown to anything, this should probably be done in the URL parameters,
eg: `<ip-address>:4001/countdown?event=2`
would produce a screen with a timer counting down to that event

This is a great addition to the aliases feature so you could use `<ip-address>:4001/bar` to signify `<ip-address>:4001/countdown?event=2`(where event 2 could be a lunch break), It is then possible to change from the app side what the /bar alias is counting down to without needing input from an external operator

Few things to decide
- what are the parameters accepted? could you do `event=eventId `or event=`eventName`?
- what happens after the event is finished? 

Some help defining this would be appreciated

**Comment by je71175** [comment]
This sounds neat

I imagine there 2 timers.

  *    countdown to event starting
  *   Once the event has started the running time

My thoughts to questions


things to decide

  *   what are the parameters accepted? could you do event=eventId or event=eventName?  Both
  *   what happens after the event is finished?  “Ended time: hhhmmss”

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Carlos Valente ***@***.***>
Sent: Thursday, May 19, 2022 5:57:16 PM
To: cpvalente/ontime ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cpvalente/ontime] New screen: countdown (Issue #120)


User request:
We need a way to show a countdown to a specific event

This screen includes a feature to countdown to anything, this should probably be done in the URL parameters,
eg: <ip-address>:4001/countdown?event=2
would produce a screen with a timer counting down to that event

Few things to decide

  *   what are the parameters accepted? could you do event=eventId or event=eventName?
  *   what happens after the event is finished?

Some help defining this would be appreciated

**Comment by cpvalente** [comment]
Hi @je71175 , thank you for your input. That makes sense to the feature behaviour

I am not too sure about parameters though.

**eventId** is the best one, it will never change regardless of what happens to the event. However 
- you dont know the id before creating the event in ontime (cannot prepare the screens without aliases)
- if the event gets replaced (eg. event deleted and created a new one in place), there is no way for the screens to know

**eventname** is very tricky and I wonder how useful it would actually be.
There is a very short list of character allowed in an url parameter, escaping all of this sounds like a painful task 
<ip-address>:4001/countdown?eventname=my%20event%20name
Also how thight should the match be? would it need to be an exact match to the title? the first partial match found in the list

**Comment by je71175** [comment]
Rather than event name as text, what about event number - same behaviour as using the OSC 
/ontime/goto int event order eg: (1)
thanks

**Comment by cpvalente** [comment]
That sounds good, we could have eventId and event as parameters.

`<ip-address>:4001/countdown?event=3`
`<ip-address>:4001/countdown?eventId=7jsi2`

**Comment by je71175** [comment]
Perfect. Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cpvalente** [comment]
Released in v1.3.0

**Comment by je71175** [comment]
Good point!  Then event number 1, 2, 3 etc. same number as you have for osc implementation ..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cpvalente** [comment]
Hi @je71175, did you mean to reopen the issue with any new information?

**Comment by je71175** [comment]
Sorry - no, I didnt mean to.  Have removed the old/resent email..
