### ISSUE TITLE
Feature request: chroma key background

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#1227]
Would like to request another view: “key”

Usage:
Many a time I bring the Minimal view into a video switcher, then overlay it over the presenter view. Would love to key out the background. Would be nice to have the white timer numbers and colon have a small black border too.

Settings:
- background color picker. Defaults to ##00ff00 (full green)

View:
- same as Minimal, except it shows the selected colored background.

**Comment by cpvalente** [comment]
Hi @tcconway, this sounds good to me
However I dont understand why would we not prefer adapting the minimal timer here.
The minimal timer already has a background key colour, just misses the borders you mention

Maybe I misunderstood?

**Comment by lukestein** [comment]
> Would like to request another view: “key”
> 
> Usage: Many a time I bring the Minimal view into a video switcher, then overlay it over the presenter view. Would love to key out the background. Would be nice to have the white timer numbers and colon have a small black border too.
> 
> Settings:
> 
> * background color picker. Defaults to ##00ff00 (full green)
> 
> View:
> 
> * same as Minimal, except it shows the selected colored background.

Just confirming that the following URL format works for me, although there is no black border around the font. (Not sure whether this is an easy css customize): `http://ontime.home/minimal?key=00ff00`

<img width="1009" alt="image" src="https://github.com/user-attachments/assets/0ee3e2ee-2d1e-4e35-b731-e4710a04ecd9">

**Comment by cpvalente** [comment]
Closing this as it is likely a side effect of lacking documentation.
Please feel free to reopen if we have missed something
