### ISSUE TITLE
Delay - Make Permanent has no impact?

### ISSUE THREAD

**Issue by juzz197** [cpvalente/ontime#1230]
When adding a delay, I see the amended, new times above the scheduled times in rundown.  

When clicking 'Make Permanent' I was expecting the scheduled times to update to include the delay but nothing seems to happen - is this the correct behaviour?

Thanks as always!

**Comment by juzz197** [comment]
I see that when creating the delay, everything works as expected, e.g.

1) Event starts at 20:00:00
2) Create delay of 00:05:00 immediately before
3) New Start shows as 20:05:00 and this is reflected on the backstage view

However, when I then click 'Make Permanent', in the delay, the delay disappears and my times revert to their originals i.e. 20:00:00 start in the example and not 20:05:00 as I was expecting.  

Am I misunderstanding the the 'Make Permanent' function?

I can do a screen recording if that'll help.

Thanks!

**Comment by cpvalente** [comment]
> I see that when creating the delay, everything works as expected, e.g.
> 
> 1. Event starts at 20:00:00
> 2. Create delay of 00:05:00 immediately before
> 3. New Start shows as 20:05:00 and this is reflected on the backstage view
> 
> However, when I then click 'Make Permanent' in the delay, the delay disappears and my times revert to their originals i.e. 20:00:00 start in the example and not 20:05:00 as I was expecting.
> 
> Am I misunderstanding the the 'Make Permanent' function?
> 
> I can do a screen recording if that'll help.
> 
> Thanks!

I see, that is not expected to happen. The screenshot could be helpful

If you prefer you can drop into the discord server and I can try to help you there later today 
https://discord.com/invite/eje3CSUEXm

**Comment by juzz197** [comment]
Here's the screen recording.  I have some commitments this evening but will try and drop into the discord if I can.

**Comment by cpvalente** [comment]
Thank you @juzz197 , I found the issue.

In v2, you could use blocks to prevent a delay from propagating. This was changed in v3 in a way that you need a gap in scheduling or a positive delay to do so

It seems that we forgot to update the logic to apply delays.
I will open a task and we will make sure this is fixed in the next release

Meanwhile, you can add the delay after the block and everything should work as expected

**Comment by juzz197** [comment]
I've run a few tests and everything is working as expected now.

Thank you!
