### ISSUE TITLE
Ability to disable or change ALT+1 shortcut.

### ISSUE THREAD

**Issue by bilalg86** [cpvalente/ontime#1235]
It would be helpful to be able to change or disable the Show App shortcut key combination ALT+1. For me it clashes with another software I use.

**Comment by cpvalente** [comment]
Hi!
This shortcut will be removed from Ontime, this should be available in the next release

**Comment by cpvalente** [comment]
Hi @bilalg86, can you please check the new release v3.6.0 and confirm whether the issue is resolved?

**Comment by cpvalente** [comment]
closing this as completed and released

**Comment by bilalg86** [comment]
Thank you for the quick turn around and apologies for the late reply. I can confirm the issue is resolved.
