### ISSUE TITLE
Change colour of last event

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#125]
Would be great if the colour of the last "played" event could be changed, like change it to gray or similar. This could come in handy for the cuesheet as you normally don´t care about the past. It´s more interesting what comes up next...
Gives more clear visual indication of where you are.

Btw: Congrats to V1 :-)

**Comment by cpvalente** [comment]
Thank you for you comment and for your involvement.
This can definitely be part of #55 but I wonder if it should be optional behaviour?
I know some users use ontime just a timer generator, so they would make a Qlist like
- 1 min timer
- 5 min timer
- 10 min timer

and from there use OSC to control these. In this case there is no sense on a before / after. 
Also ontime doesnt really care about the order of the events, but about the start time. 

Either way this is a good suggestion and I believe it can go a long way on user experience. I will take a look

**Comment by Keksstar** [comment]
Definitly a good part for #55 - Thanks for adding this!

**Comment by cpvalente** [comment]
Hi @Keksstar , is this issue still relevant in v2?

**Comment by Keksstar** [comment]
Sure, it's still present.

**Comment by cpvalente** [comment]
Hi @Keksstar , with the release of beta-6 we have made it so that all events previous to the loaded event are faded out.

Having fade apply to the event immediately before is something we need to calculate and we felt it doesn't provide enough value for the trade off.

I will eventually close this issue but am still hoping to get your feedback ion the implementation

**Comment by Keksstar** [comment]
Looks great in ontime. Sadly it´s not reflected to the Cuesheet. Would be great if this can be added there as well.

**Comment by cpvalente** [comment]
I believe this has been sufficiently handled in #435

**Comment by Keksstar** [comment]
I can´t see any difference in the Cuesheet. It´s still present there. It doesn´t show the same behaviour as the software itself.

**Comment by cpvalente** [comment]
> I can´t see any difference in the Cuesheet. It´s still present there. It doesn´t show the same behaviour as the software itself.

The new cuesheet is not yet deployed
