### ISSUE TITLE
Notes as Data sources

### ISSUE THREAD

**Issue by RasterboxOff** [cpvalente/ontime#1251]
With some iteration the notes of a cue were removed from the possible data sources in views. 
However, on simple rundowns it often is unnecessary to create custom fields and the one note box is enough to put down the name of the people on stage. It is a little bit unfortunate that the note is not available as a data source in all views. Many times this field will carry the names of the people on stage. 

It's missing in 
Timer - Main text
Public - Event secondary Text
Lower Thirds - both top and bottom text 
Operator - can't be a Highlight field

I think for consistency sake it could be in the hand of the users to utilize that text field anywhere. 

Thank you a lot for your consideration @cpvalente :)

**Comment by cpvalente** [comment]
Thank you @RasterboxOff.
I have added a task for us to improve this. I expect this will likely be out in a near future release as we are working on UX

Meanwhile: 

We consider that the note is a data type in the domain of the editor, in which case, the operator does not have write permission.
The operator should be able to use note as a data-source, but not as a highlight field (which is editable and, for us, it is data that belongs to operators)

**Comment by cpvalente** [comment]
Hi @RasterboxOff , this has been released as of 3.6.2, could you please confirm so that we can close this ticket?

**Comment by cpvalente** [comment]
Closing this task as completed, feel free to reopen if this is not accurate
