### ISSUE TITLE
Shortcut Zoom In doesn't work 

### ISSUE THREAD

**Issue by maurice941** [cpvalente/ontime#1256]
Pressing Ctrl + + in the editor in Ontime doesn't zoom in, while zooming out (Ctrl + -) works fine. 
The option in the views menu and clicking on Zoom In works as well.

**Comment by jwetzell** [comment]
I'm not able to reproduce this using latest chrome on macOS can you share your browser/os combo to see if it can be reproduced there?

**Comment by maurice941** [comment]
not in the Browser I mean in the app

**Comment by maurice941** [comment]
Version 3.6.1 on Windows 11.
I think its the same on win 10 but I don't know it for sure.

**Comment by jwetzell** [comment]
Thanks, the issue also is present on Linux builds. It's a long standing issue on Electron. I'll see if there is something we can do to work around this weird behavior from electron.
