### ISSUE TITLE
OSC API: control +- minutes

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#126]
OSC API should provide ability for +- minutes, so it can be controlled with Companion

**Comment by cpvalente** [comment]
Hi @Keksstar, that is perfect timing.
I have been planning on writting a Companion module but never really knew what to aim for.

It sounds like you use it, perhaps you could guide me here? Are there similar devices that have a similar workflow?

When it comes to your issue. This is already possible in the [OSC API as documented on gitbook](https://cpvalente.gitbook.io/ontime/control-and-feedback/osc).

The delay endpoint expects a string value. This value can be negative to remove time from a running timer
`/ontime/delay` `10` > Adds 10 minutes to running timer
`/ontime/delay` `-5` > Removes 5 minutes from running timer

Does this fit your use case?

**Comment by Keksstar** [comment]
Ahh! Wasn´t clear to me that "delay" is used for this. Works perfectly! Thanks
Should have read better.

Irisdown Countdown Timer uses a Companion Module as well... https://www.irisdown.co.uk/countdowntimer.html

Normally I gave an Streamdeck with Timer control to my customer, as it is their show and they know the timing better than me as technican. From there they could set predefined times, Play+Pause Timer, +-1 minutes and get visual feedback of the actual time - like you could see on the Irisdown website.

For Ontime it will need Prev+Next Event as well.

**Comment by cpvalente** [comment]
Yeah, delay is probably not a very well achieved name.  "It made sense at some point" as it is usually the case with apps that grow out of a roadmap.

Lots of timers out there.. When I started ontime I couldnt find that many, pretty interesting.
I will look into the companion API
