### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by forchinmaser** [cpvalente/ontime#1265]
On Mac OS Monterey, both Cmd+Z and Edit>Undo have no effect in the editor mode.

**Comment by cpvalente** [comment]
Hi @forchinmaser,

Undo is something we are getting from Electron, which we use to wrap the app
It will only work at a very basic level of text entry

I agree it provides incorrect expectations and we will remove this in the next release of Ontime

**Comment by cpvalente** [comment]
Closing this for now as we dont have actionable points for this
