### ISSUE TITLE
Modify Cuesheet View / Add new templates

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#129]
Is there a way to modify the Cuesheet Page somewhere in the final installation or just when using the Source Files? Would like to adjust column spacing and font size for different monitor sizes.
Thanks.

Also saw the Ontime Viewer Template... https://github.com/cpvalente/ontime-viewer-template
How to add this Template to an Ontime installation?

**Comment by cpvalente** [comment]
Hmmm, the cuesheet is probably the trickiest page to customise. But perhaps you can look into some css injector for your use case? There are plugins for chrome and apps that do this, unfortunately I have never used any

The viewer template tries to show how you can make your own view. You would just need to tweak the HTML + CSS + JS to work the way you need it to and serve it in any machine in the same network as ontime

Hope this was semi helpful

**Comment by Keksstar** [comment]
So there is no CSS File or similar to adjust the Cuesheet?

**Comment by cpvalente** [comment]
Every viewer has its own css file.
But when the app is distributed this is all compiled. no way that I can think of to tap into this other than building the app yourself

What changes do you have in mind?

**Comment by Keksstar** [comment]
Well... some things:
- When using an 4K display I can display up to two user fields without the need for scrolling, if I need more than these I have to scroll... on an HD display it´s not working at all... see attached screenshots.
- Column size can´t be varied, as it´s fixed value and not dynamically adjusted to window size.
- Text color & Size can´t be changed.
- "Follow selected" stays in middle of screen. As pointed out in #125 it´s more interesting what comes next. So the last two events is more than enough to see.

Can´t find the Cuesheet Viewer css in /client/src/features/viewers - is this /client/src/features/table?
As it´s nodejs, can it be compiled with an simple "make" or does it need more to compile?


<img width="1920" alt="cuesheet_4k" src="https://user-images.githubusercontent.com/15065206/169669965-0f573857-88bf-47a8-9a8d-d9e0f8e4013d.PNG">
<img width="960" alt="cuesheet_HD" src="https://user-images.githubusercontent.com/15065206/169669966-907b6d7a-be72-45b2-8f03-2bef88a969c8.PNG">

**Comment by je71175** [comment]
For a standalone display, we use a raspberry Pi and VNC into the PI's display to setup the tables view.  Once running with "follow selected" the table scrolls with the current cue visible (in the centre except for first and last cues).

**Comment by cpvalente** [comment]
I can see what I can do about the position of follow selected, perhaps we could make an issue detailing a list of improvements to cuesheet?
It will take a while for me to get there, but will do it eventually.

When it comes to the build:
- The style file is `client/src/features/table/table.module.scss`
- The easiest way to understand the build process is to look into the CI file build.yml (.github/workflows), it details all the steps to build the app in the pipeline.

If you need some help with any of this feel free to reach out at mail@getontime.no

**Comment by cpvalente** [comment]
Closing this. Tasks are extracted to #133

**Comment by Keksstar** [comment]
@cpvalente Downloaded the Template Viewer example... But how can I "run" it locally? Do I need an Webserver for it?
