### ISSUE TITLE
Custom output with Tiles 

### ISSUE THREAD

**Issue by hadphild** [cpvalente/ontime#1291]
It would be amazing to have a custom output that could be made up of tiles. So sizing would be easy. If you have a look at home assistant or even bitfocus companions presets / buttons.

Drag and Drop.

Then an option to backup these configs for portability to other shows.

**Comment by cpvalente** [comment]
Hi @hadphild , thank you for this.

We have discussed having user definable UIs with some drag and drop format.
For example #539 

In short, we all agreed this would be a good feature, but we never managed to prioritise it over other work in the app.

It may be that we would make something eventually, but meanwhile we would welcome a user PR with a suggestion.

You can also increase the chances of this being made by sponsoring a developer to work on the feature. I am happy to help where possible

**Comment by cpvalente** [comment]
Closing this as there are no further steps from our side
