### ISSUE TITLE
OSC Point Support

### ISSUE THREAD

**Issue by hadphild** [cpvalente/ontime#1292]
Have a way to get all the notes from Powerpoint using OSC point. 

Having and main and backup for pulling in all the notes. Having a countdown time to the notes would be really useful for one DSM.

**Comment by hadphild** [comment]
More to reduce down the DSMs you have onstage. There are a lot of applications that can extract notes from PowerPoint just think of one application that can do it all.

**Comment by cpvalente** [comment]
Hi @hadphild, thank you for this.

I find that this ticket leaves a lot of work for our side, it doesnt contain enough information for us to act on. So not only would we be implementing a request, we would also have to research your use case

In general, it is a good idea to assume that we dont know what you do or your tools and workflow.

> Have a way to get all the notes from Powerpoint using OSC point.
I had to google OSC Point, it sounds to me that this is a tool that companion can leverage. Would a reasonable solution be to use companion as a middle man to push data to ontime?

> Having and main and backup for pulling in all the notes.
I did not understand what you mean here, is this another request?

> Having a countdown time to the notes would be really useful for one DSM.
I also did not understand what are you calling notes. Also, what does the DSM do in your case?

> More to reduce down the DSMs you have onstage.
This further confused me, do you have multiple DSMs? Do you expect this feature to allow cutting production rules?

> There are a lot of applications that can extract notes from PowerPoint just think of one application that can do it all.
This is a great point. I dont think we want Ontime to do it all.
Our main focus is on making it easy for users to integrate ontime with the rest of the tooling, but there is no ambition that Ontime would be a one-stop-shop for show running

**Comment by cpvalente** [comment]
Closing this as we have no further possible steps to take on our side
