### ISSUE TITLE
color change for custom fields 

### ISSUE THREAD

**Issue by maurice941** [cpvalente/ontime#1305]
I've imported everything into Excel and want to change the color of a custom field. In Settings > Custom Fields, I'm unable to save the new color change until I give the field a new name.
![image](https://github.com/user-attachments/assets/d4cfc227-3898-4678-9e42-0307a09c6da5)

**Comment by cpvalente** [comment]
> ... I'm unable to save the new color change until I give the field a new name.


Thank you for this. We will prioritise a fix
