### ISSUE TITLE
Timer Type "None"

### ISSUE THREAD

**Issue by rob-fi** [cpvalente/ontime#1311]
It would add to the flexibility of ontime if you would be able to select a timer type of "None", or similar.

This would enable the timer view to remain on a display and show the now/next cards but without a timer.

It's possible to select "Clock" at the moment, and this is OK to a degree, but it sometimes also causes confusion or distraction.

Manual blanking is possible but that removes the now/next and also requires an operator remembering to do so (and then remembering to enable it again).

Thanks.

**Comment by cpvalente** [comment]
Hi @rob-fi , thank you for this

I am trying to understand what is the behaviour of this timer
Since it is in the next card, I assume it has a schedule, would it also have a duration? Would it still be playable? ie: can you be running a timer of type None?

If so, what do we show in the views when it runs? several of our backstage views depend on the timer duration for knowing if the show is on time. Is it that we still show the timers everywhere just not in the timer view?
What would the minimal view show (since all it does show is the timer)?

**Comment by rob-fi** [comment]
So my idea with this is that it is essentially no different to setting the timer type to Clock, except that in the timer view it would just be blank or show the same --:--:-- as if there's nothing running.

The use case scenario is when there's a stage monitor showing the timer output all of the time but there are many entries in the rundown that don't require the use of a timer because they're various items that are important for the production to keep track of but not of interest to someone on stage. The Clock timer is the option available at the moment, but the presence of the clock can sometimes be distracting to someone.

Blanking the timer is of course possible, but then what if someone forgets to enable it again? I'd rather not have to worry about blanking the timer and just choose whether an event has a timer or not at all.

Does that make it clearer?

**Comment by cpvalente** [comment]
Hi @rob-fi , thank you for adding this information

Yes, this makes things clear, and I believe this is a valid use case
We will bring this ticket up and follow up here, hopefully with a PR

**Comment by rob-fi** [comment]
My opinion is that it would be cleanest to simply not have any text at all where the timer would be.

The now/next cards would stay in their place as usual (if enabled) and whenever an event that has a timer other than "None" comes up, the timer will appear. 

My suggestion of the --:--:-- as an option was just in case it was felt that something should be there as a placeholder for consistency. But from a visual aesthetic point of view, I believe that there simply being no text where the timer would be is best. This is only my opinion though, and I'm happy to go with whatever if there's a strong opinion that there should be something else instead!

**Comment by cpvalente** [comment]
Hi @rob-fi , this was released as part of 3.7.0. 
Could you please review and give us some feedback? We would also want to close this ticket

**Comment by rob-fi** [comment]
Thanks @cpvalente. I finally got a chance to look at the implementation. I see you went with the --:--:-- option so I assume you feel that's important for consistency (or perhaps it's easiest to implement).

How do you feel about the fact that it continues to change colour in reaction to warning/over time (and add the red border for over time) in the timer view? Intuitively I'd expect that not to happen.

**Comment by cpvalente** [comment]
Hi @rob-fi , thank you for bringing this up
The issue above was a misstep which was fixed in v3.7.1, could you please give it another review with the latest version?

**Comment by cpvalente** [comment]
Closing this issue as completed and released in 3.7.1
