### ISSUE TITLE
Extract reports after events

### ISSUE THREAD

**Issue by tun-ji** [cpvalente/ontime#1317]
Is it possible to extract reports from ontime so I see insights like planned duration vs actual duration?

**Comment by cpvalente** [comment]
Hi @tun-ji, thank you for taking the time to reach out

There is currently no way to do this. 
However, we have actually been discussing a similar implementation and have called this feature "reporter".
We already have some work done and a PR. You can follow the progress here https://github.com/cpvalente/ontime/issues/1139

Unfortunately this is a busy time of year and it may take some time for us to land the feature in a release. Keep in mind that the first iteration will likely only show the times in the interface, and not yet make them exportable as you mention. 

Meanwhile, I took a look at your profile and wonder if you would be available to help us with Ontime?

**Comment by cpvalente** [comment]
Hi @tun-ji , I apologise for taking so long to reply. it is a busy season.

I will close this ticket as a duplicate. As for your collaboration, please hop into our discord server ([link in the readme](https://github.com/cpvalente/ontime?tab=readme-ov-file#links)) and we can find something that is relevant to how you use ontime
