### ISSUE TITLE
Change accent color

### ISSUE THREAD

**Issue by jochen-froehlich-gkgab** [cpvalente/ontime#132]
Is it possible to change the "red" default color which is used in all screens to a custom color to match our corporate color scheme?

**Comment by je71175** [comment]
And upload a logo too please 😊

**Comment by cpvalente** [comment]
Hey @jochen-froehlich-gkgab. Thank you for getting involved and for your suggestion

There are some features in the roadmap that are blocking worflows and those will receive priorities. I will leave this issue for sometime when I have an epiphany about how it could work.

Meanwhile, having a comprehensive issue would definitely help and I could just bite the bullet and make this into user settings at some point.
What sorts of things would it make sense to have user definable? 

Something like:
- Accent colour
- Background colour
- Text colour
?

**Comment by jochen-froehlich-gkgab** [comment]
Hi would it be possible to modify the colors as for the Lower Thirds function: https://cpvalente.gitbook.io/ontime/views/lower-thirds ?

**Comment by cpvalente** [comment]
Would that be preferable to a central configuration? 
I would imagine that the app settings could have a file with a list of main colours that the viewers could use

**Comment by jochen-froehlich-gkgab** [comment]
Yes that would be awesome. A central config file for all options would be great.  In the headless docker version this config parameters can be set via env vars in the docker compose.
This would keep all options in one place and make it easy for the users to configure.

**Comment by Keksstar** [comment]
Actually I´m using the Brower Dev-Tools to modify the speaker screen... Adjusting colors, get rid of actual and next event.
This should be customizable. My customers don´t like "gray" :-)

**Comment by cpvalente** [comment]
Hi @Keksstar .
A good way to achieve this is using local overrides (chrome only unfortunately) so that your changes will persist.

However there is currently a PR for adding a CSS override file. Would you be interested in contributing with testing?

**Comment by Keksstar** [comment]
Oh, didn´t know Chroma as persistant overrides. Nice.

@cpvalente I´m quite busy these days. I can test things, but I can´t code. (I know what happens at CSS and can adjust it, but can´t build from ground up)

**Comment by cpvalente** [comment]
Hi @jochen-froehlich-gkgab .
The newest release adds support for CSS overrides.

This is admittedly a more advanced feature but should be straightforward enough to figure out. The challenge might be finding the file which needs to be edited, which would depend on your installation. Something like 
```
ontime/extraResources/src/external/cad/override.css
```
In the example file which comes preloaded you will find the current toy available variables, including an accent colour.

I will close this issue for now in favour of opening specific issues for improvements
