### ISSUE TITLE
Add Chinese (Simplified) Translation

### ISSUE THREAD

**Issue by MaiJianxiang** [cpvalente/ontime#1324]
I am very amateur in programming, but I think I can provide Chinese (simplified) translation for Ontime.

[zh-CN.zip](https://github.com/user-attachments/files/17676285/zh-CN.zip)

**Comment by cpvalente** [comment]
> I am very amateur in programming, but I think I can provide Chinese (simplified) translation for Ontime.

Hi @MaiJianxiang , thank you for this.
I am not particularly comfortable opening a zip file from the internet, I hope you understand.

You can paste the translation object here and I will integrate it into the app

**Comment by MaiJianxiang** [comment]
```
export const langZhCn = {
  'common.expected_finish': '预计完成',
  'common.minutes': '分钟',
  'common.now': '现在',
  'common.next': '接下来',
  'common.public_message': '公众消息',
  'common.scheduled_start': '计划开始',
  'common.scheduled_end': '计划结束',
  'common.projected_start': '预计开始',
  'common.projected_end': '预计结束',
  'common.stage_timer': '舞台计时器',
  'common.started_at': '开始于',
  'common.time_now': '当前时间',
  'countdown.ended': '事件结束于',
  'countdown.running': '事件进行中',
  'countdown.select_event': '选择要关注的事件',
  'countdown.to_start': '到开始时间',
  'countdown.waiting': '等待事件开始',
  'countdown.overtime': '超时了',
  'timeline.live': '当前进行',
  'timeline.done': '已结束',
  'timeline.due': '即将开始',
  'timeline.followedby': '随后是',
};

export type TranslationObject = Record<keyof typeof langZhCn, string>;
```

**Comment by cpvalente** [comment]
Thank you @MaiJianxiang , I will add this to the next release

**Comment by cpvalente** [comment]
Hi @MaiJianxiang this has been released in 3.9.0, could you please verify this for us?

As a side note, I am unsure if we could be doing something better to reach chinese users, perhaps you would be able to advise us?
If so, please do get in touch on [email](mailto:mail@getontime.no) or [discord server](https://discord.com/invite/eje3CSUEXm)

**Comment by MaiJianxiang** [comment]
Sorry for my late reply. 

I propose to change 'common.stage_timer' to '剩余时间', which means remaining time, which is more appropriate.

If the "Editor" page is also allowed to be translated, I think it will be used by more non-English users. I know it needs a lot of work. Maybe we can use a multi-person collaboration platform like Crowdin to help with translation?

**Comment by cpvalente** [comment]
Hi,

I think that may be a good change and we can consider it when we get to review the backstage screen, but we would need to do it across all languages. So the change would be that the backstage screen says "Time left" rather than "Stage timer" on the countdown label

At this point a solution like crowdin is not viable for us.
Ontime is developed on the spare time from our full time jobs and I fear it would complicate the development process.

If Ontime Cloud becomes a viable solution we could be in a better place to reconsider

**Comment by cpvalente** [comment]
Closing this as completed
We can open tickets for app translations separately
