### ISSUE TITLE
Multi-Event / Multi-User

### ISSUE THREAD

**Issue by JavierChaparroMX** [cpvalente/ontime#1325]
I have been loving organizing my events with Ontime!, we have around 65 events per year between Weddings, Corporate events etc, and I was exploring giving my customers the option to "Sign-in" and move the "Itinerary" objects to their liking or maybe at least the option to have an event "Loaded" depending on who signs in to be able to edit or Run more than one event at the time.

**Comment by cpvalente** [comment]
Hi @JavierChaparroMX , while the Ontiem infrastructure does not lend itself for this type of requests, we have recently released a cloud solution which does.

You are welcome to give it a try by visiting [our website](https://www.getontime.no/) and reach out for suggestion on how we can improve it

Meanwhile, we will close this ticket as it is not within reach of Ontime
