### ISSUE TITLE
Possibility for multiple Stages/simultaneous Events in one File

### ISSUE THREAD

**Issue by lx05** [cpvalente/ontime#1328]
Is it possible to have multiple Stages with individual Timers and Cuesheets? All in one file. So you can select which stage you want to see or if you want to see both stages. This would also make it easy to have one big overview over all events happening on all stages.
Or is it just easier to host multiple Docker instances for each stage? This would only make it impossible to have one big cuesheet for the production assistant or other people...

**Comment by cpvalente** [comment]
Hi @lx05 thank you for this

The way that we think about Ontime, is that is a show tool like d3 or qlab, ie: one project per show.

The correct way to achieve a multi-stage setup as you mention, would be by running Docker instances per stage.
We are also planning a release of a cloud version of Ontime which will hopefully make this easier.

In the future we plan on making views that gather information from multiple stages, but this has to follow the ongoing efforts with new features and design reviews.

Meanwhile, we could help the process by defining this view
For a user leveraging multiple stages, which views would you need to be accessible and what data should it contain?

**Comment by cpvalente** [comment]
Closing this as there is no actionable follow up for us
