### ISSUE TITLE
Auxiliary Timer Add-Subtract Time

### ISSUE THREAD

**Issue by STEMgrh** [cpvalente/ontime#1356]
I'm working on creating an Ontime workflow with OSC for a tv show I work on, and I would love to see add and subtract commands in the API for the Aux timer!

**Comment by cpvalente** [comment]
Thank you for taking the time to reach out
The Auxiliary timer current allows setting the time but not increments / decrements

Do I understand correctly that you would like to add or remove an amount of time to a running auxiliary timer?
Are there other API requirements you have for the Auxiliary timer?

It would be good to understand your use case, if you are willing to share:
- what is the use case in which you miss the ability to add / remove time?
- what are you using to control ontime?
- how do you use the auxiliary timer?

**Comment by cpvalente** [comment]
Implemented and released as part of 3.9.0
@STEMgrh , can you please double-check that this is what you meant?

See the docs for the implementation API
https://docs.getontime.no/api/protocols/osc/#add--remove-time-to-auxiliary-timer
