### ISSUE TITLE
Export event list bug

### ISSUE THREAD

**Issue by audiostrom** [cpvalente/ontime#136]
I tested this with the compiled version on the website.
When I click export, save the list and then import it, I get the default/demo list of events

**Comment by cpvalente** [comment]
Hi @audiostrom, thank you for the report.
This indeed seems like an oversight when I moved to the public folders. I will push it so it gets fixed for the upcoming version

**Comment by cpvalente** [comment]
Hi @audiostrom , I believe this has bene fixed with the latest v1.2.0
Can you please confirm?

**Comment by cpvalente** [comment]
Looks to me that this has been fixed, closing the issue to keep things tidy
