### ISSUE TITLE
Paste not possible in electron Interface

### ISSUE THREAD

**Issue by RasterboxOff** [cpvalente/ontime#1376]
A client is figuring out Ontime and he can't paste text into the electron interface. That makes creating presets not really viable. 
It works when pasting into an editor that runs in a browser. 

Apple M1
MacOS Sonoma 14.6.1
MacBook Pro 17,1

Ontime 3.9.4

**Comment by cpvalente** [comment]
Thank you,

it turned out this was introduced when we removed the edit menu from the electron app
We will have a fix in the next release
