### ISSUE TITLE
Teleprompter integration

### ISSUE THREAD

**Issue by apcdgworks** [cpvalente/ontime#1385]
Is there any option for a Teleprompter integration or Teleprompter module in ontime, for example https://rundownstudio.app has

**Comment by alex-Arc** [comment]
hey @apcdgworks It seams that some of your message was cut off when you tried to put it all in the title field?

**Comment by apcdgworks** [comment]
I didn't understand...

**Comment by apcdgworks** [comment]
is it possible to give a teleprompter feature with ontime it would be great for media production

**Comment by cpvalente** [comment]
Hi @apcdgworks , thank you for taking the time to make this suggestion

At the moment, it is unlikely that a teleprompter feature will appear in Ontime.
However, if there is an open source project for a teleprompter we could look into facilitating an integration

**Comment by apcdgworks** [comment]
ok... Is there a way to display text in mirror mode

**Comment by cpvalente** [comment]
> ok... Is there a way to display text in mirror mode

depends what text you are trying to display. The views have a "Flip Screen" button which will turn on the mirror mode

**Comment by cpvalente** [comment]
Closing this as there is no possible action points from our side
