### ISSUE TITLE
create colour picker for event colour

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#1397]
In the `<EventEditor>` component, users can select a colour for the event
We currently allow the user a choice of pre-defined colours

The issue request is to create an option with a colour picker for users to be able to select a custom colour
The interface will likely look like the `<ViewParamsEditor>`

See the [entrypoint for the relevant code](https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/rundown/event-editor/composite/EventEditorTitles.tsx#L49)

**Comment by Shobhit-Nagpal** [comment]
hey @cpvalente, would love to take this up :)

**Comment by cpvalente** [comment]
Hi @Shobhit-Nagpal , thank you for offering.

You are welcome to propose a PR, please let me know if you need any more context
As a note, we would need to make sure that the data changes are properly throttled to ensure smooth performance (ie: no update of the colour when the user is dragging the picker around)

And out of interest, do you use Ontime or are just looking to do some react work?

**Comment by Shobhit-Nagpal** [comment]
thanks @cpvalente, started working on it. got the base functionality done.

i do require your opinion on this. would you like the colour picker to show directly as it already is in the `<EventEditor>` component and add a save and reset to default button just below or would you like to open a drawer where users can pick their color from as the issue mentioned having a similar interface like `<ViewParamsEditor>`?

as for your question, i was looking to make some open source contributions, found the repo pretty cool, saw this issue and thought i'll take it up

**Comment by Shobhit-Nagpal** [comment]
thanks for all the inputs, opened a pr for this
