### ISSUE TITLE
Potential issues with M1

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#143]
There is a user report of the app not being able to start in a Mac with M1.

I am unsure if this is an architecture, OS or user setup issue, since no issues were reported by any of the testers.

In general the app is unable to start if it is installed in a location that has no permission to write. This shouldn't be a problem in macOS as far as I can tell unless the user has some specific configuration

It would be great to hear if anyone is having issues and what is the configuration so we can investigate. 

I will leave this issue here until I get some confirmation that the app installs and runs on M1 architecture running the latest macOS

**Comment by je71175** [comment]
We have used successfully on Mac M1s. The only issue encountered was stopping the app required a force quit (logged elsewhere). onTime is still running after Quitting inside the application.

**Comment by cpvalente** [comment]
Thank you again for your help @je71175 
I believe the quitting issues have been resolved with the latest release?

**Comment by je71175** [comment]
Hi - yes this is fixed in the most recent version, only if you shutdown via the "power" button in the app.  If you choose right quit or menu OnTime Quit the original problem remains.  The only way to resolve is the force quit...

**Comment by cpvalente** [comment]
You should be able to use the cmd+q combination to quit the app. Closing the app closes the window as normal MacOS behaviour.
You should also be able to restore the window by using the icon in the task bar. Is that not the case?

**Comment by je71175** [comment]
Yes, cmd +q works, but closing the app window, I can re-open it again.  Right click "show all windows" - I get the message "No Available Windows".  So it seems the server is still running (I can access onTime via the web url) but the app window isn't restored.

**Comment by cpvalente** [comment]
Hey @je71175 , I have been unable to recreate this.

I close the app window using the window buttons. Then I can open it with clicking the ontime logo in the taskbar or by pressing alt + 1.
Can you please clarify? Would you be able to attach a screenshot of your error message?

**Comment by je71175** [comment]
Hi

Option + 1 works to restore the window for me.  Click or double click on the onTime icon didn’t do anything.   Also if I right click, show windows 



Thanks Jason

**Comment by cpvalente** [comment]
The behaviour described seems to be relative to the native window management in OSX.
I found the same behaviour in iTunes and Safari.

When the window is closed, the app can be reopened by pressing `Alt + 1 `or by using the icon in the system tray (next to the clock)

Closing this as it is not an issue
