### ISSUE TITLE
Show the time to the next event

### ISSUE THREAD

**Issue by je71175** [cpvalente/ontime#160]
At times, we need to know how long until a certian event.  We would like onTime to calculate this automatically.  Inital thoughts are perhaps we could hover the mouse over the cue and this information could appear in a "tips" temporary window.

thanks !

**Comment by cpvalente** [comment]
Hey @je71175 , thank you for your continued support.
In the main app page I can see that this could be part of the Info panel. 
I have also planned that the cuesheet could have an optional column to show countdowns to all future events. 
What do you think?

**Comment by je71175** [comment]
Thanks! Anything that means we don't need to calculate time-to-event manually is great 👍

**Comment by cpvalente** [comment]
Hi @je71175 , we have made a few tests and have decided that this doesnt fit well with our roadmap.

The time to next is basically the timer.
The only way to provide value here is to provide an time-to an arbitrary point in time or event

I dont doubt the niceness of the feature, but havent personally found a format which provides an elegant UX or makes it particularly useful.

I will close this for now, if you have strong opinions on the contrary, please feel free to reopen and we can discuss
