### ISSUE TITLE
12 Hour Time

### ISSUE THREAD

**Issue by dillwishlist** [cpvalente/ontime#161]
Is it possible to display the Studio Clock in 12 hour mode rather than 24 hour mode?

**Comment by acdolph** [comment]
And not just the studio clock but anywhere the clock time is displayed along with the timer

**Comment by acdolph** [comment]
The only shortcut I've seen is "a" for AM and "p" for PM - but that would
probably work well in time entry.

FWIW the thing I see as most urgent would be the "Time Now" display on the
views, but I'm less likely to use the schedule display views in my
application.  While I'd love to be able to enter times as AM/PM, it's much
less important.

**Comment by cpvalente** [comment]
Thank you. 
I will make an issue for showing time in 12 hour format.

Entering time in this format will need to wait for the issues related to redesigning the Event component

**Comment by acdolph** [comment]
That’s great, thank you!

**Comment by cpvalente** [comment]
Hey @dillwishlist and @acdolph, I have created a MVP as discussed before, you have a general setting to display timers in the views in 12 or 24 hour format. Would any of you be available to test this feature before release?

The way I have done this before is that you either a) build the project yourself or b) I can send you a link to a build.
For the second scenario please get in touch at mail@getontime.no
