### ISSUE TITLE
Play sound 1 minute before countdown ends

### ISSUE THREAD

**Issue by 9dcontrolroom** [cpvalente/ontime#163]
Is it possible to add a play sound event (JS maybe), one minute before countdown ends? This could be a nice feature, especially if you could change the remaining time for trigger...
Thank you for your time!

**Comment by cpvalente** [comment]
Hey @9dcontrolroom , thank you for your feedback.
Where would this sound play? in app or one of the viewers?

**Comment by 9dcontrolroom** [comment]
Thank you for your reply and your great work!
It would be very useful for the sound to play in one of the viewers so it can notify them that there is [specific] minutes left!
Is it possible?

**Comment by cpvalente** [comment]
Hey @9dcontrolroom, it is absolutely possible. However I feel like most people use viewers in unnatended screens. 
I feel like there is no expectation on sound playback as they are usually in areas like backstage - stage - foyer - set where you dont want unnecessary sounds. 

What is your workflow like or what use case do you have for ontime. Perhaps it would make more sense to have a specific type of screen to support this?

**Comment by 9dcontrolroom** [comment]
Thank you for your reply.
I work in a theater where we have several shows during the day. I need a countdown clock for the outside crew to know the remaining time, but also need an alarm sound for the crew that don't have direct access to the screen. (The sound comes from the same PC the countdown clock is shown)...

**Comment by cpvalente** [comment]
This sounds like it would open the gates for a bunch of needed customisation (whether there is sound, which sound, when, which screens) and I would be more inclined to believe this logic belongs on an external integration controller using one of the APIs

I will leave this open and see if it gets some traction. Meanwhile, if there is something I can do in the API side to facilitate this, please feel free to open a separate issue

**Comment by cpvalente** [comment]
Closing as a not planned feature
