### ISSUE TITLE
"Start time is last end" not working with ALT+E

### ISSUE THREAD

**Issue by Stewart555** [cpvalente/ontime#171]
While using the ALT+E shortcut to create new events, the app does not follow the rule activated by the tick-box "Start time is last end". New events created by ALT+E gets 00:00:00 in all time-fields regardless of previous event end-time.
Clicking the yellow + and "Add event after" works fine and adds the correct times.

**Comment by cpvalente** [comment]
Hey @Stewart555, good catch! Since this components are being redesigned and this is not a major issue I will fix it as part of #55

**Comment by cpvalente** [comment]
Fixed in v2
