### ISSUE TITLE
New API endpoints

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#173]
This one is preparing for #55, also answering some popular requests here

We need a few new endpoints, both in HTTP, websockets and OSC

Possibility to **load a specific event**
- [x] endpoint: `<"loadEvent">` payload event `<eventIndex>`
- [x] endpoint: `<"loadEventById">` payload event `<eventId>`

Possibility to **start a specific event**
- [x] endpoint: `<"startEvent">` payload event `<eventIndex>`
- [x] endpoint: `<"startEventById">` payload event `<eventId>`

Note: event indexes in APIs are 1 based

**Comment by je71175** [comment]
Would it be possible to use this functionality to synchronise 2 separate instances of onTime - i am thinking of a production and backup instance - for example once <eventId> is triggered on the production server, it makes an web or OSC call/message to the backup onTime so start the same <eventID>...

**Comment by cpvalente** [comment]
Hi @je71175 , I am unsure on how this could work and a feature like that should be planned with some care.
I will move this into a separate issue #174
