### ISSUE TITLE
Understudy backup workflows

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#174]
Would it be possible to use this functionality to synchronise 2 separate instances of onTime - i am thinking of a production and backup instance - for example once <eventId> is triggered on the production server, it makes an web or OSC call/message to the backup onTime so start the same <eventID>...

_Originally posted by @je71175 in https://github.com/cpvalente/ontime/issues/173#issuecomment-1173008114_

**Comment by cpvalente** [comment]
The outline would be something like this:

When an **ontime instance starts**, it would need to check for other instances in the network. If they exist it would set itself as an understudy and request updated event list and subscribe to playback status

Involved endpoints
- ontime hello: get replies from other instances of ontime in network
- ontime download: get object with full server state
- ontime sync : get object with playback state
- ontime dbChange: broadcast that the database has changed and understudies should fetch the new data. 

The understudy machine would expect a ping from the master at a certain frequency (ontime sync or smaller footprint??) and decide to **takeover** in case some were missing. It could also perform some small network checks, but this is very dependent in setup and in my experience tend to not work consistently across managed networks.

Then there is also the challenge of what would a takeover look like.
In a a small network with the following devices
- 192.168.0.2 : Ontime master
- 192.168.0.3 : Ontime understudy
- 192.168.0.9 : Ontime viewer

Any viewer in the network is directly subscribed to a host: eg: 192.168.0.2:4001/timer . In the case ontime master would fall we expect that a) understudy machine becomes master b) viewer susbscribes to new master. How does this happen? How does the viewer changes its requests to the new master?

Usually this behaviour is implemented through a gateway which receives both streams (master and understudy) and decides which to pass through. The viewers then subscribe to the gateway.

Lots of food for thought

**Comment by je71175** [comment]
Appologies for the late reply.  The sync as described makes sense, however instead of the networking failover complexity you described (which is absolutely the right way to manage cut-over) perhaps we could live with a more manual change over via a menu system

For example on each webpage, a click to open menu system, which has the addresses of the detected instances of onTime by this server.  A click through link of the alternate servers to use.

<img width="279" alt="Screenshot 2022-07-28 at 8 24 14 PM" src="https://user-images.githubusercontent.com/29515324/181504292-d329663d-5e28-4cbe-9dd6-6a4abbd78c0a.png">

Clicking on the server then opens the same page on the alternate server IP address...

**Comment by alex-Arc** [comment]
a start would perhaps be to save the server state to disk, maybe whenever a new event is selected and some specific period as to not write to disk every millisecond.  This wold also allow us to open a closed session in the same place as we left off. 

This would make it easy to setup a docker swarm with shared storage pool. Then if a container goes down another will spin up and resume from the last store point.

The networking failover could be handled with VRRP and keepalived

**Comment by cpvalente** [comment]
Hey @alex-Arc, this is great input.

I absolutely agree that a resumability process is a great start, and could potentially even be a good enough solution for most users.

The file option could be a simple implementation. We could write a file on main events that can lead a clock source to re-establish the application state. If the application exists cleanly we remove the file to indicate that we do not intend resumability on next start

Is this something you have availability to help with?

**Comment by alex-Arc** [comment]
Hey
I will give it a quick look

**Comment by cpvalente** [comment]
We consider the current solution of resumability sufficient for Ontime.
If there are suggestions from the community at a later stage we can reopen this ticket or create a new one
