### ISSUE TITLE
Feature Request: Teleprompter functionality

### ISSUE THREAD

**Issue by PaddleMonkey** [cpvalente/ontime#182]
Great work. I would like to request to add teleprompter functionality to OnTime.
I believe this feature would be a great addition.

Basic functionality would be as follows:

- Import text from file
- scrolling text (variable scrolling speed, adjustable on the fly with slider and/or buttons)
- variable font size
- variable font weight (normal, bold, italics, underline)
- variable font color (white, yellow, red)
- text justification (left, center, right, full)
- line spacing adjustment
- image flip (horizontal/vertical)
- margin scaling for scrolling text
- start scroll, stop scroll, reverse scroll, jump to top of text

Additional functionality could be considered:

- section markers (can jump to top, or desired sections of large amount of text)
- eye line indicator (an arrow or a rectangular overlay indicating the location of the lens behind the glass)

Please refer to this document as reference to replicate basic features.
[https://pavonine.co/teleprompter/manual.pdf](https://pavonine.co/teleprompter/manual.pdf)
[https://pavonine.co/teleprompter/](https://pavonine.co/teleprompter/)

**Comment by cpvalente** [comment]
Hey @PaddleMonkey, thank you for getting involved and for a very well specified issue.

I will leave this issue open to see if it gathers some support. At best this would follow current functionalities in the roadmap related to time keeping

**Comment by Keksstar** [comment]
There are so many teleprompter Apps out there...
Ontime is an time keeping app. Don´t mix things up...
