### ISSUE TITLE
Inbound OSC from other devices on network

### ISSUE THREAD

**Issue by JackyBOfficial** [cpvalente/ontime#183]
Hi!

I have been playing around with incoming OSC commands to ontime for a bit now, hoping to make a touchOSC controller on my tablet to remotely control the timer. I was thoroughly disappointed to find out that the 8888 port is stuck listening to only the 127.0.0.1 address on my pc, and is not looking for incoming data from all addresses on the network. 

I ran this by a few other tech folks to make sure I'm not missing something, but we all came to the same conclusion that ontime cannot receive data on port 8888 from anything that is not the localhost. We checked this by running netstat -a in command prompt and verifying that the 8888 port was only listening on 127.0.0.1,  not 0.0.0.0 (aka all addresses). Wondering if there is a way to change this now that we missed, or if there is a reason this has not already been implemented. If not, I would definitely love for this to be added.

Thanks! Love the app. great work so far!

**Comment by cpvalente** [comment]
Hey! thank you for reaching out.
Just had a quick check and the app does indeed listen on 0.0.0.0 `oscServer = new Server(config.port, '0.0.0.0');`

Perhaps there is something else? I believe this feature has been pretty battle tested and I would be surprised to see such a basic oversight (although possible)

I would be keen on sorting this out, but would need some more information:
What version are you using and what platform? 
What network interfaces does the app report in the info panel? is the OSC client using one of those?
Is there anything logged in the info panel?

**Comment by JackyBOfficial** [comment]
Thanks for the reply. I was also surprised when I tried to work this out, so I half posted this as a support thread to see if there was something wrong on my end 😂

I am using the lastest version, on Windows 10.

Network interfaces reported on PC#1 we're localhost and Ethernet, OSC Client was on same Ethernet network just connected over wifi (I am able to send OSC from the tablet to another program, just not Ontime)
Network interfaces on PC#2 we're localhost and Wifi, same network as tablet, and same situation as above.

When I send OSC on the localhost network (aka from Companion OSC module on same PC as ontime), yes there is commands logged. When I attempt to send the same OSC commands from outside the localhost network using the tablet, nothing is logged. 

I checked all my windows firewall settings, and will do so again when I get the chance to work on this again, so I don't think that is an issue. I haven't tried other ports yet, but I suspect this issue to not be related to that. I also had that on my troubleshooting todo list nonetheless.

**Comment by je71175** [comment]
Hi
Some thoughts :
Do you have companion open on the same pc as OnTime while using TouchOSC on the tablet? It is probably hogging the port if you do
App needs a restart if you change osc port
Sure it’s not windows defender blocking the traffic? If you have a Norton or antivirus with network try disable it for a bit. It does sound like a networking type issue
Cheers Jason

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cpvalente** [comment]
Thank you @je71175 .

@JackyBOfficial, I am unable to recreate the behaviour here. Have you had any luck troubleshooting this?
As @je71175 mentioned, I would assume that the port is probably taken by another process

Is the device sending OSC able to reach ontime server at all?

**Comment by JackyBOfficial** [comment]
@je71175 great point, that could easily be the issue... I'll give that a whirl when I can.

@cpvalente I'm actually in the process of moving house so I won't be able to try this again until tonight or tomorrow at the earliest. I'll let you know my findings when I do. Thanks so much for the help all.

**Comment by JackyBOfficial** [comment]
@je71175 You had it, closed companion and restarted ontime... works like a charm. 

I feel like an idiot! Haha! 

Thanks for the help all

**Comment by cpvalente** [comment]
Happens to the best, good luck with the moving and do get in touch if you have any feedback later on
