### ISSUE TITLE
Feature Request: About Button

### ISSUE THREAD

**Issue by emmdubb** [cpvalente/ontime#184]
It would be nice to have an About Button that gives us installed version, update checker, link to website, etc.   I had to re-run the installer to figure out what version I was running.

**Comment by cpvalente** [comment]
Hey! This is another great UX improvement and I will try to fit it in.
Currently you can see the ontime version in your OS and in-app in the settings menu

**Comment by cpvalente** [comment]
Released as part of v2 beta-5
