### ISSUE TITLE
Feature Request: New Show Wizard

### ISSUE THREAD

**Issue by emmdubb** [cpvalente/ontime#185]
It would be nice to have a wizard to setup a new show.   Just a basic form that lets us set things like the Show Name, dates running, venue, rooms used, etc.

**Comment by cpvalente** [comment]
Hi @emmdubb, thank you for reaching out with a feature request.
In the current case of ontime there isnt so much to setup just yet, (no dates running, or venue, or rooms used) but a good workflow either way

This sounds like a great idea and I will try to fit it in the roadmap

**Comment by cpvalente** [comment]
Hi @emmdubb , it took a while, but this is included in the new beta-5. Could we close this issue?
