### ISSUE TITLE
Request for timer status functionality

### ISSUE THREAD

**Issue by je71175** [cpvalente/ontime#190]
Would it be possible to incorporate the status of the timer into onTime ?  For example the status as "Stopped" "Paused" "Running" are available to other systems. (API, OSC, Companion)

I am thinking specifically for OSC status messages and API status inquiry / web sockets, and also since you have developed a companion module -I am hoping that the companion buttons could also be coded to a colour which coresponds ot the timer status (as I have seen with some other modules)

thanks !

**Comment by cpvalente** [comment]
Hi @je71175 , the playback status is already available to the APIs but is not streamed. 
Do you have a specific workflow / integration in mind?

Feedback is absolutely a must for companion module. It would be great to have some input, would you mind creating an issue in [the module repo](https://github.com/bitfocus/companion-module-getontime-ontime)?

**Comment by je71175** [comment]
Aside from the onTime UI, we primarily use OSC (via OSC Pilot app) for controlling apps, and in building the onTime OSC controls, it would be good to have a visual indication of what onTime is doing in OSC Pilot.
Have also begun looking into Central Control platform (https://centralcontrol.io/) in addition to Companion.  It seems to have a good following in video land, and supports OSC and API.    (Have heard some horror stories of Companion on live shows, particularly for complex mappings, but touch wood no personal issues).
thanks

**Comment by cpvalente** [comment]
This sounds like a good opportunity to build up the OSC integration a bit more. How would you imagine this? Would there be a poll endpoint in OSC?
If you could help me build a schema I am happy to prioritise this.

Meanwhile seems like Central Control already have a rundown timer. What is the use case for integrating ontime with this? 

Again, I am actively rebuilding the APIs so it is perfect timing to look into this

**Comment by je71175** [comment]
Hi - i was primarily using central control because it has support for control units and general hardware/ devices (eg HyperDeck).  Basically an alternative to companion and a stream deck, or even alongside companion for some redundancy.
I haven't looked into their timers functionality much, but on the surface OnTime is much more comprehensive and workflow friendly for our needs.
So the ask was for other apps in our workflow- companion, Central Control, etc, to have some feedback / sync as to what was happening with OnTime.  I was thinking at a minimum, each time OnTime changes it status it sends an OSC message,  OSC polling of OnTime would be excellent also.

**Comment by cpvalente** [comment]
Thank you for the clarification. I see a lot of movement towards OSC APIs so it would be definitely a good idea to support this.

It would be great to have some help identifying the structure here. 
- What would the osc endpoint be? a single /ontime/poll? What data does it return?
- Should ontime send data at events (like it does now every second, [see docs](https://cpvalente.gitbook.io/ontime/control-and-feedback/osc))
- What does an MVP look like, ie: what is the minimal functionality to be able to integrate with Central Control and enable your workflow

**Comment by je71175** [comment]
For the Query (poll) functionality, implement a response to OSC message "/ontime/status" the current status keywords sent with /ontime (play, pause, stop, finished) is perfect.  thank you

**Comment by cpvalente** [comment]
Hi @je71175, would you object to a message called `/ontime/get-playback`?
I believe this establishes a better pattern for status getters

**Comment by je71175** [comment]
Perfect!  Thank you

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
