### ISSUE TITLE
Webserver port change

### ISSUE THREAD

**Issue by griffon56** [cpvalente/ontime#196]
I would need to change the port of thee web server from 4001 to 80. Running on windows. How should I proceed ?

**Comment by cpvalente** [comment]
Hi @griffon56, I am surprised it took this long for someone to ask.
Port 80 is a protected port. So this is something you will need to do yourself.

You should be looking at port forwarding and proxies. Should be semi straightforward

Alternatively you can look into using the docker image, the given docker setup contains an example on how to serve the app in port 80.

**Comment by griffon56** [comment]
Many thanks for thee feedback - the following command lines did the trick on a windows 10 machine:

netsh interface portproxy add v4tov4 listenaddress=127.0.0.1 listenport=80 connectaddress=127.0.0.1 connectport=4001
netsh interface portproxy add v4tov4 listenaddress=<local_IP> listenport=80 connectaddress=127.0.0.1 connectport=4001

**Comment by cpvalente** [comment]
Perfect, glad you got it sorted out. 
If it is OK with you I will add your findinds to a the documentation to help out users looking to achieve something similar in future
