### ISSUE TITLE
Bug: After changing event order, user fields do not follow

### ISSUE THREAD

**Issue by raffaeletani** [cpvalente/ontime#203]
When you change the order of events in the app, the cuesheet webpage gets updated as expected.
However, the information in the user fields stay at their previous index. their position updates only on page reload.

Example:

```
 Event 1: 
     User0: 1
 Event 2:
     User0: 2
```

Now move the Event 2 to first place.

Expected output:

```
Event 2: 
    User0: 2
Event 1:
    User0: 1
```

Effective output:

```
Event 2: 
    User0: 1
Event 1:
    User0: 2
```

**Comment by cpvalente** [comment]
Hi @raffaeletani, thank you for getting involved and the bug report.
I will look into it and make sure to address it in a near release
