### ISSUE TITLE
Urgent: Background Color / Text not visible

### ISSUE THREAD

**Issue by w00k1ee** [cpvalente/ontime#213]
Dear Ontime Devs and Community,

I started using Ontime for an upcoming stream (starting friday) everything works great so far but I have an issue, I'm not able to resolve: 

I have some events - i Colorcoded them - that worked just fine. 

Now I have some information in some user fields. 

On some Fields I can see the Information and on others the text-color is inverted and not visible. So i basically have to switch between Dark and Light mode - to see all infos..

I tried with a CSS file, only talking to the class: 

:root {

  --color: black;

.Table_tableWrapper__d {

  background-color: #aab097;
}
}
.chakra-textarea css-2klfw7 {
  background-color: #aab097;
}

But none of that worked, and I'm not sure if anything is happening. CSS override is enabled. 

Attached I have a Picture, where you maybe see my issue.

<img width="699" alt="Screenshot 2022-10-12 at 13 33 00" src="https://user-images.githubusercontent.com/115632759/195333389-297ffba0-4197-44f5-8112-5359da9face6.png">

Best regards,
Jeremy
--

**Comment by cpvalente** [comment]
Hi @w00k1ee, is this behavior still true if you disable CSS overrides? 
Would you mind saving your file and sending it over to mail@getontime.no and I will take a look

While this issue gets fixed you could use a previous version of the app like https://github.com/cpvalente/ontime/releases/tag/v1.5.0

**Comment by w00k1ee** [comment]
Hi, 
Just checked, issue is still there when the override is turned of. 

I'll send the .csv and .json to you via mail now. 

Thank you so much!

**Comment by w00k1ee** [comment]
> Hi @w00k1ee, is this behavior still true if you disable CSS overrides? Would you mind saving your file and sending it over to [mail@getontime.no](mailto:mail@getontime.no) and I will take a look
> 
> While this issue gets fixed you could use a previous version of the app like https://github.com/cpvalente/ontime/releases/tag/v1.5.0

Hi, I sent you the email - maybe I'm in spam - lots of hosts don't like .film at the end :)

**Comment by cpvalente** [comment]
The good news is that this is a simple fix.
It was probably related to one of the recent UI updates and escaped tests.

I will push a fix later today
