### ISSUE TITLE
Release 1.8.2

### ISSUE THREAD

**Issue by je71175** [cpvalente/ontime#216]
Good morning.  Noticed 2 issues with the current release
1/ Import excel, the Event data doesnt seem to import correctly.  Existing event data isn;t overwritten
2/ Lower Thirds web view has an error
<img width="478" alt="Screenshot 2022-10-13 at 10 01 56 AM" src="https://user-images.githubusercontent.com/29515324/195482026-c700ee9a-a12b-48f1-b47a-c0502407dd5a.png">
thanks !

**Comment by cpvalente** [comment]
Thank you, I have removed the release and will look into it

**Comment by cpvalente** [comment]
Hi @je71175 , could you please describe your first point in more detail?
The are no changes in even upload but in the build system. Is it the events themselves which are not importing correctly or the event data? Did you notice the new checkbox which allows to import only events ignoring all other settings?

**Comment by je71175** [comment]
I tried both setting and didn’t notice the difference. All of onTime data was unchanged (from what was in my onTime show) after importing an Excel show.  
Thanks Jason
