### ISSUE TITLE
Downloaded file has no extension

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#22]
It seems that if "File name extensions" option in windows explorer is disabled. The downloaded file has no extension .json, and is then not recognised as an uploadable file

Tested with v.0.2.0

**Comment by xztraz** [comment]
![image](https://user-images.githubusercontent.com/25690871/146646981-4a7184cc-0235-41bd-bfcb-09c32c78e9a2.png)
seem to work (rc5 unofficial)

**Comment by cpvalente** [comment]
Clarifying the steps to reproduce

- ensure show file extensions is disabled 
- download file in ontime
- delete all events
- upload file in ontime 

Can you confirm that this works for you?

**Comment by xztraz** [comment]
point 1 in windows you mean? i have that enabled (don't want to muck around in windows too much)
can download a file. it gets .json.
deleted and uploaded and stuff imported again.

**Comment by cpvalente** [comment]
Yes, the first point you need to do in windows settings. it is just a visualization setting and pretty harmless. But I understand that you want to be cautious

**Comment by cpvalente** [comment]
This issue was caught by one of the testers and never really reported by any users.
This seems to be due to windows config and there is a good workaround. 
will close this issue for now until it becomes problematic for users
