### ISSUE TITLE
Error in CasparCG

### ISSUE THREAD

**Issue by sakuv** [cpvalente/ontime#221]
Hi! 
I'm getting "TypeError: Object.fromEntries is not a function" and "Uncaught TypeError: Object.fromEntries is not a function" while trying to use ontime with CasparCG(2.3.3). 
Any clue, is Caspar using too old Chromium, or could this be fixable in ontime?

**Comment by cpvalente** [comment]
Hi @sakuv , thank you for reaching out.
I will definitely will have a look and try and find a solution. Can you provide some more context?

How is it that you are using ontime with casparCG?
Does this happen in any view or a specific one?

**Comment by sakuv** [comment]
Caspar errors:
[2022-10-17 16:18:07.862] [error]   html[http://10.12.104.161:4001/studio] 1280 720 50.000000 Log: TypeError: Object.fromEntries is not a function
[2022-10-17 16:18:07.862] [error]   html[http://10.12.104.161:4001/studio] 1280 720 50.000000 Log: Uncaught TypeError: Object.fromEntries is not a function

Tested on two PCs, Windows 10. 
Caspar server v2.3.3-lts-stable.

Either ADD or CG -commands in Caspar do not work.

**Comment by cpvalente** [comment]
Unfortunately this seems to be down from a third party library
Can you please clarify on whether all the viewers have this issue? 

I could try and make a version that shakes off the dependency, if you would like to help in testing do get in touch at mail@getontime.no

**Comment by sakuv** [comment]
I see.
I tested following views, they seem to have problem to render in Caspar:
-default
-clock
-minimal
-backstage
-public
-lower
-pip
-studio
-countdown

They're all views i know about.

I also tested of course my Caspar setup, which worked correctly for example with SPX-GC (which renders HTML page overlays)

**Comment by cpvalente** [comment]
Closing this for now. We have a branch ready which aims to fix this and can reopen if there are any testers
https://github.com/cpvalente/ontime/tree/compatibility
