### ISSUE TITLE
OSC Previous not responding

### ISSUE THREAD

**Issue by pbl4845** [cpvalente/ontime#226]
Hi, 

I am running Ontime MacOs Versión 1.9.2 (1.9.2)
OSC Previous command doesn't seems to work, all the others I tested work properly.
/ontime/Previous

I have tried Uppercase and lowercase with no luck

**Comment by cpvalente** [comment]
Hi @pbl4845 , thank you for reaching out
According to the docs it should be `/ontime/prev`
https://cpvalente.gitbook.io/ontime/control-and-feedback/osc

In retrospect this is bad naming convention and I should, at least, allow for both prev and previous spelling.
Would you mind checking that `/ontime/prev `works for you? I will reuse this ticket for API improvement

**Comment by pbl4845** [comment]
All Fine! Proper command Works Flawlessly! 

Sorry! My Fault! 

 Don´t know why I got the impression of the command I used while looking on the Docs.

**Comment by cpvalente** [comment]
No worries, happy to help.
Please feel free to open issues if you feel needed
