### ISSUE TITLE
Request MTC Output

### ISSUE THREAD

**Issue by pbl4845** [cpvalente/ontime#227]
I´m Thinking on a nice feature.

Having the possibility to add an MidiTimeCode output(or even input), would help integrate it better on more complex automation systems.

....Waiting for the promising upcoming of OSC custom commands! 🤩

Well Done!! This is a Super Nice Tool!

**Comment by cpvalente** [comment]
Hi @pbl4845 , I feared the day someone would mention MTC, and here it is.
Without looking too much into it, I see that companion supports it. Ontime has the exact same stack so it should be possible. I wonder however if it would be possible to have a single solution for all platforms ontime supports....

This is outside my ability to test, would you be able to help here?

And can you clarify about OSC custom commands? API improvements are something I really enjoy, it would be great to have some feedback on how it could be better

**Comment by je71175** [comment]
I'll vote for MTC in and out also :)  And am happy to help test

**Comment by cpvalente** [comment]
Hi @pbl4845 ,

We have taken a look at this feature and considered it as part of v3
The current decision is that this does not match with the rest of the roadmap and we will not develop this feature further

Thank you again for taking the time to make the feature request. I hope this is not discouraging you from future contributions
