### ISSUE TITLE
Viewers dont render in iOS devices

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#23]
Page is blank in iOS devices.

Tested with version 0.2.0 on iPad and iPhone (safari and chrome)

**Comment by cpvalente** [comment]
Tracked this down to a dependency that handles keyboard shortcuts.
f3320ef adds naive shortcut handling for now and see how it follows up

**Comment by dfaligertwood** [comment]
This seems to have resurfaced (although probably not the same mechanism) on an iOS 12 device with ontime 4.7.0. Didn't have time to properly chase it down and the device wasn't mine, but going to try and borrow one to take a better look at it sometime soon.
