### ISSUE TITLE
Show video (PIP)

### ISSUE THREAD

**Issue by Richie-63** [cpvalente/ontime#232]
I run quicktime on my Mac-Laptop. Ontime is open and also running. - How can I show this live-video on the pip-screen?

**Comment by Richie-63** [comment]
ok, but how will the user see the composition on 4001/pip? How should I go on (step by step)?

**Comment by cpvalente** [comment]
Hi,
The main idea here is that you would use the ontime PiP screen as a source in your video workflow
.
The example in the screenshot was made in d3. I composed a video input on top of  the ontime screen (using the Browser Module). A similar workflow would be possible in different pieces of software / hardware

If you are not using any external media server / scaler, you would need some intermediary software like OBS Studio to handle the composite in realtime
