### ISSUE TITLE
Editing time values

### ISSUE THREAD

**Issue by je71175** [cpvalente/ontime#235]
Could I request that when editing start and finish times in the editor that we edit the "real" values not calculated values.

For example
10:00:00  to 10:10:00 is my event
If i have a delay of 20 mins preceeding this, the times are displayed as
10:20:00 to 10:30:00
If i go to edit the start / finish times i am editing "10:20:00" not my origional time of "10:00:00"

thanks

**Comment by cpvalente** [comment]
Hi @je71175, this makes sense.
Unfortunately we will need to wait for v2 on this

**Comment by cpvalente** [comment]
Hi @je71175 

Could you comment on how is this related to v2?

**Comment by cpvalente** [comment]
Closing this as we cannot verify that the issue maintains in v2
