### ISSUE TITLE
Suggested update to Styling Info on GitBook

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#241]
Here is a suggested update to the docs, with regard to CSS Styling:

**Before**

```
With ontime v.1.6.0 you are able to upload a CSS file which overrides the app defined styles.

For app users: the CSS file should override the existing in the installation folder /external/styles/override.css

This feature can be toggled on / off in the Viewer Settings in the Settings Modal. 
```

**After**

```
With ontime v.1.6.0 or later, you can change the CSS that can override the app-defined styles.

    For PC/Linux users:
    The CSS file is located in a subdirectory under the installation-folder: ./external/styles/override.css

    For Mac users:
    The CSS file is located within the Ontime app bundle.
    1. Right-click the ontime.app file in the /Applications folder and choose Show Package Contents.
    2. Navigate to ./Contents/Resources/extraResources/src/external/styles/override.css

This feature can be toggled on/off at Settings -> Viewers. 
```

I see a number of updates I'd like to suggest. Let me know if this is editable on my part, or if you'd like me to send suggestions here or other means.

Thanks!

**Comment by cpvalente** [comment]
Hi, let me look at how I can make it easier for users to support documentation.
Meanwhile thank you for this, very helpful

It would be great to hear the rest of your suggestions, you are welcome to add issues here as you feel relevant. However, it is important noting that a large part of the documentation will become outdated with v2. Perhaps you would be interested in testing the new version?

**Comment by tcconway** [comment]
Happy to help with whatever you need! This app is quickly becoming super valuable to me ;-) I hope to give back however I can. PS: I'm super good at breaking things!

**Comment by cpvalente** [comment]
Hi @tcconway, I have pushed the suggested changes to gitbook.
Thank you again for this. Documentation help is absolutely fantastic

With ontime v2 around the corner I wouldnt want to waste your time on writting documentation for changing features, but if you would be able to make a bullet point list of suggested changes I could work with you on getting this ready.

As of directly editing documentation: I believe all you need is a gitbook account. To make things simpler I should probably publish the documents as a repository. For now we can keep it here in github
