### ISSUE TITLE
Mac Keyboard command to open Settings

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#242]
For mac users, can you make Command-, keystroke open Settings? This is the default keystroke to open preferences/settings on most other Mac apps.

**Comment by cpvalente** [comment]
This is already programmed into ontime and it sounds like there is something else wrong alltogether that never got reported.
I will flag this as a bug and take some time to investigate

Meanwhile, can you provide a few more details on your setup?
Which MacOS version? browser? ontime version?

**Comment by tcconway** [comment]
Thanks!
Keystrokes act weird when Ontime is running. For example, when I hit CMD-Q in any other app, Ontime throws a modal "Server Shutdown"....with the Cancel and Shutdown buttons...even though, say Brave Browser is forefront.

System Details:
System: MacOS 13.0 (22A380), running on a MacBook Pro M1 Max (latest)
Browser: Brave v1.45.118 (latest)
Ontime: Version 1.9.2 (1.9.2)

Let me know if you need more!

**Comment by cpvalente** [comment]
This is perfect, one more clarification: are you using the editor in-app or in the browser?

**Comment by tcconway** [comment]
I've been using the app, not the browser. Just now found that you can use the browser as an editor!

Just tested in Safari Version 16.1 (18614.2.9.1.12) and Brave (which is really just Chrome), and Option-E/D/B doesn't work here either.

Think it might have something to do with the way you're grabbing keystrokes? For some reason Comand-Q is still trying to quit Ontime when it's in the background ;-)

**Comment by cpvalente** [comment]
This is absolutely right and looks like I misunderstood how shortcuts work in macOS.

I wonder if you have a focus issue? Are you able to move the pink cursor with Alt+<Arrow Up> and Alt+<Arrow Down>?

**Comment by tcconway** [comment]
Tab/Shift-Tab move the focus around in the browser and App. Alt+/- (Option +/-) do not move the focus.
