### ISSUE TITLE
Help menu point to Online Docs

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#243]
Can you add a **Ontime Help** menu item under **Help**, that opens the default web browser to https://cpvalente.gitbook.io/ontime/

Apologies for the flood of issue posting ;-) Hope these help though!

**Comment by cpvalente** [comment]
No need to apologise, this is indeed very helpful.

I am not entirely clear on the feature. Currently on the left side menu, the question mark icon will open the help documentation linked in a browser window, is this not the case?

**Comment by tcconway** [comment]
Ah, I see the question mark now. I was referring to the top menu bar. Help menu up top, shows "(empty)".

**Comment by cpvalente** [comment]
Ah I see, you probably refer to the app bar in MacOS. It makes sense to me, thank you
I work mostly in Ubuntu and Windows, so help with MacOS is appreciated.

**Comment by tcconway** [comment]
Happy to help with any testing, both on Mac, networking/scripting, and of course vMix!
