### ISSUE TITLE
Have the override.css file outside of the Mac App bundle

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#244]
Probably more a Mac issue than PC/Linus users.

Can we choose a specific CSS Override .css file instead of using the one embedded within the Mac App bundle?

I envision a [browse] button in the Settings>Viewers area that allows us to choose a .css file anywhere on our HDD.

This would be beneficial especially when we update the .app so we don't lose our override css settings.

**Comment by cpvalente** [comment]
Hi.
The feature seems slightly immature to me and I have been avoiding documenting it.

It would be great to know how is this working for you, perhaps you have time to send me some thoughts to mail@getontime.no?

Upload of custom CSS files is definitely something that will be on the table once we know a bit more about this feature

**Comment by cpvalente** [comment]
Hi, this has been resolved as part of v2. Please also note the updated documentation with the path to the override file
https://cpvalente.gitbook.io/ontime/features/custom-styling
