### ISSUE TITLE
Companion: Get variables from Ontime

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#248]
Would like to request that the Companion module be able to get variables from Ontime. Things like:
- OnAir/OffAir status
- Current running time
- Current Title and Subtitle
- Current Cue Start, End, Duration

This would be super helpful as we build out our Companion buttons!
Thanks!

**Comment by cpvalente** [comment]
Hi @tcconway , thank you for this (and the other) help.
Would you mind moving this one to the ontime module? 
https://github.com/bitfocus/companion-module-getontime-ontime

**Comment by tcconway** [comment]
Thanks. Done.

**Comment by cpvalente** [comment]
Hi @tcconway , just following up here since there is ongoing development in the ontime module and I did not see your issue there. Perhaps it got lost somewhere?

**Comment by tcconway** [comment]
Odd. I swore I posted over there. Either way, here it is again!
https://github.com/bitfocus/companion-module-getontime-ontime/issues/7
