### ISSUE TITLE
On Launch, asks 

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#249]
**System:**
- MacOS Ventura - 13.0 (22A380)
- Ontime - 1.9.2 (1.9.2)

**Issue:**
This is more a slight inconvenience bug more than anything else. But if I've learned anything about bugs like this, it sometimes causes issues way down the line...so here ya go:

On **each and every app launch**, MacOS throws this message:
> Do you want the application "ontime.app" to accept incoming network connections?

Having the Firewall set to "Allow incoming connections" has no effect. I think this is just cosmetic, as everything seems to work perfectly -- other computers on the network can easily access Ontime like normal.

Here's a visual: https://ibb.co/m6sTPGF

**Comment by cpvalente** [comment]
Hi @tcconway, this is (unfortunately?) not a bug.

Ontime is not signed, so macOS has no way of verifying the code integrity of the app and will keep asking you to make this sorts of decisions.

The signing process is relatively painless but incurs a yearly cost. There is no plan from my side to purchase the necessary certificates
