### ISSUE TITLE
Select next event issue

### ISSUE THREAD

**Issue by kellhogs** [cpvalente/ontime#255]
When using blocks in the event list selecting the next event it will also select blocks and respond with a timer of 00:00:00

would be great if blocks would be automatically skipped when selecting the next event.

**Comment by kellhogs** [comment]
@cpvalente both

**Comment by cpvalente** [comment]
Thats right, sorry for that.
I have been working on v2 for so long that I forgot this was an issue.

Good new: it is fixed
Less good news: it will be released as part of v2

I will still mark it as an improvement and leave the issue open so that we can check when v2 is in open beta

**Comment by cpvalente** [comment]
Fixed in v2
