### ISSUE TITLE
Paste doesnt work

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#256]
OS: Mac 13.0
Ver: 1.9.6

Looks like paste doesn't work (Copy does) when copying longer titles and other items.

For example:
1. Open your favorite plain text editor. I used BBEdit.
2. type out: 1234567890123456789012345678901234567890E
3. copy then paste into any of the fields. Note that the Notes field does work.
4. Delete the "e" from step 2 and notice that you can paste that in.

Looks like there is a 30char limit to paste in.

Expected use: If the text pasted in is longer than the field allows, it should truncate the pasted text.

**Comment by cpvalente** [comment]
Hi @tcconway , thank you for your continued help.

With v2 in the works, I am unable to prioritise any work in UI components unless is an active bug or is stopping some workflow.
Would you consider this to be the case here?

We also have a pending request to lift all restrictions on input size which would resolve this as a side effect.

Let me know what you think

**Comment by tcconway** [comment]
It is stopping workflow, but I have a workaround personally, now that I know it exists. I just truncate the text knowing the limitation. No biggie for me.

I assume most others might not run into this, so I'd consider this a lower priority for most/all others.

Thanks again!

**Comment by cpvalente** [comment]
Fixed in v2
