### ISSUE TITLE
MacOS Version

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#26]
Make release for MacOS
- [x] setup scripts
- [x] setup CI

### On Mac OS version
Mac OS version has been ready for a while now, just stalled for lack of testers. If someone would like to focus on Mac OS I am happy to push a alpha build, drop me a message

**Comment by dillwishlist** [comment]
@cpvalente I would be happy to do some testing on the Mac version.

**Comment by cpvalente** [comment]
Hey @dillwishlist 
I have invited you to a separate repo where I am working on the mac release. You can download the mac version by navigating to release and downloading the macos artifact.

Let me know how it goes, feel free to reach out on email mail@carlosvalente.com

**Comment by dillwishlist** [comment]
Perfect, thanks!
