### ISSUE TITLE
Possible to change websocket/viewerport to other than 4001

### ISSUE THREAD

**Issue by ehfyn** [cpvalente/ontime#262]
Ontime collides with another software that i use alot - Heretorecord.com's H2R Graphics.
Is there a way to change the port on Ontime? The field is greyed out in settings.

**Comment by cpvalente** [comment]
Hi,

The collision is unfortunate and I will see that it will be easy to change it in future.

As of now, the only way to do it is by running the app in a docker container, you will be able to expose the sever in whichever port you would like. 

This is probably not the answer you were hoping for, but hope it helps either way

**Comment by cpvalente** [comment]
Closing in favour of #358
