### ISSUE TITLE
Full Screen button doesn't do just that on iOS

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#269]
Expected result:
On an iOS device (Safari in this case), tapping the fullscreen button should make the web page go full screen.

Actual result:
The full screen button highlights; nothing else

Steps to repeat:
1. On an iOS device (I tried an iPad Pro and an iPhone), open the Ontime web page
2. Tap the Ontime icon
3. Tap the Full screen button

iOS ver: 16.1 and 15.7

**Comment by tcconway** [comment]
Hi @cpvalente. Sorry for the confusion here.
This is for any iOS device (iPhone, iPad) and using Safari...When you try to make the timer go full screen, it won't do it.

Image: https://ibb.co/ZYywSm4

**Comment by cpvalente** [comment]
Hi @tcconway.

This is an issue from iPhone side. Apple chooses not to support fullscreen API in iOS for iphone. However it should work for iPad?
I dont have an iPad to test, would you mind doublechecking for me?

**Comment by tcconway** [comment]
Thanks for the reply.

I can confirm the button does not work on Safari iPadOS nor iPhone like you mentioned.

One workaround I guess is to turn the device sideways. (sometimes having to swipe up just a tad). The downside on iPadOS is you still see the top bar with the Time-IP-Connection-Clock thing...but beggars can't be choosers.

One thought is to possibly remove the Full Screen button JUST when displayed on iOS/iPadOS--or better yet have it show a popup explaining that "To view Full Screen, tilt your device horizontally." It initially feels coding this would be a waste of time, but I feel it is worth it - Everyone that I introduced to OnTime uses iPad Pros sitting on the speaker podium for their speaker timer.

Thanks again!

**Comment by cpvalente** [comment]
hmm, it seems that apple is not interested in supporting fullscreen in iPhone. BUT we should be able to make this work in iPadOS. Let me send you some test code
