### ISSUE TITLE
Limiting broadcast schedule

### ISSUE THREAD

**Issue by smithart** [cpvalente/ontime#270]
Our radio show typically broadcasts for one hour each week. I've set up the Event List and I am using Roll Mode to automate the timer display.

The Event List in ontime is showing the hourly events for the entire 24-hour day, and I can't figure out any way to set the other hours to off-air or to filter the display to only show the time period I'm interested in.

Is this possible, or would this be an enhancement request?

**Comment by cpvalente** [comment]
Hi, there is currently no filter functionality in any of the views.

I am not entirely sure I understand the feature you describe, but it sounds interesting. Would you mind fleshing out a description with some more detail and a use case (eg your radio show)?

**Comment by smithart** [comment]
We broadcast a live call-in talk radio program on over 200 stations every Saturday night for one hour. We have our own studio and frankly don't care about the programming that occurs the rest of the week.

When I set up the clock in ontime, it populates and shows events for every hour of every day. So, looking at the event list on Thursday, I have to scroll through dozens of events that don't apply to get to the set for the specific hour we are broadcasting.

I would prefer that when I open ontime, it would show the next *actual* event, and that all of the countdown timers would reference that event. For example, if I'm in the studio 3 hours before showtime, I would like to be able to start the Roll mode and have the clock countdown to the "Start show" event.

I can think of a few potential ways to implement this:
* One option would be to add a setting to select Off Air hours. Even if the setting was the same for every day, it would  at least solve the "day-of" problem. But it would be even better to have full calendar control.
* Another option would be to have something similar to the Delay/Block functionality, where you could block off a period of Off Air time.
* The best option would be to be able to define multiple clocks and be able to assign clocks to specific days/hours. Then we could create an Off Air Clock that could be assigned to most of the week.

And of course, in each of these cases the countdowns, timers, etc., should basically treat the Off Air times as invisible.

I hope that helps. Let me know if you need more information. I suspect we're not the only syndicated show that might be able to benefit from this functionality.

**Comment by cpvalente** [comment]
Hi, thank you for the information.
Currently ontime does not have a concept of days, all times exist in relationship to each other. Some of the very first versions of ontime did include full datetime data, but it was decided back then, that this involved additional overhead without too much gain for a rundown / timer application. 

With the release of v2. there will be possibility to skip an event without deleting it. We also have plans to implement event groups which I believe could help with your situation.

Having said that, all of these seem, to me, to be convoluted work-arounds to fit your needs. I wonder if there is some very fundamental functionality in ontime that is lacking, or if the architecture around the implementation of time is badly thought through. Would you mind sending a sample of your showfile to mail@getontime.no? I will follow up once I have a better understanding of the use case

**Comment by smithart** [comment]
Okay, after some more experimentation, I came up with a reasonable solution using the current functionality.

By creating two events, one each for the Off-Air time before and after the broadcast, I was able to achieve most of what I requested:

```
Time Start  |  Time End   | Event Title
12:00:00 AM |  7:00:00 PM | Off Air
 7:00:00 PM |  7:05:00 PM | Station   Identification
 7:05:00 PM |  7:10:00 PM | Start/Segment 1
 7:10:00 PM |  7:11:00 PM | Break
 7:11:00 PM |  7:15:00 PM | Segment 2
 7:15:00 PM |  7:17:00 PM | Break
 7:17:00 PM |  7:30:00 PM | Segment 3
 7:30:00 PM |  7:32:00 PM | Break
 7:32:00 PM |  7:45:00 PM | Segment 4
 7:45:00 PM |  7:47:00 PM | Break
 7:47:00 PM |  7:59:24 PM | Segment 5/End
 8:00:00 PM | 12:00:00 AM | Off Air
```

Although full calender control would be a great enhancement, I think the current implementation will work for my needs.

Thanks so much for your help!
