### ISSUE TITLE
request: OSC Title when entering 

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#271]
Currently the OSC message `/ontime/title` returns the title of the current ***running*** title. Would love to have this for the currently ***selected*** title, wether it's counting down or not. I imagine this could be sent out whenever a different cue is selected.

Would also request that `/ontime/time` gets sent out whenever a cue is selecte.

For example, I am using [OSC/Pilot](https://oscpilot.com/) to create a full-screen touch surface to run a show. I have a bunch of buttons that each send "/ontime/gotoid" and the cue id to load various cues. I am also pulling in `/ontime/title` and `/ontime/time` OSC messages so I can see what is currently selected and the time on it.

**Comment by cpvalente** [comment]
Hi @tcconway, thank you again for this.

I believe integration to be key for ontime being successful, so I am happy to look into this and it would be great to work on this together.

It would be important to try and clarify the scope of the feature. Ontime does not offer much vocabulary as to its operations so, sometimes, there is room for misunderstandings on the meaning of simple things such as selected <> running, event <> cue

In the interface you can navigate with something that the app calls cursor. as of v1, this does nothing else than allow for using the keyboard to add events.

In the application domain, a selected event is an event loaded in the playback, regardless of whether it is playing or not. The selection in the interface is user-specific and the server does not know of its state.

Onto your request:
- Can you describe the moments when ontime would broadcast these messages?
- Would this broadcast be periodic (eg. once a second?)

This seems very much in line with the plans for integration, which I hope v2 will unblock.
Thank you for your help

**Comment by tcconway** [comment]
Hi @cpvalente and thanks for your time reviewing this.

Here's what I see to be the top line scope in particular to this topic, (keeping in mind that this serves my personal needs LOL). Using a StreamDeck, OSC App (eg. TouchOSC, OSC/Pilot), an an app of some kind (e.g., vMix), herein called a "The Device" to control playback operations during a show. I'm a big fan of pushing a tactile button over using a mouse during shows.
 
Actions from The Device should probably be: 
- Next Cue & Previous Cue
- Play, Pause, Stop
- Speaker Timer Message On/Off, at the minimum. Public Message and OnAir status are important, but happen so infrequent that it might not warrant the time to code them into a button on The Device.

Received data to The Device should probably include:
- Title, number, and ID of the current cue
- Time shown on the clock, even if it's not counting up/down
- Total time of the cue
- Is the cue counting up or down

All this revolves around the important concept of there being an Operator -- a person who is in charge of Show Operation Controls (advancing/starting/pausing/stopping of cues). The Operator doesn't necessarily have to be a single individual. There are several different ways to design for this (although this is just top of mind...and doesn't include all/better ways):

- Option A: Anyone with access to the App, /editor, or /cuesheet can change the current cue/start/stop/pause
- Option B: Lock the Show Operation Controls /editor and /cuesheet with a 4-digit pin, to keep the curious out.
- Option C: You could even have a locking system that allows only one Operator to control the Show Operation Controls at a time, but this sounds like a lot of work.

With this Operator design consideration, I'd recommend that whatever the Operator does, it should reflect everywhere, in real time. They are the one in charge during the show, and everyone else (and all of The Devices) should see what they do in real time. 

If you wanted to keep the OSC traffic down, I imagine you could have a `/osctimer/refresh` command that would broadcast out the not-so-time-specific details on demand. Another way to look at it:

A cue gets changed, or the server receives a refresh command. Things that can get sent out once:
- Cue title
- Presenter name
- Total cue time
- Event Number
- Cue number (order of the cues, 1, 2,3, etc)

Every second:
- Current Time
- Overtime flag
- Event Title, and/or cue number

I know a lot of this already happens (and is on the roadmap to v2), but wanted to add a bit of color around what I see to be an important role - The Operator, and how their actions should be broadcast out.

Hope this helps!

**Comment by je71175** [comment]
Hi
Can I ask how you see the last part of your request working?

_A cue gets changed, or the server receives a refresh command. Things that can get sent out once:

Cue title
Presenter name
Total cue time
Clock Start time and End time
Event Number
Cue number (order of the cues, 1, 2,3, etc)_

Are you trying to sync the data in onTime with another platform? If so curious which?

Also on this request, I'd recommend a slight change 

_Received data to The Device should probably include:

Title, number(in the list), and ID of the current Cue
**Time shown on the clock, even if it's not counting up/down
Total duration of the cue
Clock Start time and End time
Is the cue counting up or down_**

To

Clock current time 
Clock Ending time
Time remaining
Is running 

This data is more easily digested in apps and controllers like TouchOSC 

Thanks Jason

**Comment by tcconway** [comment]
Thanks @je71175

I think the big picture for me personally is to press a "Prev" or "Next" button on a device (TouchOSC, Stream Deck, whatever) and see the selected cue title, duration and current counting-down time (if it's running) on said device...all of them actually.

I imagine being on stage with the presenters during rehearsal, whipping out my phone with TouchOSC on it, and jumping between cues, starting and stopping, all while seeing the title and total of each cue on my phone. I can do some of this now, except for "Next", "Last" and seeing info on the currently-loaded cue.

**Comment by tcconway** [comment]
So...now I'm using [Osculator](https://osculator.net/) with the intent of showing times on a StreamDeck running [Companion](https://bitfocus.io/companion). It works great...except I'd love Ontime to send the current cue's total time when a next/previous command is taken. Right now I see when I press next or previous, the OSC message `/ontime/next` or "/ontime/prev" gets sent. I'd love it to  ALSO send a `/ontime/time 00:30:00` time, so I can update my buttons as it comes in.

**Comment by cpvalente** [comment]
Hi @tcconway, this sounds great.
OSC integration is next on my v2 list, so the timing is excellent.

Could you please compile these requests into a feature description? It would also be great to get @je71175 input here

**Comment by tcconway** [comment]
Here's a first stab at what makes sense to me...but I defer to what others would prefer:
Here is a recommended dictionary for OSC implementation for Ontime. It's originally based from the [Ontime documentation](https://cpvalente.gitbook.io/ontime/control-and-feedback/osc).

## OSC Control API (default port 8888)

| Message         | Parameter | Action |
|-----------------|-----------|--------|
| /ontime/play    | *--*|  Start timer on selected event |
| /ontime/start   | *int* event order eg: (1) | Starts playback of given event |
| /ontime/startid | *string* event id eg: (84d1) | Starts playback of given event |
| /ontime/pause   | *--*|  Pause timer |
| /ontime/prev    | *--*|  Select previous event |
| /ontime/next    | *--*|  Select next event |
| /ontime/unload  | *--*|  De-select event |
| /ontime/reload. | *--*|  Reload timer for selected event |
| /ontime/roll    | *--*|  Start Roll Mode |
| /ontime/delay   | *string* time in minutes eg: (10 or -10) | Delays running timer by given amount |
| /ontime/goto    | *int* event order eg: (1) | Jumps playback to event |
| /ontime/gotoid  | *string*  event id eg: (84d1) | Jumps playback to event |
| /ontime/onAir   | *--*|  Turn *On Air* flag *ON* (see studio clock) |
| /ontime/offAir  | *--*|  Turn *On Air* flag *OFF* (see studio clock) |


## OSC Feedback (default port 9999)


### Trigger: selected event changes or is reloaded
When an event changes, the following is sent:

| Message         | Parameter | Notes |
|-----------------|-----------|-------|
| /ontime/action    | *string*    |  Returns: `next`, `prev` or `reloaded`     |
| /ontime/eventNumber | *int* | Returns index of the newly selected event |
| /ontime/presenter  | *string* | Returns the presenter text of the newly selected event |
| /ontime/time | *string* eg: (00:10:23) | Returns newly selected event's total running time |
| /ontime/title  | *string* | Returns the title of the selected event |


### Trigger: event is playing

When an event plays, the following is sent at the moment of the action...

| Message         | Parameter | Notes |
|-----------------|-----------|-------|
| /ontime/action    | *string*    |  Returns: `playing` |


...and the following gets sent **once every second**:

| Message         | Parameter | Notes |
|-----------------|-----------|-------|
| /ontime/orderid | *int* | Returns order number (e.g., 3) of the selected event |
| /ontime/eventid | *string* | Returns Event Id (e.g., 2ea0f) of the selected event |
| /ontime/overtime | *int* | Returns `1` if in overtime or `0` if in regular countdown time |
| /ontime/presenter  | *string* | Returns the presenter text of the selected event |
| /ontime/time | *string* eg: (00:10:23) | Returns selected event's total running time, or negative time counting down |
| /ontime/title  | *string* | Returns the title of the selected event |


### Trigger: event is stopped or paused

When an event stops, the following is sent:

| Message         | Parameter | Notes |
|-----------------|-----------|-------|
| /ontime/action    | *string*    |  Returns: `stopped` or `paused` |

**Comment by progressmedia** [comment]
Thank you for the work on this so far. I just wanted to mention a similar need which is that, it would be really nice if there was a system to import variables between Companion. So for example, CueTimer on Companion allows you to bring 5 variables into CueTimer, which help to customize buttons etc like above. 
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/117510714/221433989-009bcbab-0e2a-42b1-828f-3a12a135bfdc.png">

**Comment by cpvalente** [comment]
Hi @progressmedia, thank you for reaching out

I am currently working on the integration engine for v2, so it is an excellent time to talk about this.
However, I am unsure if I understand what I am looking at.

We would leverage companion to send some data to ontime. Is this correct?
What does ontime do with this data? Since you mention buttons, I may be looking at it wrong. Could you elaborate?

**Comment by progressmedia** [comment]
Ok so in my vision for this, you would have a similar list of variables, and in a use case like this: 
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/117510714/221436649-42d690aa-1085-4cba-9d5d-35d750e5dc44.png">
Then that would essentially feed timer data to ontime which would then render it, as the playlist here to the right. 
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/117510714/221436731-8e3dcd8e-e706-4f23-88e5-7252056ea267.png">

Maybe I am missing something about the ideal way to integrate something like Mitti with OnTime? I just want to make a linked way of easily having the timers auto-populate based upon what my mitti is playing.

**Comment by cpvalente** [comment]
I see. I believe it could be tricky to have arbitrary variables into ontime.
You could use one of the APIs to control the playback from another application, including companion / mitti

This would, however, not allow you to synchronise data about the rundown.

The easiest way forwards is to put together a few scenarios and specify the necessary data.
We can then see what can be done that is not covered by one of the APIs. I believe integrations are important and am happy to put in the work to strengthen this aspect of the app

**Comment by progressmedia** [comment]
Ok, so if I have a 30(X) second video, and I hit play in Mitti, couldn't I just start a new OnTime timer for __X__ seconds and then start the timer? We're an online outlet, so we don't have hard times like a broadcast station would. So for us at the present, the concept of total run time isn't relevant. I think it would be most natural for many people to use it to trigger timers, and it would make it a lot more versatile if it doesn't fundamentally break it.

**Comment by cpvalente** [comment]
I am not entirely familiar with your workflow and it would be great to see what we can do
Would you mind contacting me at mail@getontime.no to discuss this?

**Comment by tcconway** [comment]
FWIW, the existing list of variables will probably do you well.
Within Companion v3.0.0 **BETA**, there are a TON of variables exposed.

Just paste one of them, for example _$(ontime_2:clock)_,  into your button name!

https://i.ibb.co/2n9sQJN/image.png

**Comment by cpvalente** [comment]
Hi @tcconway .

Could this be closed on favour of the integration feature in v2?

**Comment by Punkerschaf** [comment]
I haven't tried yet,  but as I understand the last sentence of ([Websocket API docs](https://cpvalente.gitbook.io/ontime/control-and-feedback/websocket-api) you can use these variables in the OSC integration as well.

**Comment by tcconway** [comment]
Thanks @Punkerschaf! This works perfectly!

**Comment by cpvalente** [comment]
Thank you @Punkerschaf, this is exactly the case.

quick note to add that timer.current will return the running timer in milliseconds. If we need to send this information in any other format (eg. text), please do open an issue for it.
