### ISSUE TITLE
Would like to have two different QR codes - one for "Public" and one for "Backstage"

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#276]
We're using the Backstage view quite a lot lately, and have been taking advantage of the automatic-QR Code generation to show various things.

For example, we're using `WIFI:T:WPA;S:SSIDName;P:Password;` in the "Event URL" field for the first day -- helps crew get on the Wifi so much easier. Then we change it to a shared Google Docs link, or other online production forms for show days.

So, this brings us to the request. Can there be a different QR Code for "Backstage" views and a different QR Code for "Public" views? Right now, we aren't exposing any "Public" views, but I bet our clients will love it once they know about it Shhh.... ;-) I'd love to use the QR Code as-intended for Public views -- like showing the public-facing event pages -- but simply love having a QR code for the techs backstage to do a different thing.

Thanks!

**Comment by cpvalente** [comment]
Hi @tcconway, this is a great observation and happy to know that the feature is. It should have always been like that.
I will make sure this is part of v2. Meanwhile, would it make a difference to you to see this rolled out in v1?

**Comment by tcconway** [comment]
I'd say, have it be for v2 -- doesn't affect our shows as my clients haven't realized there's a "public" side of things ;-)

**Comment by cpvalente** [comment]
Done in v2
