### ISSUE TITLE
Pagination dots. Should one be bright?

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#277]
On the top/right of both the /backstage and /public pages, there is a list of upcoming cues/events. I've noticed that it gracefully loops through content if there are more cues than it can show at one time. Nice! Here's an example: https://i.ibb.co/X5fsFkP/image.png

I see three dots, signifying that there are three pages to the loop. Would it be possible to have the corresponding dot be white, while the others remain gray? That would be a nice indicator of which page you are viewing. For example if the second dot is white, you are viewing page two of the list.

**Comment by cpvalente** [comment]
Hi, I am working on this feature as we speak.
It seems like this behaviour was lost sometime during the beta 1 period, not entirely sure why.

This is fixed in v2. Thank you again

**Comment by tcconway** [comment]
Thanks!
