### ISSUE TITLE
Seconds in studio clock

### ISSUE THREAD

**Issue by Cammate** [cpvalente/ontime#282]
Hi!
Is it possible to have the seconds (in numbers) added to the studio-clock? That would greatly add to the value for using this in a live broadcast environment.

Kind regards,
Marc

**Comment by cpvalente** [comment]
Hi Marc, this is absolutely possible.
Could you help me classify the features in a spectrum between convenient to we-cant-use-without?

**Comment by Cammate** [comment]
Hi Carlos,
Well, when in a live broadcast having a synced clock with readable seconds is crucial. Ie. When your news-broadcast has to start at 18.00h sharp a director wants a clock he can depend on. He or an assistant counts the seconds out loud untill the start of the program. 
So there are 2 parts in this request that are important:
- having a synced clock (this is convenient, but can be overcome)
- having the seconds easily readible so you can countdown with this. (We can't use it in a proper way without the seconds)

Besides that there are a few things that would make working with OnTime more convenient:
- Being able to sync the clock with a wordclock of other form of timecode
- Being able to view the remaining time of a videoclip that is being played out (ie. out of CasparCG, Playbackpro, Cuelab, Vmix, and so on. I know that there are a few software packages that are already supported, that great!)

Hopefully this gives you an idea...
Kind regards,
Marc

**Comment by cpvalente** [comment]
Hi Marc (waited a long time in my life to say this),
I believe we can make a few features out of this. For now, we could focus on the studio timer having some seconds :D

I believe there is already an issue for adding MTC sync, if you could describe what other transports you encounter in your environment we can at least investigate.

Regarding the sync with other packages:
We could try and identify a few transports for the different implementations. However, I am not too confident that we would ever want to create close integrations for all those platforms. This should probably be done externally by some sort of controller

**Comment by Cammate** [comment]
Hi Carlos,
That's great to hear. I wouldn't change a lot on the view. It is usable as it is right now. Just the seconds are missing.

I saw the issue about MTC. I work with LTC and wordclock normally. I know there are others as well, but these are the once I come by.

As for the integration of other packages. I can understand that it is not really doable to make something for every implementation. In a perfect world there would be some kind of standardization in the communication. Unfortunately that is not the case. I will have a look into how a "in-between" package could interact with software like CasparCG and OnTime.

Keep up the good work!
Regards,
Marc

**Comment by cpvalente** [comment]
It makes sense to me that we would avoid too much visual noise.
As suggested, the view provides a URL parameter `seconds` to enable showing seconds.

This is admittedly badly documented from our side and we will revise as part of the v2 release

**Comment by cpvalente** [comment]
Hi @Cammate 
The feature has been in production for a while and it will be part of v2
Also documented in [the docs here ](https://ontime.gitbook.io/v2/views/studio-clock)

Can we close this ticket?
