### ISSUE TITLE
request: receive and display osc string 

### ISSUE THREAD

**Issue by iainsyme** [cpvalente/ontime#283]
Hi Carlos!

Would be possible to integrate a field to display an incoming osc string on the Studio Clock webpage? We are looking for a way to use it as a monitor of a looping show, and ideally would fire out an '/osc/ontime/title of section' string. That way we would be able to, at a glance, look and see where we are in the show.

Best,
iain

**Comment by cpvalente** [comment]
Hi @iainsyme, thank you for reaching out.  

Do you see this replacing one of the existing fields or adding a new one?
A design proposal could be helpful.

With that in mind, I wouldn't think this would get into production, at least until v2 is released

**Comment by alex-Arc** [comment]
Hey @iainsyme have you tried out this new release https://github.com/cpvalente/ontime/releases/tag/v2.21.3
Dose the `External field` solve your use case?
