### ISSUE TITLE
Upload corporate logo

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#30]
Add functionality to upload custom logo. 
it could maybe be present instead of the QR code

**Comment by cpvalente** [comment]
For anyone following this. Although it has been requested a few times, the feature is halted for lack of good design.

If someone can make a suggestion on where does the branding logo go I am happy to implement. I believe the initial suggestion to replace the QR code is not a good solution

**Comment by tcconway** [comment]
Here are some layout suggestions!

https://ibb.co/kmdXYv6
https://ibb.co/JCKjL2M
https://ibb.co/DKDSzRg
https://ibb.co/Sfccyhg
https://ibb.co/fnXv2J9
https://ibb.co/Tv3ZNKr
https://ibb.co/8grhN7z

**Comment by cpvalente** [comment]
Closing this for now as, since v2, there is no Ontime branding in any of the views. Any further work here would be community-led. Ideally with some suggestions as to how can this happen

**Comment by cpvalente** [comment]
We are deciding to revive this as part of the design review.

The proposal is to implement a user given image in the signage views
- timer
- public
- backstage
- timeline (?)
- studio clock

We may prefer to implement this on a view-by-view basis as we review the designs

## Feature description
- in the project settings, user should be able to upload an image. 
- if the image exists, the views specified above should show the image inline with the design 

## Implementation details
- it is up to the user to provide a good image format
- we need to decide whether we want to keep the image and save its path in the project, or keep the base64 reference directly in the project json file

**Comment by alex-Arc** [comment]
implemented with #1314 and #1335
