### ISSUE TITLE
Code signing

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#31]
See code signing before release

**Comment by cpvalente** [comment]
I will be closing the issue until I find a FOSS friendly way of getting certificates

**Comment by Mavyre** [comment]
@cpvalente Just FYI, Apple is issuing free developer accounts for Non-profits organizations: https://developer.apple.com/support/membership-fee-waiver/

We used this to sign and notarize the app and pkg to distribute ontime through a self-service portal, without any issue after finding out how to do everything correctly.

If you need more details, I'd be happy to help you out on that!

**Comment by cpvalente** [comment]
Hi @Mavyre , thank you for this. It is great news.

Unfortunately it seems that we might be outside the covered regions. 

> Eligible regions: Australia, Brazil, Canada, China mainland, France, Germany, Israel, Italy, Japan, Mexico, South Korea, United Kingdom, United States.

Although it is unclear to me how this applies to individuals I will keep track of this to see if the state changes.
It is my understanding that is possible to sign the app without a paid developer account, this would at least let the app run as a native build for arm macs. 
Do you have some experience on this? Perhaps you would be able to help?

**Comment by Mavyre** [comment]
I tried to find a way to sign without a paid developer account. I could not find any way however.

Seems like we're stuck at the official Apple signed certificates...
