### ISSUE TITLE
Feat: Localization of web views

### ISSUE THREAD

**Issue by kev-ac** [cpvalente/ontime#324]
It would be great to be able to translate web views to enhance the experience for guests. 
If others feel the need to have this feature and could possibly be merged in I can work on a PR. 

Proposed solution: 
- Library: react-i18next
- Set desired language with an URL query param

**Comment by cpvalente** [comment]
Hi @kev-ac, thank you for reaching out and for offering to help.

I completely agree this would be a good improvement and don't see any downsides to having a translation in place
Few thoughts:
- translations should only happen to views available to guests. This would mean cuesheet and editor should not be translated.
- with this in mind, there is very little to be translated, and I wonder if i18 might be overkill. Many users consume the views on less powerful devices such as TVs and tablets. Keeping the bundle sizes for the views low is important. I imagine that a simple solution using a translation map should be sufficient and not too cumbersome (?)
- this PR should be targeted for v2

What do you think?

**Comment by cpvalente** [comment]
From the app side, this would be a great addition. I would welcome a PR.

If you have availability to make a proposal, it would be fantastic. 

I have documented the [development process ](https://github.com/cpvalente/ontime/blob/v2/DEVELOPMENT.md)in v2. Please do get in touch if I can be of help mail@getontime.no

**Comment by cpvalente** [comment]
Hey, good work. I dont think I would have done it much differently myself.
Few questions:
- what does the common prefix symbolise? I hope I guessed correctly below
- would it be simpler to use a javascript object?
- can you please add the new option to `OverridableOptions`? I will eventually get around to make a menu to change these

Either way, these are the strings in the views:
```
export const langEn: TranslationMap = new Map([
  ['common.time_now', 'Time now'],
  ['common.now', 'Now'],
  ['common.next', 'Next'],
  ['common.started_at', 'Started At'],
  ['common.expected_finish', 'Expected Finish'],
  ['common.stage_timer', 'Stage Timer'], // is the name good to begin with?
  ['countdown.select_event', 'Select an event to follow'],
  ['countdown.to_start', 'Time to start'],
  ['countdown.waiting', 'Waiting for event start'],
  ['countdown.running', 'Event running'],
  ['countdown.ended', 'Event ended at'],
  ['common.start_time', 'Start Time'],
  ['common.end_time', 'End Time'],
]);
```

**Comment by kev-ac** [comment]
> what does the common prefix symbolise? I hope I guessed correctly below

The common prefix was chosen for strings which are shared across multiple views. 
Strings which are unique to a specific view should be prefixed by the view name. 


> would it be simpler to use a javascript object? I don't think performance will be at play here

A Javascript object could be easier to read, I can have a look at it.
What would be your desired structure for the object? Something like this?
```
const langEn = {
  common: {
    time_now: 'Time now',
    now: 'Now',
  },
  countdown: {
    select_event: 'Select an event to follow',
    to_start: 'Time to start',
  },
};
```

> can you please add the new option to OverridableOptions? I will eventually get around to making a menu to change these

I will do that.

**Comment by cpvalente** [comment]
I don't have strong opinions here and wouldn't mind either way.

Personally, I would prefer a flat object with the prefixes you mention

I will also try to add an eslint rule to ensure all text in a view goes through a function. Fingers cross, I remember

**Comment by kev-ac** [comment]
I've changed the code to use a js object instead of a Map. 

Would you mind refactoring the OverridableOptions _thing_? I think you have deeper thoughts about how it should work.
I've kept in the language setting in`AppRouter.tsx` for now. Feel free to remove it when you're done.

=> PR #325

**Comment by cpvalente** [comment]
Thank you! great work! Would you like to contribute with some more code to ontime 😅

**Comment by cpvalente** [comment]
hahaha, sounds familiar. It was worth a shot...

If anyway you bump into some time do let us know.
Can always pick up some CSS tasks to make the views more responsive 😄

**Comment by cpvalente** [comment]
I appreciate your help @kev-ac 

Testing around, I was wondering if it would be friendlier to have this in one of the settings menus in app.
That seems to be a more common workflow on ontime. Global app settings with the possibility to override for a single view with a URL param

What do you think?

Either way, this provides a great start

**Comment by kev-ac** [comment]
There could be many other ways this can be achieved, for example in the settings menu or also maybe by the system locale of the PC. 
Both could also be combined: Settings menu takes the system locale als default (if its an available translation) and the user can override it.

**Comment by cpvalente** [comment]
Done in v2.
We can add translations in separate PRs without needing an open issue

Thank you @kev-ac
