### ISSUE TITLE
Stuck on loading screen - v2.0.0-beta2

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#330]
Hi!

Having the issue that I´m stuck in loading screen forever after launching the app. Dots are circling forever, nothing happens until I kill the app via Taskmanager.
Any ideas what´s wrong here?

v2.0.0-beta1 opens without any issue.

OS: Win10-21H2

**Comment by cpvalente** [comment]
Hi! Thank you for reaching out

I suspect the app cannot reach its resources.

We would need some more information to be able to help.
- did you install for users or for all users?
- which directory did you use for the installation? did you use the default path or a modified one? 

It would be very helpful if you could start the app from the command line. This provides a log of the process and should highlight the error

We have several users in beta 2 so I believe the error is in the installation. However it would be important to identify the problem so the app can recover

Thank you again

**Comment by Keksstar** [comment]
I tried both, install for all users or only me...
Used the standard path.... (program files/ontime for all users, appdata/local for only me) - no modifications of the install.
Also did an clean install and deleted all "old files" from previous installations.

Console output:
`(node:12392) UnhandledPromiseRejectionWarning: TypeError: Error processing argument at index 1, conversion failure from
    at Object.showErrorBox (node:electron/js2c/browser_init:49:5725)
    at C:\Program Files\ontime\resources\app.asar\main.js:185:14
(Use `ontime --trace-warnings ...` to show where the warning was created)
(node:12392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

**Comment by Punkerschaf** [comment]
Hey Guys,
I have this Issue too. But on MacOS Monterey. Thought it's because I'm on the road using an old MacBook Pro with "OpenCore Legacy Patch" to run the latest OS on unsupported old Hardware. So I used to have program crashes more often and didn't thought about a real issue.
If I can help, please tell me.

**Comment by cpvalente** [comment]
Thank you, I have removed the files for beta 2 from the release and will investigate

**Comment by cpvalente** [comment]
Hi, @Keksstar  and @Punkerschaf .
We have traced the issue to our instrumentation tool (sentry), which, in fairness, is also in beta. 

I have release beta 3 with a fix, could you please confirm that the distribution works in your platforms?

**Comment by Keksstar** [comment]
Beta 3 works fine for me, without the issue 👍
Thanks!
