### ISSUE TITLE
Improvement: Eventtime should be adjusted when time is added/removed

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#331]
Hi!
Would be great to have an selectable option that the event duration is adjusted when time is manually added/removed during an event. This should also affect all following event start-times. The new start-time is calculated based on the duration of the previous event.

It can be seen as part of #100

**Comment by cpvalente** [comment]
Hi @Keksstar , could you please expand on the feature?

Do you mean time added by using the buttons next to the playback?

**Comment by Keksstar** [comment]
Yup, when adjusting the time manually in the "playback" (-1 +1 -5 +5) it should adjust the overall event duration and not only the current playback time.
It should then also adjust the starting time of all next events.

**Comment by cpvalente** [comment]
This makes a lot of sense to me and it was one of the reasons to make v2.

The current planned approach is that the Delay Block would have an option for "Absorbing added time". So any added time gets added into the delay and propagated from there.

It is important noticing that delays are not actually changing the public-facing times until applied, so this would only work for backstage / production data

What do you think?

There are some other decisions to make related to the behaviour of delays in Roll Mode.

I am happy to discuss this over email at mail@getontime.no

**Comment by Keksstar** [comment]
Well, that means that after each event an delay block must be added to compensate for any added times?
The delay block workflow seems to complex for me in fast productions - so we should add #331 into #100 and leave it as it is right now.

I also think that ontime must generally decide what it wants to be... Personally I only see it as an production tool and wouldn´t use the times for any public use. All users I know from also only use it for production. But that´s not my decision... Maybe you should raise a poll on this topic :-)
