### ISSUE TITLE
v2 Docker version requirement?

### ISSUE THREAD

**Issue by Fred-DTV** [cpvalente/ontime#336]
Heyo,

I've tried to update our docker image, running on our Synology NAS, to the v2 beta, but it wouldn't start the container.
Here are the logs from the ontime container v2: https://pastebin.com/XQFE7F4x

Synology (for whatever reason) doesn't update the Docker version, so it is still on 2010.10.3.-1308.

Could it be that this is the issue?

**Comment by cpvalente** [comment]
Hi @Fred-DTV , thank you for getting in touch.
I believe this might be a problem on our side, and we will investigate. Meanwhile, can you please check that you are running the latest build?

https://hub.docker.com/layers/getontime/ontime/beta_v2.0.0-beta3/images/sha256-0c38f9bda90722892f245211e4fe832ca3a454e075db5eff3c1632e8b3dab0fd?context=explore

**Comment by cpvalente** [comment]
Hi @Fred-DTV , we believe the newest release beta-4 has fixed the issue, can you please check?
https://github.com/cpvalente/ontime/releases/tag/v2.0.0-beta4

**Comment by Fred-DTV** [comment]
It is up and running! Amazing job @cpvalente :) thanks a lot, i am excited to try the new version

**Comment by cpvalente** [comment]
Nice, thank you! 

Please do get in touch with feedback. We are making some adjustments to the playback but, will hopefully, soon be able to make v2 a stable release.

Feedback is very much appreciated.

On the topic of the bug: it is ironic that the issue was in the bug reporting tool
