### ISSUE TITLE
Can't delete OSC statements

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#345]
**Version:**
2.0.0-beta4

**Issue:**
OSC statements can't be deleted, even though they initially look like they are.

**Steps to repeat:**
1. Open the  "Integrations" window by clicking on the puzzle piece on the left hand side of the screen.
2. Click on "OSC Integration" tab bar and click on any of the "On..." statements.
3. Click "Add new" button and add an OSC statement.
4. Click the red "-" button to delete it. Notice it disappears.
5. Close and re-open this window and notice that the OSC command hasn't really been deleted.

**Comment by cpvalente** [comment]
Hi @tcconway, thank you for this.

The change will only be made once you click the Save button. This is missing from your steps to recreate.

Two follow-ups here:
- can you please confirm that this is the case and that the functionality is correct by clicking Save?
- in the case it works: how can we clarify this in UX? All settings in modals will need a save action to take effect

**Comment by tcconway** [comment]
Thanks for the reply. The Save button doesn't every enable.

**On-Open:**
<img width="573" alt="image" src="https://user-images.githubusercontent.com/403326/233118381-e9cf297a-20c9-4d5c-b922-bc48cdedacec.png">

**After deleting the two elements**
<img width="573" alt="image" src="https://user-images.githubusercontent.com/403326/233118671-73b5aad8-b40d-4138-aee9-4ee3d1f2085a.png">
Note: Not shown is the mouse cursor with the "not available" cursor when hovering over the Save button.

**Comment by cpvalente** [comment]
Hi @tcconway, could we close this issue with the new beta 6?

**Comment by tcconway** [comment]
It looks like the issue still persists in beta 6.

Steps to repeat:
- Open the Integration settings by clicking on the puzzle piece.
- Click the "OSC Integration" tab
- Click the red "-" on a custom osc message
- Click save.
- Close the window.
- Re-open the window and notice the osc message line still exists.

**Comment by cpvalente** [comment]
ah my bad, I think I overlooked the whole issue and fixed only part of the bug. 
This is core to v2 and I will make sure it gets fixed
