### ISSUE TITLE
Request: Add Block type to Studio Clock

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#348]
Would love to see the Block element reflected in the Studio clock. Perhaps something like:
![image](https://user-images.githubusercontent.com/403326/233095643-db5e8f66-b760-48f1-9746-37b8f8b9439a.png)

**Comment by tcconway** [comment]
Always! Point me in the right direction!

**Comment by cpvalente** [comment]
We have decided not to include improvements in the studio clock view until a new specification is made
