### ISSUE TITLE
Input time with "9am" or "6p" in the Start or End fields

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#350]
_Note: italicized text was added to add clarity._

For the Start + End fields, would love to add time like:

- "9am" -> 09:00:00   --   _User puts a number 1-12 with either "am or pm" to signify a specific time._ 
- "6p" -> 18:00:00  --   _User puts a number 1-12 with either "a or p" to signify a specific time._ 
- "9:15am" -> 09:15:00  --   _User can also use a number 1-12, a colon and an number 00 - 59 with either "am or pm" to signify a specific time._ 

All these with or without spaces between the am/pm _or a/p_.

PS: :Love you can add "10m" type of nomenclature to the duration.
PPS: What does pressing the "S" "E" or "D" buttons do?

**Comment by cpvalente** [comment]
Hi @tcconway 
Would you be in favour of closing this ticket with the current implementation?

**Comment by tcconway** [comment]
Adding time works great! Thank you.
