### ISSUE TITLE
Block shows "Display Block" on Cuesheet

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#353]
Version:
2.0.0-beta4 

Issue:
While adding a "Block" in the event list, it shows up as a "Delay Block" in the /cuesheet

Expected:
The Block should show on the cuesheet with the provided name of the block.

**Comment by cpvalente** [comment]
Thank you

**Comment by cpvalente** [comment]
Hi @tcconway, can this issue be closed with the implementation in beta?

**Comment by tcconway** [comment]
Thank you!
