### ISSUE TITLE
Help needed: Responsive editor views

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#359]
The most important view in the application is the editor. This should allow for controlling the timer and message status and editing and managing the rundown.

![looking good](https://user-images.githubusercontent.com/34649812/233835967-6699c77e-7459-46fa-b5cb-670271a07b3a.jpg)

However, this view is not particularly responsive. The [offending code is here](https://github.com/cpvalente/ontime/blob/v2/apps/client/src/features/editors/Editor.module.scss)
Two major issues:

1. Windows machines have a default zoom of 125% 
![windows-zoom](https://user-images.githubusercontent.com/34649812/233835923-1ae68c2a-b446-4eeb-af5e-5bd9a9405352.jpg)

2. MacOS is lower than HD
<img width="1624" alt="Screenshot 2023-04-23 at 12 47 16" src="https://user-images.githubusercontent.com/34649812/233835947-5d4db1ed-e955-4a09-b850-dfcce7cb91ed.png">

These issues are easily circumventable by 1. disabling Windows zoom or 2. Zooming out the interface.
However, this is a bad introduction to the app, and we would like to improve.

### Todo
We would need to improve the style in the editor to ensure that it scales well in these situations.
We should not have to introduce new font or element sizes. Changes should be holistic for the entire page contents.

PRs on this task are welcome, please ensure that code changes are based from v2

**Comment by 0x088730** [comment]
My name is Noah Sim.

Please check my portfolio website -https://neverlandworld.vercel.app/

As I'm a professional front-end developer, I have good experience with  Pixel-Perfect website development and Super animation UI development.

I have checked your requirement more closely.

I can start working right now.

Please get in touch

**Comment by SabahatRathore** [comment]
i will fix this and it responsive

**Comment by ZeyadZewail** [comment]
Hi, i saw your issue on upwork.

Two questions.

1. would it not be better to disable the windows zoom to design once then adapt to the different sizes regardless of device?

2. what do you mean by "MacOS is lower than HD",  it seems the same to me but maybe Its the image compression or maybe its something related to retina display.

**Comment by SabahatRathore** [comment]
Yes when we make reponsive design it call work on all size of different
screen...
I can understand second question..
We have to use Media query to make it responsive

**Comment by SabahatRathore** [comment]
If you want to work this is my what's app contact

**Comment by 0x088730** [comment]
What development tool did you use to make the website?
- For full responsive website building, we can use many kinds of responsive website development module.
Ex: React-Responsive, React-Grid-System, React-FlexBox-Grid, React-BootStrap etc.
Via project development, we can discuss in more details.
Thanks

**Comment by SabahatRathore** [comment]
I use react gird and flex for responsive

**Comment by cpvalente** [comment]
Hi @SabahatRathore 

Thank you either way for taking the time to comment 

However, this sort of comments are unhelpful and don't show understanding on how to work in a production application. 

Have you analysed the current solution? How is your solution different or even better?
Have you understood the cost of applying a new styling framework to an application that is in production?

**Comment by SabahatRathore** [comment]
There are many ways to make react site responsive,for example we use flex
and then for each screen i use media query to make it responsive for every
screen
