### ISSUE TITLE
Ontime Fullscreen

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#360]
On Windows: When maximizing to fullscreen, ontime is maximized vertically, but not horizontally.
Should also be streched horizontally to give an better user experience.
![grafik](https://user-images.githubusercontent.com/15065206/233845747-19264be5-124c-41cd-810e-3dc50540d837.png)

#improvement

**Comment by cpvalente** [comment]
This is likely not the fix you were hoping for. But this buttons are removed in the next version in favour of letting the OS do this for us

**Comment by Keksstar** [comment]
Then you have the buttons top right... Same effect ?

**Comment by cpvalente** [comment]
That's right. We toyed with the idea of removing the OS bar and creating our own.

This is part of the reason ontime has the full screen and minimise buttons.

We recently decided that we would prefer using that real estate for features and would let the OS window do its thing.

I will also make sure that the window can maximise properly.
What resolution is the screen you experience this with?

**Comment by Keksstar** [comment]
Got it :-) Thanks!

3840x2160

**Comment by cpvalente** [comment]
Hi @Keksstar , do you think this can be closed with the implementation in the beta?

**Comment by Keksstar** [comment]
Yes, perfectly solved! Looks great. Thank you! :-)
