### ISSUE TITLE
Request: Adjust seconds

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#366]
I tend to do a lot of things that we are tracking seconds. Would it be possible to add +/- functionality to adjust running time in seconds?

One approach is to hold CTRL or CMD down and clicking +1, -1, +5, -5 would affect seconds? When holding down CTRL a label "seconds" could pop near the top of the buttons...or something else to identify these are seconds we're clicking on?

**Comment by cpvalente** [comment]
Hi, this is a great point. 
The current workflow uses minutes as the standard unit. Meaning that adding seconds would need some complex-ish maths from the user side

eg: 0.1 -> 6 seconds

I see two points of action here:
- time shifting endpoint makes it easier to use seconds
- improve UX in adding seconds

As for the second point:
- as a browser based app, shortcuts is not something particularly easy to handle and I am skeptic of creating shortcuts which conflicts with native events
- we are aware that we will unlikely be able to build an interface that satisfies everyone. In this case we have instead focused on adding good integrations so we can offset this work to something like companion 

The way that I see forwards is that you are able to customise the 4 buttons that add time to the running timer. This should be done carefully as we already start cluttering this section (see beta 5). Any help here is appreciated

**Comment by cpvalente** [comment]
This is implemented for the integrations but not yet in the interface
