### ISSUE TITLE
Adding flashing/blinking indication when time is over on the speaker panel 

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#371]
It would be very useful for the speaker / stage-moderation to get a red-flashing/blinking indication when the time is over.
http://<ip-address>:4001/speaker

This is one piece of few wishes/requests from our collection what speakers told us after a event was happen.
Speaker are very busy and stressed on stage and wish strong visual helpers on the active speech.

any consultation or feedback is highly welcome.
Thank you for your support!

**Comment by cpvalente** [comment]
We will be joining this with #382
