### ISSUE TITLE
Actions on multiple event selection

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#372]
As a nice to have feature, I was asking myself if a multiple selection on events at editor app would be helpful.
This would make sense, if quickly changes of many event-rows about public (on/off), label-colour, etc

any consultation or feedback is highly welcome.
Thank you for your support!

**Comment by cpvalente** [comment]
Currently, we wouldn't have what to do with this multiple selection
It is part of the plan to create a context menu for making quick changes as you describe. 

A multiple-selection flow could follow

**Comment by iqtreiber** [comment]
Last learnings from view events >>

select multiple event lines for
- set color label for many lines at once
- enable/disable "public" at once
- change timer type at once

this would help reducing work effort for event

**Comment by cpvalente** [comment]
## Some context

Currently, we have a context menu on the EventBlocks that allows for some quick actions
https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/rundown/event-block/EventBlock.tsx#L83

We would like to expand this context menu to affect a selection of items

We also have a cursor function that currently allows a single item to be selected at any time.
https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/rundown/event-block/EventBlock.tsx#L156

## The feature
1. We would need somewhere to store a list of Ids. when a item is selected with shift or ctrl we manipulate the list as usual
ie: Shift + click to select range, Ctrl + click to toggle add to selection. Clicking in an event would clear the selection by adding that single event to the list

2. In the UI, we would also need to add some style to the `<EventBlock>` to ensure the selection is visible

3. The context menu would need to check whether the selection has a single or multiple items. I suggest creating a new set of actions for multiple selections. We can start with adding `Set Is Public` and `Set is Private` which would change the `isPublic` field to contain `true` and `false`, respectively

4. We would also need a way to pass this information down to the backend. Either by calling the PUT endpoint for every item affected, or creating a new endpoint `batchEdit` specifically for this purpose. I would be inclined to prefer the latter.
Endpoint in frontend https://github.com/cpvalente/ontime/blob/master/apps/client/src/common/api/eventsApi.ts#L27
Endpoint in backend https://github.com/cpvalente/ontime/blob/master/apps/server/src/controllers/rundownController.ts#L37
 
I suggest we leverage the current `editId` for this https://github.com/cpvalente/ontime/blob/master/apps/client/src/common/stores/appModeStore.ts

Modifying the `editId` to be an array of strings would allow us to create the feature with minimal friction. We would need to change the logic in `EventEditor` only to read the first element of the array.
