### ISSUE TITLE
enhancement of export function in the editor app

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#373]
At the editor app it would be great to enhance the export function
Today the JSON configuration will be exported at this function.
Maybe it is possible to add a small prompt asking what to export?
It could be only the CSV or only the JSON but selectable for the editor

any consultation or feedback is highly welcome.
Thank you for your support!

**Comment by cpvalente** [comment]
Thank you @iqtreiber, I really appreciate help on things that can improve the UX of the app

There are some annoying technical reasons why it is that way, and I believe we should bite the bullet and make this happen. 
Hopefully in a not too distant future

**Comment by diaasaur** [comment]
Hey @cpvalente, can I take a shot at this? Looks easy enough for a newcomer!

**Comment by cpvalente** [comment]
Hi @diaasaur. It would be great to have your help here.

The entrypoint for the existing code in <Cuesheet> is here https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/cuesheet/CuesheetWrapper.tsx#L71

Please do reach out here or to mail@getontime.no if you need any help.

**Comment by iqtreiber** [comment]
Hi all,

as this original issue was talking about "export function" in the main menu,
I would like to ask if inside this issue "import" would also possible. (feeding data in both direction).
If this "import function" would need a separate issue, I will create one.

many thanks!

**Comment by cpvalente** [comment]
Hi @iqtreiber,
in this task we will only implement the exporting.

Implementing CSV import should be something separate and I am unsure on whether it would be a priority for us.
CSV is a great format on software to software communication, but not particularly human alterable.
I am not aware of any use cases where other apps can read and modify the ontime csv format

I do understand the need for a complete flow of add elements in ontime -> export -> modify elsewhere -> import changes.
I think #194 might be better suited for this.

You are welcome to disagree. Please do open an issue with and remember to detail your particular workflow to give us context on how can we help

**Comment by iqtreiber** [comment]
Hi @cpvalente,

What use case does have a export without a import?
Every second event, I am receiving a kind of excel sheet from various clients.
The most clients start with preparation in a sheet and at a certain point, they handover to the operator.
At this point, the datas need to be retyped again in Ontime, as no data import is available, correct?
In my point of view, I am only looking for save time in my work and of course type error.

If I misunderstood here something, please let me know.
thank you

**Comment by cpvalente** [comment]
Hi @iqtreiber, apologies that I have not clarified my comments.

The excel import already exists and what you describe should be possible right now.
What we don't have is a CSV roundtrip workflow, as ontime does not import CSV. Again, CSV is usually useful for software to software communication and would not apply in the workflow you describe

It is possible that I might be missing something, in the case the excel import is not doing what you need it to, I would love to hear about it. Perhaps there is an issue we are not aware of or a misunderstanding on the feature.
Feel free to reach out to email and we can chat through it

**Comment by iqtreiber** [comment]
Hi @cpvalente,

I am Apologise, you are absolutely correct. the feature excel import exist already and describe in GitBook.
https://ontime.gitbook.io/v2/features/import-events-from-excel#event-data
I am just having my troubles to find the import-doing (how to do import).
Is this import-doing at the same menu where import a JSON project file or somewhere else?

thank you

**Comment by cpvalente** [comment]
No problem @iqtreiber, there is a lot going on in the app

Yes, the import menu accepts json or excel, you import them the same way. Just select your excel file instead

**Comment by iqtreiber** [comment]
Great thanks!

Please be so kind and add this important information to the online manual for the next reader.
https://ontime.gitbook.io/v2/features/import-events-from-excel#event-data
If possible also provide a download there with one example excel sheet as a start base.

**Comment by cpvalente** [comment]
Hi @diaasaur, any updates here? Can I help you with this?

**Comment by cpvalente** [comment]
Hi @diaasaur , I am removing the assignment so that other collaborators see this task as available. If you would like to continue with this please let me know
