### ISSUE TITLE
Display the countdown time from roll-reature - showing "the event is starting in hh:mm:ss"

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#383]
Testing the very nice roll-feature, it would be very wonderful to get the countdown to START displayed.
This could be helpful on all viewer /public /backstage /timer ...... to see "the event is starting in h:mm:ss"

**Comment by urbs2005** [comment]
I actually also think this may be what I’m looking for as well.  I put in a question in the discussion board as I thought I was just missing the option.

I also was wondering if it would be possible to make the roll option individual for each event, rather than system wide?

**Comment by cpvalente** [comment]
Closing this as not part of v3
