### ISSUE TITLE
New progress-bar from /timer viewer for /public and /backstage

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#384]
By testing the beta-6 the new progress bar (white/orange/red) is super-improvement.
Many thanks for this wonderful new feature !!!

Question: would be possible that the new progress bar will come for /public and /backstage
- currently it runs from right to left (why not also from left to right)
- same color indication (white/organge/red)
- instead the progress bar runs the full width of page width, would be nice to have just above the event-box (there is already a grey line)

**Comment by cpvalente** [comment]
Hi @iqtreiber , thank you for your suggestions.
I will get around to organising and prioritising once v2 is through

Meanwhile

> currently it runs from right to left (why not also from left to right)

This is absolutely a bug and I will try and see it fixed. Meanwhile, it seems that refreshing the page fixes the issue
