### ISSUE TITLE
Display Event-Name on the top of Editor App & Rundown

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#385]
Would be possible to show the Event Name also on the Left-Top of Editor-App (there is empty place)
This would be also 1:1 used in the /rundown where on the Left-Top is a empty place.

If the application allow 2 more fields for Event-Date and Event-Location/City would increase the use.
Helping in the past and future to see quickly the What/Where/When. 

<img width="1797" alt="Bildschirmfoto 2023-05-18 um 11 44 02" src="https://github.com/cpvalente/ontime/assets/9744544/22d5096d-13bd-43e9-9d44-da6cac814a28">

**Comment by cpvalente** [comment]
Hi @iqtreiber, thank you very much for all your involvement with the app roadmap.

How would you feel about having this in the info section? Similar format as the **Playing Now** / **Playing Next** sections

**Comment by iqtreiber** [comment]
Hello @cpvalente,

Yes this would be fine with me.
As written in my original issue text, can this change consider all 3 fields?

1. Event-Name (existing data field)
2. Event-Date (new data field)
3. Event-Location/City (new data field)

thank you!
