### ISSUE TITLE
Event Editor: fields show stale data

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#388]
The Info field in the event editor does not seem to reset when moving across events

- Enable edit mode on the <MenuBar> (left menu)
- Select an event in rundown. The event editor (bottom drawer) should now open
- Edit the event info field eg: "test info"
- Select another event in rundown without closing the event Editor

You will now see that "test info" remains in the text area. we would have expected this to be cleared
We should also see if there is a potential for the same to happen with other fields

**Comment by asharonbaltazar** [comment]
Assign me, please

**Comment by asharonbaltazar** [comment]
I see three fields – Title, Presenter, and Subtitle (and Note to the right). 

So if I edit one of these inputs and quickly switch to another event, the edited input doesn't reset. This is the bug?

**Comment by cpvalente** [comment]
That is right. When you move from editing an event to another, the input fields data should change to reflect the new field
This is very obviously seen in the note field and in some cases the title - presenter and subtitle

I would suspect that the remaining inputs (colour and times) could also be vulnerable
