### ISSUE TITLE
Add fields to excel import

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#391]
With v2 we have added two new fields to the event definition

"endAction": "none",
"timerType": "count-down",

We should ensure this are imported from Excel (`parseExcel() in parser.ts`) and that it respects the definition enum. Ideally dynamically
It would also be important to ensure the validation happens on json parsing (`parseRundown() in parserFunctions.ts`)
```
export enum EndAction {
  None = 'none',
  Stop = 'stop',
  LoadNext = 'load-next',
  PlayNext = 'play-next',
}
```

```
export enum TimerType {
  CountDown = 'count-down',
  CountUp = 'count-up',
  Clock = 'clock'
}


```

**Comment by bunday** [comment]
taking a look at this
