### ISSUE TITLE
Create dynamic form for modifying URL parameters

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#399]
### Why

Currently, users can modify most of the view routes through URL parameters
What can be defined is in the documentation, which tends to become out of date as we go along. The process is also very error prone and generally unfriendly

### The task

We want to create a reusable form component which posts its data to the current hostname URL params.

**Requirements**
- The form should receive an object containing field and type, and generate a form to modify the given fields with an appropriate element (eg: text input for strings, switches for booleans). 
- On submitting the form, the fields and values should be pushed to the URL parameters of the current host
- We can leave validation for later

### Technical details

The URL params are now read inline in each view component. That is not ideal, but we will leave it as it is for now. 
We will use them to extract from which params a view have. We hope that the code and comments will suffice for documentation here. You can also see the documentation under [View Modifiers](https://ontime.gitbook.io/v2/views/minimal-timer)

Eg: for /minimal (the component with most overrides)
```
const key = searchParams.get('key');
const offsetX = searchParams.get('offsetx');
const alignX = searchParams.get('alignx');
const hideOvertime = searchParams.get('hideovertime');
```

Could be described like
```
[
  {
    field: 'key',
    description: 'Key colour (as an hex value, eg: #FF0000)',
    type: 'string',
  },
  {
    field: 'offsetx',
    description: 'Horizontal offset (-1000, 1000)',
    type: 'number',
  },
  {
    field: 'alignx',
    description: 'Horizontal alignment of timer',
    type: 'option',
    values: ['start', 'center', 'end']
  },
  {
    field: 'hideovertime',
    description: 'Whether styles should change in overtime',
    type: 'boolean',
  },
];
```

and generate an URL looking like
`localhost:4001/minimal?key=#ff0000&offsetx=10&alignx=start&hideovertime=false`

We can skip validation of the fields for the first draft, but if you are very keen we can leverage React Hook Form validation stuff here, like
```
  validation: {
    min: -2000,
    max: 2000,
    validate: () => function to validate
  }
```

**Comment by asharonbaltazar** [comment]
Drag-N-Drop in #403 is scaring me from picking up that particular issue. I'd like to dip my toes a bit more. Can you assign this one to me? Can't promise any timeline, though, if you're okay with that

**Comment by cpvalente** [comment]
Absolutely. We dont have any pressure towards this feature, but it will be a great addition to the app and very welcomed by the users.

It also sounds like a fun challenge.
Let me know if you need any guidance from the app side.
As far as UI goes, keep it simple and make the form a fullscreen overlay.

The code in the views generally runs in devices and we try to keep it to a minimum

If you want to chat about any of it reach out to mail@getontime.no

**Comment by asharonbaltazar** [comment]
So, lemme break it down to see if I understand correctly:

1. Clocks are customizable via the [URL params](https://ontime.gitbook.io/v2/views/clock#url-modifiers).
2. Currently, users must type these modifiers into the address bar manually to get the desired effect.
3. This issue wants to address number <span>#</span>2 by adding a form which pushes these modifiers to the URL. It would also allow editing values.

If I'm correct in my assumptions, where would you like this form to exist? I'm assuming a button somewhere on the screen that, once pressed, brings up a form in a modal.

**Comment by cpvalente** [comment]
Hi @asharonbaltazar , that is correct. 

The exact architecture for this is up for discussion. I would be inclined towards something along the lines:
- In the current <NavigationMenu>, we create a new entry "Customise" (or a better word that you might come up with
- The new entry will push the user to a new screen, which is the form. The new screen should take as parameters the URL path the user came from and the customisable fields object as described before
- The new form will push the user back to the original path along with the parameters defined in the form

I believe this to be the most straightforward implementation.
There are some loose ends that could improve this:
- Could the form know the defaults to avoid pushing parameters without impact? ie: keeping the URL cleaner
- The new form should be a simple full-screen page. Several users come here from mobile and tablet devices (and TVs)

**Comment by asharonbaltazar** [comment]
That was not the direction I was heading. I suggest that there should be a hook (sorta like the context menu hook) that's responsible for bringing up the form. The form component should live in the clocks' parent component:

```tsx
// Clock.tsx
const [openUrlForm] = useCustomizableUrlForm(/* url form args go here */)

return (
  {/* clock components */}
  <NavigationMenu />
  <FormButton />
)

// AppRouter.tsx
return (
  {/* route components */}
  <ClockCustomisationForm />
)
```
`<ClockCustomisationForm />` will detect any URL changes and open appropriately. Once a user finishes editing the clock parameters, they can push their changes and the form closes. Lemme know if this sounds like something you're looking for.

#### P.S. 

I noticed ` <NavigationMenu />` is being repeated in every clock/timer route. Perhaps it's worth lifting it into the parent component (`<AppRoute />`), where it could live beside `<ClockCustomisationForm />`. 

I haven't studied the component too closely to see whether there's logic that requires it to be in every component, so that's my guess at first glance.
