### ISSUE TITLE
Roll handover to playback

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#400]
Currently, the only way to exit roll mode is to stop the playback.

This means we lose all information as to the current state in the rundown and current playback

We want to build a way to stop **roll** and continue the playback without losing our state.
Ie: instead of clicking **stop** we would click again the roll button, which would internally stop the **roll mode** and set the playback mode to **play**. This should mean that the timer will continue running on the selected event (if any is running)

We would also need to consider what would happen if there are no events running (countdown mode), my inclination is that the playback should move to **stop**

The relevant code is in the `update()` mode of the `PlaybackService`

**Comment by bunday** [comment]
I will pick this up next

**Comment by cpvalente** [comment]
Hi @bunday, any news on your progress? Can I offer some help or clarifications?
