### ISSUE TITLE
Timer Bug when 0 time is left

### ISSUE THREAD

**Issue by 12xx12** [cpvalente/ontime#411]
There is a bug, when the time hits zero. I think this illustrates what Is going on:
```
 0:00:02 (white)
 0:00:01 (white)
 0:00:00 (white)
 0:00:00 (red)
-0:01:00 (red)
-0:02:00 (red)
```
So there is one step too much. It's just one second, but it is there.
The ` 0:00:00 (red)` step is too much.

**Comment by cpvalente** [comment]
Hi @12xx12 , good observation. And thank you again for getting involved. Great to have you
This is not a bug, but it might be that it could be better communicated.

The details go somewhere along the lines:

At every update: Ontime calculates the state of current timer and calls possible registered, side effects. We don't know that this happens at the exact second, but somewhere there about
Back to your example, what actually happens is something like (removed the hours for readability)
```
+00:02.200ms   <---- we call it 00:02 and evaluate it to not overtime, (white)
+00:01.300ms   <---- we call it 00:01 and evaluate it to not overtime, (white)
+00:00.140ms   <---- we call it 00:00 and evaluate it to not overtime, (white)
-00:00.200 ms   <---- we call it 00:00 and evaluate it as overtime, (red)
-00:01.300ms    <---- we call it 00:01 and evaluate it as overtime, (red)
-00:02.050ms    <---- we call it 00:02 and evaluate it as overtime, (red)
```

From the above, we infer that values are clamped down to the closes second, resulting in the behaviour you have notes

This is the normal behaviour for a timer, but I understand it is strange to see a timer of 0 and then red 0.
Perhaps you have some thoughts on how this could be better communicated to the user?
