### ISSUE TITLE
Cuesheet - bad "selected item" visability when items are colored

### ISSUE THREAD

**Issue by Keksstar** [cpvalente/ontime#413]
It´s quite hard to see which item is selected when items are colored. Maybe an frame or similar around it could be added.

I think it´s getting clearer when previous items are greyed out in cuesheets, see #125 

![grafik](https://github.com/cpvalente/ontime/assets/15065206/6f51fbda-f3ba-4037-ac12-d05145406c4e)

**Comment by cpvalente** [comment]
We are currently focusing on getting v2 out, unfortunately cuesheet improvements will not happen until then
This is a tough one, and we will get to it.

**Comment by cpvalente** [comment]
Hi @Keksstar , would you be available to beta test the new cuesheet?

**Comment by cpvalente** [comment]
Handled in #435
