### ISSUE TITLE
Wrong version Displayed

### ISSUE THREAD

**Issue by 12xx12** [cpvalente/ontime#422]
Tested OS: Win10
Ontime Version: v1.10.2

When opening the settings, the wrong version is shown. I just downloaded the newest version, and it shows 1.9.9
I tied global and local installations.

![ksnip_20230531-213232](https://github.com/cpvalente/ontime/assets/44411062/2366d595-15a2-47aa-ad50-c9b889de628e)

**Comment by cpvalente** [comment]
Hi @12xx12 , I appreciate you getting involved.

Ontime is built of 3 apps (packages) 
- a server (the real deal)
- an interface that helps interact with the server
- an electron wrapper that helps with the distribution

in v1, each of these packages has its own versioning
What you see here is the version of the UI, which happens not to be the same version as the distribution


Although I can provide a logical explanation, I agree that this is confusing an unnecessary and it has been corrected in v2
