### ISSUE TITLE
Move App version to new Tab in settings

### ISSUE THREAD

**Issue by 12xx12** [cpvalente/ontime#423]
Usually the app version, copyright, License stuff is displayed in some sort of separate tab in the settings called “About” or similar.
I just tried to find the app version and missed it at the first try.

Maybe add the additional tab?

**Comment by 12xx12** [comment]
Or instead, maybe add an app icon to the top left corner and make it clickable to reveal this information

**Comment by cpvalente** [comment]
Hi @12xx12 , 

Is this related to v1?
This has been fixed in v2. We will no longer push improvements to v1

the [newest beta version is here](https://github.com/cpvalente/ontime/releases/tag/v2.0.0-beta6), I would encourage you to check it out
