### ISSUE TITLE
Cuesheet columns conservative layout

### ISSUE THREAD

**Issue by andry1234-cpu** [cpvalente/ontime#424]
Hello,
thanks for the great work done with this project.
Would it be possible to get a kind of conservative layout for the cuesheet section? 
As soon as I re-arrange my columns, just a refresh is enough to be back to the default layout.

Thank you

Bests

**Comment by cpvalente** [comment]
Hi @andry1234-cpu ,

Thank you for reaching out.

Some `/cuesheet` table options are persisted in the browser
- light / dark mode
- follow selected option
- column order
- column visibility
- column width

This is inconsistent to what I understand from your post. 

I would be inclined to think that there might be something in your browser preventing us from storing the settings.
This could be a security setting (most likely) or you might have ran out of space (less likely)

To help troubleshoot I would need to know:
- which version of Ontime are you using and 
- which OS 
- which browser

You can also check this yourself, 

Chrome instructions (it will be similar enough in other browsers):
- Open the dev tools (ctrl + shift + c in windows)
- navigate to storage
- expand "local storage" on the left navigation
- find the Ontime host and see the contents

See the screenshot as to what it looks here

![table storage](https://github.com/cpvalente/ontime/assets/34649812/a8011900-63b8-4815-910c-eeb6addab385)

**Comment by cpvalente** [comment]
Hi @andry1234-cpu , did you manage to see the issue resolved?
Anything we can follow up with here?

**Comment by cpvalente** [comment]
Closing since we dont have an actionable task here
