### ISSUE TITLE
URL Aliases is it an Alias or a redirect?

### ISSUE THREAD

**Issue by EventReplay** [cpvalente/ontime#429]
Firstly Thank-you for creating a great tool I've rteally enjoyed playing around with it. :)

Is it me not quite understanding how to make this work but I don't seem to be getting how to do a dynamic URL.

If I use my alias it just changes to the Page URL so if I want to actiavte a different view I have to reenter the alias which defeats the object if it unattended.

I'm using the lastest windows 1.10.2 installer on win10. only just seen the beta's

Many thanks in advance for any help.

**Comment by cpvalente** [comment]
HI @EventReplay, thank you for getting in touch

Technically this is an implementation of redirects. perhaps it should have named that way
Ontime holds on to a list of known keys and pushes (redirects) to a given route when it finds it

The implementation for unattended setups is that your route can change without the client doing anything about it
I can see that it might be problematic that the client needs to refresh the browser to see the change.

Personally, we have used this with kiosk setups which contain the alias as starting point. making it easy to refresh. But I do understand that it might not always be straightforward

Is this your use case? If so, do you have suggestions for a possible workflow?

**Comment by EventReplay** [comment]
Hi Thank-you for your prompt replay.

I was trying a senario to switch between the clock and the minimal timer views on an unattended screen that would be a in fulscreen mode!

Not critical just wanted to understand the alias settings!

Note: I tried the beta6 version, with Excel Import I had to change Event URL to Public URL and I couldn't get Message End, End Action or Timer Type to import.
Although I liked the the new Event list look and extra's I did really like the collapse all function on 1.10.2 to give a minimal look to see a lot of info.
Only just got the 1.10.2 look I liked with my little tweaks, so I will need to make some time for the beta as the views looked quite different.

Thanks again for all you hard work I will continue the play! :)

**Comment by EventReplay** [comment]
> Is this your use case? If so, do you have suggestions for a possible workflow?

I was onsite today setting up using OBS & NDi Monitor to relay a Camera feed so I thought I'd have a go using the browser source to show the public veiw as a test instead of a holding slide! Worked brilliant as expected.

On the journey home the mind starts to ponder what if I use an alias?

So:
Create 2 Alias with the same name one enabled one not.
in browser source use Alias
Tick Shutdown source when not visable
Tick Refesh browser when scene becomes active
Then:
Just ensure the scene with the browser source is not visable.
Goto OnTime Swap the two Alias states.
Make the scene with the browser source visable.

I'm pretty sure that could be a one button stream deck press!!!!!

Remote screen would be fullscreen NDi Monitor.

Not perfect but it works. :)

**Comment by cpvalente** [comment]
Good to hear you are finding your way round

**Comment by EventReplay** [comment]
It Looks like my scenario stated above switching between timer & clock is taken care of in v2!!!

If you change between Timer Type clock & coundown in the running event minimal timer view changes :)
Something is not quite right as the clock changes colours linked to timer warning & danger colours!

Stilll playing, I personally would like an option to toggle seconds on/off with the clock.

**Comment by cpvalente** [comment]
Nice,

I am unsure if I follow the issue you describe. Could you provide some screenshots?

**Comment by EventReplay** [comment]
Not so much an issue just an interesting side affect!
If I have an event running set to Timer Type Clock Minimal View will Display just the Clock. The Clock Colour will change as the Timer gets to the warning & danger colours so you go from a white to amber to red Clock!
![Minimal View Clock](https://github.com/cpvalente/ontime/assets/49799927/6d1802a3-445b-4e38-ae31-7d53982a864f)

**Comment by cpvalente** [comment]
Thank you for bringing this up. I will have a look

**Comment by cpvalente** [comment]
Hi @EventReplay is it the case that the minimal view timer has a colour?
The colour here follows the same definitions as the timer that the user adds in view settings

I could not see any issues with styling in clock

Did I understand this correctly?

**Comment by EventReplay** [comment]
@cpvalente 

Yes both Timer & Clock has Colour and it was my assumption that styling was linked!
I was just not expecting the Clock to change Colour.

I can see that could be useful as long as the viewer knows what the colours mean.

As stated above not really an issue just an interesting side affect! I have no issues with clock styling, I would just like an option to toggle on\off seconds. :)

And this is not related to the Alias issue! Sorry for heading of at a tangent.

**Comment by cpvalente** [comment]
> @cpvalente 
> 
> 
> 
> Yes both Timer & Clock has Colour and it was my assumption that styling was linked!
> 
> I was just not expecting the Clock to change Colour.
> 
> 
> 
> I can see that could be useful as long as the viewer knows what the colours mean.
> 
> 
> 
> As stated above not really an issue just an interesting side affect! I have no issues with clock styling, I would just like an option to toggle on\off seconds. :)
> 
> 
> 
> And this is not related to the Alias issue! Sorry for heading of at a tangent.
> 
> 
> 
> 
> 
> 

No problem. I appreciate the time you are putting into helping with this

I believe we might be suffering from unclear naming convention here,

The timer and minimal routes both present the running timer. Those are styled according to the view settings.
The clock view shows the running clock and it should only be styled by the view editor (pencil menu thing)

As soon as this is true, we are good. Any deviations from these would be a bug, even if a small one

**Comment by EventReplay** [comment]
> 
> No problem. I appreciate the time you are putting into helping with this
> 

No problem, I wish I had more time and my coding knowlege was better as I would dive in an try to solve it myself!

Please don't hesitate to ask if you think I could help testing anytime, the least I could do for the use of a great piece of software.

**Comment by cpvalente** [comment]
Help with testing is always welcome. 
Get in touch at mail@getontime.no and mention which industry and role you come from and we can take it from there

**Comment by EventReplay** [comment]
> Help with testing is always welcome. Get in touch at [mail@getontime.no](mailto:mail@getontime.no) and mention which industry and role you come from and we can take it from there

email sent.

**Comment by cpvalente** [comment]
Closing this in favour of a resolution ticket #449
