### ISSUE TITLE
Companion Connection to GetOnTime Problem.

### ISSUE THREAD

**Issue by ShaunMarais** [cpvalente/ontime#434]
Hi Everyone! 

I'm using Bitfocus 3.0.0-rc1. 
I Updated the GetOnTime Module in C:\Program Files\Companion\resources\bundled-modules\getontime-ontime\companion-module-getontime-ontime-2.1.2  from the online [Repository](https://github.com/bitfocus/companion-module-getontime-ontime)

Companion now reads the updated module.
when i enable connection i get the following Status; Unknown Starting...and it doesn't connect.

what am i doing wrong. or rather what steps do i need to follow to get a connection between companion and the OnTime module? 

Thank you,
Shaun

**Comment by cpvalente** [comment]
Hi @ShaunMarais,
thank you for reaching out.

Issues related to the companion module are better suited for the companion repo
https://github.com/bitfocus/companion-module-getontime-ontime

@kellhogs , any tips here?

**Comment by ShaunMarais** [comment]
Thank you. 

I will repost there.

**Comment by kellhogs** [comment]
@cpvalente took the conversation over to the Companion repo. Can be closed here i think.
