### ISSUE TITLE
Keep original destination on redirect

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#449]
It has been pointed out in #429 that the URL Aliases feature uses a redirect in its implementation
That means we lose our original destination once the page is entered. If the editor were to change the URL we would need a refresh on the view client to re-resolve the alias.

URL Aliases has two target specifications:
1. Simplify long URLs
2. Allow remote control of unattended clients

This is a bug on the second point

### The task
Fixing the bug would take two steps:

1. Maintain the original alias
2. Periodically check if this has changed and redirect

### Implementation details

I would suggest that **maintaining the original** alias could simply be done by injecting a parameter in the URL (eg: `localhost:4001/timer?from=my-alias` once the [URL is resolved](https://github.com/cpvalente/ontime/blob/master/apps/client/src/AppRouter.tsx#L45)
Alternatives using local storage or react state could also be considered if it improves reactivity on step 2

As for **knowing the alias has changed**, we would either likely need to attach a listener to the [parameter in the store](https://github.com/cpvalente/ontime/blob/master/apps/client/src/common/hooks-query/useAliases.ts)
Once we know **if the alias has changed**, we can check the stored value from point 1 to see if the current destination is affected

**Comment by bunday** [comment]
I can look into this
