### ISSUE TITLE
Clock stops at midnight

### ISSUE THREAD

**Issue by baggytrowsers** [cpvalente/ontime#455]
I'm unable to run the clock over midnight. It keeps stopping at 11:59:59. It's running on a headless raspberry pi with a RTC module.

**Comment by cpvalente** [comment]
Hi @baggytrowsers, thank you for bringing this to our attention.

Can you please give more details as to what you are experiencing?
- Do all the timers stop? is it just the clock?
- Are you running in docker? Do you see any errors in the terminal?

We are not aware of any issues with midnight, but will create a patch ASAP if we can reproduce it

**Comment by baggytrowsers** [comment]
I'm not running any timers. Just the default clock. It's running in a docker as per instructions. No errors that I can see (but I'm not great with terminal.)

What's weird is that after midnight when it stops, I can manually refresh the page and it will display the current time, but it doesn't continue counting through the seconds. It will just show the fixed time at the time of the page refresh. The only way it will work again is if I reboot.

**Comment by cpvalente** [comment]
I have found the issue and it will push a patch fix later today

Thank you again for bringing this up
