### ISSUE TITLE
Entering start and end times mixes 12h and 24h

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#46]
enter 15:00:00 as time. it shows as 03:00:00 and then back again to 15.. when enter is pushed.
Selecting the same time shows 03.. again.
![image](https://user-images.githubusercontent.com/25690871/143678461-683cb411-ab0b-42d9-9b62-de84e31cda8e.png)
![image](https://user-images.githubusercontent.com/25690871/143678479-b6442795-80ff-47a4-87b3-272205203925.png)

also entering 00:00,   12:00, anything 20+ buggs out. probably related. and the drop downs to enter time are a bit weird :)

version. downloaded today

**Comment by xztraz** [comment]
i thing 24h time should be standard if it is not an option to select 12h/24h.

**Comment by cpvalente** [comment]
I see, I managed to recreate the issue by setting my system time to 12 hour format (AM/PM)
I dont think any of the testers here use AM/PM and this was poor oversight, let me have a look if I can push a quick fix

**Comment by xztraz** [comment]
i use 24h as system time(win7) so thats a bit weird

**Comment by cpvalente** [comment]
Fixed with 627cce7, although it remains a mistery where did the 12 hour format came from in this specifc case.
Will leave it open for now and close if there is no further activity in this issue

**Comment by xztraz** [comment]
This works now. (installed whats built now.)
only thing i could miss is if you want to enter a time fast and just hit the box and enter 12 for example. and hit enter. (to enter 12:00:00) but its entered as 00:00:12 can the input be right filled with 0 instead of left filled. also if you don't enter : maybe that can be filled in automatically?.   so say you want to enter 15:45:00   just hit box. enter 1545 enter.

**Comment by xztraz** [comment]
original issue resolved and tested. Great!
