### ISSUE TITLE
name missmatch presenter/speaker

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#47]
controll gui:
![image](https://user-images.githubusercontent.com/25690871/143678724-dfa8aa43-c272-4b14-a63c-15be020d4c1c.png)

web links (under the icon)
![image](https://user-images.githubusercontent.com/25690871/143678739-68598438-514c-4c13-8636-55bbb20dea98.png)

**Comment by cpvalente** [comment]
This is well observed and been on the developer notes for a while, originally came from the fact that everyone involved works in different fields.
I think we should try to unify this by deciding the name of the viewers and pushing throughout.

The main idea is that there are two types of screens
Public and Backstage

Do you have an opinion on naming convention here?

**Comment by xztraz** [comment]
i don't mind either name for it as long as it is the same :)  since you use presenter in other places (timecards) that might be easiest to change to that

**Comment by cpvalente** [comment]
Fixed with #60, will leave it open for a while in case there are follow ups
