### ISSUE TITLE
Compiled 2.2.12 for Windows installs the old 2.0.9 version 

### ISSUE THREAD

**Issue by andry1234-cpu** [cpvalente/ontime#472]
Hello everyone, 
as said in the post title, installing the 2.2.12 precompiled package on Windows does install the old version 2.0.9.

**Comment by cpvalente** [comment]
> Hello everyone, 
> 
> as said in the post title, installing the 2.2.12 precompiled package on Windows does install the old version 2.0.9.
> 
> 

Hi @andry1234-cpu , thank you for bringing this to my attention

It looks like I missed some steps on creating the latest release.
The 2.2.12 install is indeed up to date, just fails to report so.

This will be corrected with the next release

**Comment by andry1234-cpu** [comment]
> > Hello everyone,
> > as said in the post title, installing the 2.2.12 precompiled package on Windows does install the old version 2.0.9.
> 
> Hi @andry1234-cpu , thank you for bringing this to my attention
> 
> It looks like I missed some steps on creating the latest release. The 2.2.12 install is indeed up to date, just fails to report so.
> 
> This will be corrected with the next release

Oh, thank you for the info. 
Have a nice day everyone

**Comment by cpvalente** [comment]
This has hopefully been resolved with the newest release
