### ISSUE TITLE
warning popups white text on yellow backgroung hard to read.

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#49]
popups if entering times wrong results in a popup that is having a bit to low contrast to read. 
![image](https://user-images.githubusercontent.com/25690871/143912140-736bc907-be38-4fac-b374-888ede58b868.png)
something more intuitive would be to change the color of the boxes with offending times.
something like
![image](https://user-images.githubusercontent.com/25690871/143912949-5a6e4114-a301-447f-a23f-ec359dddcc00.png)

But the question rises. what do you do if you want an event that stretches over midnight?

**Comment by cpvalente** [comment]
Thank you again for your great input. It is great working together to improve the app

As part of the initial design there were a few decisions made towards enforcing as little of a workflow as possible

This included not being too particular about times. This means you can use ontime as an event rundown tool by adding a schedule to the event list. Or use it as a simple stage timer tool by creating reusable timers such as
00:00:00 -> 00:10:00 (10 minute timer)

Onto your suggestions

> popups if entering times wrong results in a popup that is having a bit to low contrast to read.

- All user feedback will eventually move into the Info component in some sort of system logger. This aims to be less intrusive and help with debugging of other parts of the system (specifically with integrations). 

> But the question rises. what do you do if you want an event that stretches over midnight?

- All times over 00:00:00 are considered to be over midnight. Similarly, all events ending before the event before finishes, are considered to be in the next day. This means that the maximimum event lenght is effectively 23:59:59. Do you have an example of a workflow where this is not working for you? I am happy to take a look.

**Comment by xztraz** [comment]
> * All times over 00:00:00 are considered to be over midnight. Similarly, all events ending before the event before finishes, are considered to be in the next day. This means that the maximimum event lenght is effectively 23:59:59. Do you have an example of a workflow where this is not working for you? I am happy to take a look.

That sounds as it should be! but i guess you still get a warning if end time is "before" start time. as could happen if an event stretches over midnight. otherwise the plan with a info logger/debug sounds like a great way for in depht errors.

**Comment by cpvalente** [comment]
The warning doesn't really fail the field. Is lot is just meant as a friendly warning so you can double check your entry.

You can confirm this by seeing that time timer is calculated correctly as going past midnight

**Comment by cpvalente** [comment]
No longer in use since logger in #81

**Comment by xztraz** [comment]
much better! rc5+log
