### ISSUE TITLE
Shortcuts should match OS

### ISSUE THREAD

**Issue by asharonbaltazar** [cpvalente/ontime#492]
Shortcuts, like the one at the bottom of `/editor`, should correspond to the OS the user is on. It'd would make the UI less confusing for users on different operating systems.

The `QuickAddBlock` displays `Alt + E` to add a new event. On MacOS, it should be `option + E`.

**Comment by cpvalente** [comment]
Agreed! Thank you for the initiative @asharonbaltazar

**Comment by asharonbaltazar** [comment]
I'm sorry if I wasn't clear in the original issue writeup, but the only problem is the labels. If a user is working with a MacOS computer, it might be confusing for them to see shortcuts that don't exist on their keyboard (alt vs option).
We should handle the differences in labels — that's all. Functionality still works great!
