### ISSUE TITLE
hoover help on some buttons missing

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#51]
Hoover help is awesome for quick hints what a button does and some have it and some are missing it.
all buttons and boxes here are missing hoover texts. for example.
![image](https://user-images.githubusercontent.com/25690871/144422054-30f23712-3eae-4447-b180-85cafc8c223a.png)

Some text suggestions:
![image](https://user-images.githubusercontent.com/25690871/144422348-414466f9-41b0-44f3-8986-2b6c058a82a1.png)
Show overlay message to <X> / Hide overlay message to <X>

![image](https://user-images.githubusercontent.com/25690871/144422542-9c6e657f-c8c5-413b-a051-149283864870.png)
Run events synced to clock.

![image](https://user-images.githubusercontent.com/25690871/144422911-c32bdca0-7479-4bca-b363-f1696c296ff8.png)
Run selected event

![image](https://user-images.githubusercontent.com/25690871/144422977-3b2463ac-c013-4944-a3b6-0315ede04bbc.png)
Pause

![image](https://user-images.githubusercontent.com/25690871/144423044-f27d8dff-1d7b-483b-b2e7-77396ae7b6d0.png)
Stop run (maybe a square stop symbol instead?)

![image](https://user-images.githubusercontent.com/25690871/144423276-dc98b52b-3a1d-4e50-a8f8-1915aa806583.png)
Jump to Next/Prev post

![image](https://user-images.githubusercontent.com/25690871/144423353-488e7209-8059-4085-87f9-de0ca4d1a236.png)
I have no idea what this button does?

![image](https://user-images.githubusercontent.com/25690871/144423441-f47ecf35-5237-4c9d-a25e-f949d67ad6bf.png)
Add / Remove post.   (remove might need some confirmation or undo function)

Some hoover help on a block would be great too. what does a block do.

**Comment by cpvalente** [comment]
I believe this should be part of a bigger issue. See  #54

**Comment by xztraz** [comment]
trying the buttons now to 

> > ![image](https://user-images.githubusercontent.com/25690871/144423353-488e7209-8059-4085-87f9-de0ca4d1a236.png) I have no idea what this button does?
> 
> That is a reload button. It will reload the currently selected event. effectively pausing playback and resetting timer

The icon feels like a repeat symbol. could it be something more like a back or undo arrow?

also if you'we pushed stop. why not make the play button not grayed out and if pushed starts on the first post if nothing is selected?

**Comment by xztraz** [comment]
![image](https://user-images.githubusercontent.com/25690871/144589872-15d132e7-8b9b-41f8-a3cc-1df83c7f0224.png)
could be something like this maybe?
![image](https://user-images.githubusercontent.com/25690871/144590404-381dd1fa-cc9a-481b-92e9-8410d4c18097.png)

**Comment by cpvalente** [comment]
Some of these were implemented with #88 
Will leave the issue open as I will probably revise some of the icons in upcoming issues

**Comment by cpvalente** [comment]
Closing this since there hasnt been activity since the last fixes
