### ISSUE TITLE
Ontime window does not launch in local builds

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#510]
When the app is packaged inside electron, it is electron's responsibility to start all the processes.
From electron's perspective, it goes something like

1. Open preload window
2. Start Ontime server (returns a port indicating where to find the server)
3. Close the preload window and open a window with the UI build served at the given port

It seems that the app gets stuck somewhere between step 2 and 3.
The server process is started by the preload window is never closed but the server is available

It is puzzling that the pipeline builds work well.
The only apparent difference is the inclusion of the local environment variable

This bug was likely introduced by the changes in #476 

We are likely calling the backend at the wrong place. A good place to start is the handling of the backend start call
https://github.com/cpvalente/ontime/blob/master/apps/electron/main.js#L159

**Comment by cpvalente** [comment]
@pSnehanshu do you have availability to take a look?

**Comment by pSnehanshu** [comment]
Hi, sorry I don't have availablity at the moment.

**Comment by Enubia** [comment]
I tried to reproduce this issue but was not fully able to.
What I encountered is that electron apparently does not work properly with linked dependencies from `pnpm`. I had to install the electron directory with `npm` after pnpm linked its stuff and running `npm run dev:electron` works fine with the server and client running locally as can be seen here

![image](https://github.com/cpvalente/ontime/assets/44695100/dc1e9fe6-cd88-4575-bd3f-4e5db54a99d9)

What doesn't work is running the electron app in production mode locally since there seems to be issues with the environment setup

**Comment by cpvalente** [comment]
Hi @Enubia, these are interesting findings.

It could well be that I am doing something locally that is not well communicated in the documentation.
Can you provide some more context to what you experienced?

How did you install dependencies?
which directory are you calling the command from?
what errors did you see? did nothing install or just the shared stuff?

**Comment by Enubia** [comment]
What I initially did was install the dependencies via pnpm. I then attempted to run the electron app but it failed because the electron executable could not find it's framework dependencies.
After this I purged all node_modules folders and installed the deps via npm which resulted in no hard linked dependencies anymore. This did let me run the electron app but only in local mode, so with a running server and UI.

This whole setup was done on my Mac M1 chip.

For some reason I'm not able to reproduce this behavior on my windows machine via WSL. On windows it won't launch at all.

Differences between those two are:

- pnpm version mac: 7, windows wsl: 8
- node version mac: 16, windows wsl: 18
- npm version mac: 7ish (cannot verify this right now but it should be the default one in node version 16), windows wsl: 9

**Comment by Enubia** [comment]
> which directory are you calling the command from?

the `npm run dev:electron` command was executed in the `apps/electron` directory since the turbo config commands are not in line with the root package.json.

**Comment by Enubia** [comment]
> What errors did you see? Did nothing install or just the shared stuff?

This is the interesting part

It did show the framework dependencies not found error during the initial try.
When I attempted to run it in production mode, the app wasn't able to locate the client index.html file although the whole build directory was created before via `npm run build:local`.

So something seems to be off path-wise when you attempt to run the app in production mode. I did not dig into this further as I thought it was not worth the effort for now.

**Comment by cpvalente** [comment]
Testing it right now with Windows and WSL in a bash terminal

- I delete all node modules from the root
- `pnpm i` from root and see a `Scope: all 6 workspace projects` messages

if I now navigate to apps/electron/node_modules i see the dependencies installed (electron, electron-builder ...)
- running `pnpm dev:electron` from this directory starts electron 

at which step do results differ from you?

**Comment by Enubia** [comment]
```sh
❯ pnpm install                                                                                                                                                                             ontime/git/master 
 WARN  Unsupported engine: wanted: {"node":"~16.16.0"} (current: {"node":"v16.17.0","pnpm":"8.7.6"})
Scope: all 6 workspace projects
 WARN  2 deprecated subdependencies found: asar@3.2.0, electron-osx-sign@0.6.0
Packages: +989
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1011, reused 985, downloaded 0, added 989, done
apps/client postinstall$ pnpm addversion
│ > ontime-ui@2.9.0 addversion /Volumes/Workspace/git/ontime/apps/client
│ > node -p "'export const ONTIME_VERSION = ' + JSON.stringify(require('../../package.json').version) + ';'" > src/ONTIME_VERSION.js
└─ Done in 321ms
apps/server postinstall$ pnpm addversion && pnpm setdb
│ > ontime-server@2.9.0 addversion /Volumes/Workspace/git/ontime/apps/server
│ > node -p "'export const ONTIME_VERSION = ' + JSON.stringify(require('../../package.json').version) + ';'" > src/ONTIME_VERSION.js
│ > ontime-server@2.9.0 setdb /Volumes/Workspace/git/ontime/apps/server
│ > shx cp ../../demo-db/db.json src/preloaded-db/db.json
└─ Done in 869ms

devDependencies:
+ @playwright/test 1.34.3
+ @types/node 18.11.18
+ @typescript-eslint/eslint-plugin 5.48.0
+ @typescript-eslint/parser 5.48.0
+ cross-env 7.0.3
+ eslint 8.31.0
+ eslint-config-prettier 8.6.0
+ eslint-plugin-playwright 0.12.0
+ prettier 2.8.2
+ turbo 1.8.8
+ typescript 4.9.4

Done in 26.8s
❯ cd apps/electron/                                                                                                                                                                       ontime/git/master !
apps/electron❯ pnpm run dev:electron                                                                                                                                                      ontime/git/master !

> ontime@2.9.0 dev:electron /Volumes/Workspace/git/ontime/apps/electron
> NODE_ENV=development electron .

dyld[6471]: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: <4C4C4479-5555-3144-A168-D52060D6B51E> /Volumes/Workspace/git/ontime/node_modules/.pnpm/electron@22.3.5/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
  Reason: tried: '/Volumes/Workspace/git/ontime/node_modules/.pnpm/electron@22.3.5/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Volumes/Workspace/git/ontime/node_modules/.pnpm/electron@22.3.5/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/Electron Framework.framework/Electron Framework' (no such file), '/Volumes/Workspace/git/ontime/node_modules/.pnpm/electron@22.3.5/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Volumes/Workspace/git/ontime/node_modules/.pnpm/electron@22.3.5/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file, not in dyld cache)
/Volumes/Workspace/git/ontime/node_modules/.pnpm/electron@22.3.5/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGABRT
 ELIFECYCLE  Command failed with exit code 1.
```

this is what happens when I do the exact same steps as you did with pnpm

**Comment by cpvalente** [comment]
Hi @Enubia , I have just recreated the exact same steps without issues.
While this is not a lot of help, my first thought would be to resolve the error in the first line

>  WARN  Unsupported engine: wanted: {"node":"~16.16.0"} (current: {"node":"v16.17.0","pnpm":"8.7.6"})

While I doubt that a minor version in node makes a difference, you are using an entire major version over the project in pnpm
You could try migrating the project to pnpm 8 and seeing if it resolves the issue.

If we are to upgrade pnpm, I would prefer that we do it in a separate PR. I have done it in several projects without finding an issue.

**Comment by alex-Arc** [comment]
the problem might be that 
one runs `pnpm build:local` for testing the cli but this builds the index.ts from the server not app.ts that electron expects 
but both are named index.cjs in the server/dist so there is no way to notice

some clear script names could maybe be good or just fixing the DEVELOPMENT.md
