### ISSUE TITLE
Display of the planned duration as time scale bar in Ontime-App

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#513]
During the planning and implementation of events, more and more often comes the question, which event-part consumes the most time in order to get easily clear time from it for another event-part.

Maybe there is way to show just a thin color bar of each event-part, representative for the duration with the max. value of all event-parts as max. value.

This would give the event manager very quickly the answer which event-part consume how much time for any kind of replaning the event.

thank you

**Comment by cpvalente** [comment]
Hi @iqtreiber, thank you for your continued involvement
This sounds great and could potentially help us communicate the running vs scheduled time. 

Can you provide a rough sketch of what this might look like?
In which view(s) is this present?

**Comment by iqtreiber** [comment]
I have painted a kind of mockup which is not very beauty but shall show the request about "duration bar".
In my opinion only in the Ontime App (Admin App) should this bar displaying.
>> helping the main admin and client to managing "speaker slots" for the event.

<img width="1409" alt="Phase 1" src="https://github.com/cpvalente/ontime/assets/9744544/fe4baa9f-de85-44dd-8da3-ecf2091895bb">

**Comment by cpvalente** [comment]
Hi @iqtreiber, I understand the value of this, but would this not be better served by your other suggestion in #514 

From my perspective, the other option seems to provide better overview and is also easier to implement

**Comment by iqtreiber** [comment]
Hi @cpvalente 

Yes correct #514 shall be a part 2 of #513 part 1, as I thought it might be needed to split in two parts.
But of course the 100% value has #514 when both parts are available.

BR Stefan

**Comment by cpvalente** [comment]
Hi @iqtreiber , we really like the suggestions in #513 but feel this is maybe a step outside of the roadmap of the application

**Comment by iqtreiber** [comment]
Hi @cpvalente, no problem as long as #514 will get alive we can close this issue #513.
Is there any estimated time schedule for #514 ?

**Comment by cpvalente** [comment]
> Hi @cpvalente, no problem as long as #514 will get alive we can close this issue #513.
> 
> Is there any estimated time schedule for #514 ?

#514 is very much in line with what we want for the app. So it will happen

We are currently working on the over - under calculation. As we spoke before, this is made slightly tricky by how ontime rundown is made 

Once we have found a good way we will work on the presentation.

Since this is a busy time of the year, I wouldn't expect the first phase to be done on this side of the year
