### ISSUE TITLE
Predefined speaker messages for speaker-view

### ISSUE THREAD

**Issue by iqtreiber** [cpvalente/ontime#515]
Based on the already existing issues towards companion, here is the request for an independent, direct solution in the Ontime app.

https://github.com/bitfocus/companion-module-getontime-ontime/issues/26

Would it be possible to create a few predefined messages in the basic configuration of the Ontime app, which can then be selected and executed via a select box?

thank you

**Comment by cpvalente** [comment]
Can you expand on how this would work?
Do these get saved in your project file? how many of these do you get?
is this list available for all screens? are the lists different for each screen type?

If we get some clarification, it might be that it takes part of some future improvements to the message feature. 
However, at this moment, there is no planned work on this area for the near future. This is unlike to change unless users feel strongly that this should be a priority in the roadmap

**Comment by iqtreiber** [comment]
Based on the last events, we were dealing with around 3-4 known, repeating "messages".
We copied these 3-4 known between txt file and Ontime and rolling.

I am not a developer but from the operating handling it's very similar to the "timer end message".
As far as I know the "timer end message" is part of the project settings.
We are only using this messages for the speaker on the stage /stage-view

I have been paint two mockups - which maybe a way of solution.

![image](https://github.com/cpvalente/ontime/assets/9744544/203e278f-5006-4c6a-96b8-61decdef2e36)

<img width="660" alt="Bildschirmfoto 2023-09-15 um 14 20 43" src="https://github.com/cpvalente/ontime/assets/9744544/d0f2d73d-4f39-418f-a112-af86fb2a58d9">

**Comment by alex-Arc** [comment]
Its a good function but
This can easily be accomplished in companion (example available in the companion issue)

**Comment by iqtreiber** [comment]
This issue/request continue at companion-module.
https://github.com/bitfocus/companion-module-getontime-ontime/issues/26

This issue can be closed.
