### ISSUE TITLE
Edit user fields from operator view

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#516]
### Context
The `/operator` view is a readonly list of the rundown.
In addition, the user can subscribe to a `userField`, which will be displayed along with the event information

We would like to add the ability for the users to update the data in this user field.

### The task
The suggested implementation is to add a press-and-hold action on the `OperatorEvent` entry that shows a modal with a text input. Submitting a value here should update the relevant user field

We would also like a way to improve visibility of the feature, perhaps we can show a message on scroll "press-and-hold to edit userfield", this should only be shown while the user is scrolling and  if there is a subscribed user field

**Comment by cpvalente** [comment]
Having second thoughts on this. I fear this might open the gates for a lot of wanted customisation.
Would it be best to leave this as lean as possible?
@Punkerschaf

**Comment by Punkerschaf** [comment]
I totally agree with you. What would be the leanest form?
Press and hold to edit the selected user field is a direct way I think. This doesn't need space for a new button.
If there is no user field selected, the edit function is just not available.
The information about this function could appear in the customisation menu.
This seems pretty straight forward to me. Did you have a smaller variant in mind, @cpvalente ?

**Comment by cpvalente** [comment]
Hi @Punkerschaf, I have made a prototype with clicking on an entry to edit its userField.

I am wondering whether there are any curve balls in future that would complicate this feature.
If we can agree that this is a complete feature set that we would not need to extend I am happy with it.

From the top of my head, the only conflicting request we got was to be able to subscribe to multiple user fields, what do you think?

**Comment by Punkerschaf** [comment]
@cpvalente , I understand what you mean. From my side I'm totally fine with only one editable user field. Like there is a primary field and any more as multiple subscription are read-only. When I have to edit multiple user fields I rather use cuesheet anyway. 

If other ontime users whish this feature to be more flexible, I only see to change the text edit into a modal with selection buttons on top to change the field to edit. But in this case, the suggestions of them remain to be seen. I don't have a smarter idea for this either.

**Comment by cpvalente** [comment]
Sounds good, @Punkerschaf are you able to run ontime locally directly from the repo?
We have a PR #609  which would be great to have some feedback on. Otherwise we will wait for next release 🤞 

You might also be interested in #605

**Comment by Punkerschaf** [comment]
Thanks for involving me this way, @cpvalente .
I've never done this before since I only running some python script. At the moment I'm struggling just with running the npm script for dependencies. But I think this is a MacOS problem or of my junked up beginners dev enviroment.
I try to fix this; till this I wait for the release and reading the PR's comments.

**Comment by cpvalente** [comment]
No worries @Punkerschaf , feel free to reach out and I can help you.
the hard part is setting up node and pnpm, from there everything is automagic

the setup here is not unique to ontime, so you can look for instructions in another (better documented) app 😅

**Comment by viktorfreiman** [comment]
@cpvalente is there a option to have the operator view readonly again? I have found with some people with touchscreen that missclick when scrolling. I am thinking of having a globol setting on/off

**Comment by cpvalente** [comment]
Hi @viktorfreiman, such option doest currently exist. 
I will make a change to add it
