### ISSUE TITLE
OSC?

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#52]
OSC is mentioned a lot but is that Open sound Controll or something else? some hint of what it is in the gui and help would be great :)

**Comment by cpvalente** [comment]
Exactly, OSC stands for Open Sound Control.
As it isnt integral to the operation of the App I will leave it mostly documented over at [gitbook](https://cpvalente.gitbook.io/ontime/control-and-feedback/osc).

This is a good point though to increase clarity in the interface. Perhaps moving the OSC related stufff to an integrations tab and adding links to documentation in app. Will move into a overarching issue

**Comment by xztraz** [comment]
i just didn't find what OSC stood for. what software you where trying to talk to. so just write the full name somewhere :) settings page would be a good place. 
![image](https://user-images.githubusercontent.com/25690871/144581129-487e7104-a316-46af-8143-81b847123f0c.png)

**Comment by cpvalente** [comment]
Implemented and released with #81

**Comment by xztraz** [comment]
verified: 
![image](https://user-images.githubusercontent.com/25690871/148130137-3530efa8-15c0-4332-920a-8a56e25e0018.png)
