### ISSUE TITLE
Selected text boxes changes corner radius

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#53]
comparing unselected and selected shows a bit different corner radius. this is not a biggie :) but something feels a tiny bit off when selecting boxes. 

![image](https://user-images.githubusercontent.com/25690871/144426847-cf42477d-a904-481e-b3d5-26fd30de8d1d.png)

![image](https://user-images.githubusercontent.com/25690871/144427166-54d41ce1-9dcf-475d-9692-cba20b2d81ce.png)

**Comment by cpvalente** [comment]
Adding this to a bigger issue about interface improvements #55 
If many style issues arise I could make a new issue with that in scope

Leaving the issue open for documentation

**Comment by xztraz** [comment]
it was a tiny thing :) tried to find the corresponding css but hard if i can't inspect in a browser

**Comment by xztraz** [comment]
opps wrong button :D

**Comment by cpvalente** [comment]
Fixed with #95
