### ISSUE TITLE
Roll mode: SMPTE/MTC Timecode

### ISSUE THREAD

**Issue by MilkMGN** [cpvalente/ontime#535]
Would it be simple to add to use an audio input and take in timecode to base events off in roll mode? 

Could even then use the system clock and figure out what time events are going to happen within the current timecode cycle

**Comment by cpvalente** [comment]
Hi @MilkMGN , thank you for reaching out.

Adding some sort of timecode integration is something we would like do, we also we have a similar request for adding a MTC output from ontime time #227 

However there is some investigation to be done, and several caveats to consider. I would welcome help on this task.

Personally, I would prefer a MTC or some network time integration, it would be interesting to see what companion does and which protocol would have the least friction in integration

**Comment by MilkMGN** [comment]
Hey @cpvalente , 

I have a friend willing to look into making a branch for this, whether through SMPTE or MTC. For my event i'm planning to use this in we need SMPTE, so we may chip away at that. 

Thanks for your reply, i look forward to possibly making this work.

**Comment by je71175** [comment]
Also if you want to look at another external platform Chataigne is a great intergrator for multiple platforms and systems.  http://benjamin.kuperberg.fr/chataigne/en#download
Have been using external platforms with OSC to trigger onTime events.
But I do like the idea of having TimeCode (we would use MTC) native in onTime.  
cheers Jason

**Comment by alex-Arc** [comment]
@pbl4845, @je71175, @MilkMGN 
Hey all sorry to ping you like this
I am working on a MTC prototype and could use some help testing if you are stile interested

**Comment by alex-Arc** [comment]
@viktorfreiman there is also a NTP option

**Comment by viktorfreiman** [comment]
Hi guys, I have just got LTC from Audio device working. Here is a working demo. https://github.com/viktorfreiman/audio-demo
I tried to get it to work with ontime but I had some problems with getting pnpm and turbo working.
If anyone is up to rework it and getting it upstream would be awesome.

@MilkMGN I am also doing a show with LTC.
I working with lights so my fallback to get it working is to use my light console, grandMA3's LTC input and then send OSC cues to bitfocus companion to have it track with ontime.

**Comment by je71175** [comment]
happy to help with testing. 

> @pbl4845, @je71175, @MilkMGN Hey all sorry to ping you like this I am working on a MTC prototype and could use some help testing if you are stile interested

**Comment by alex-Arc** [comment]
> Hi guys, I have just got LTC from Audio device working. Here is a working demo. https://github.com/viktorfreiman/audio-demo 

supper cool that you got something with LTC working, I looked in to it and could not find anything that handled real-time
i will see if i can add it

**Comment by BenjMoore** [comment]
> @pbl4845, @je71175, @MilkMGN
> Hey all sorry to ping you like this
> I am working on a MTC prototype and could use some help testing if you are stile interested

That would be much appreciated, ill post in this thread once ive had a look

**Comment by alex-Arc** [comment]
there is something here to try out
https://github.com/cpvalente/ontime/tree/feat-clock-source
the UI is a bit scuffed and you need to restart to make them take effect

**Comment by alex-Arc** [comment]
hey @viktorfreiman the build chain for audio seams a bit complex
https://github.com/bitfocus/libltc-wrapper requires node-gyp
https://github.com/almoghamdani/audify requires a C/C++ compiler toolchain 
I don't know if that is something we can easily add without making it very difficult for people to build and contribute
@cpvalente any thoughts on this?

**Comment by MilkMGN** [comment]
Hi all,

Me and @BenjMoore will be looking into this today.

**Comment by cpvalente** [comment]
> hey @viktorfreiman the build chain for audio seams a bit complex
> 
> https://github.com/bitfocus/libltc-wrapper requires node-gyp
> 
> https://github.com/almoghamdani/audify requires a C/C++ compiler toolchain 
> 
> I don't know if that is something we can easily add without making it very difficult for people to build and contribute
> 
> @cpvalente any thoughts on this?

I believe we shouldn't be trying to get so much working at once. The task now should be to be able to add one external source of time.

Once the feature is stable and has proved value we can try to move forwards. I would suggest starting with an NTC as it has little friction for implementation and I believe provides the most value to our users 

When it comes to MIDI we can look into companion for inspiration, ontime and companion tech stack is very similar.

**Comment by alex-Arc** [comment]
here is a windows build https://www.dropbox.com/t/b40MRzzRZQT00HkR

To use MTC set the source to MTC and enter the name of the midi device you what to use then restart ontime
![image](https://github.com/cpvalente/ontime/assets/19875125/ddb780e9-4331-436e-bc47-ad55778d9225)

To use NTP set the source to NTP and enter a comma separated list of NTP servers then restart ontime
![image](https://github.com/cpvalente/ontime/assets/19875125/bca0d7f7-0d41-4d55-891a-09af46654808)

**Comment by viktorfreiman** [comment]
Hi @alex-Arc 

I have tried to get MTC working but without any luck.
When I press roll mode I get: 
`WS IN: TypeError: Cannot read properties of null (reading 'id')`

I think if ontime has never got any MTC the clock should be at 00:00:00.
The clock should pause if the MTC stops.

I am using TimeLord (It's the only free solution I have found for windows) to generate MTC
and it works with piXtimecode.
https://timelord-mtc.com/
https://www.microsoft.com/sv-se/p/pixtimecode-monitor/9mt05f4n77xz

![fFyYAApdwn](https://github.com/cpvalente/ontime/assets/46821238/e51b7d5f-6c4a-40fa-864b-e8a90610f549)
![M2BOZK19X3](https://github.com/cpvalente/ontime/assets/46821238/d90bba6a-e8f2-4192-9916-8f82f2bcd6b1)

**Comment by alex-Arc** [comment]
Hi @viktorfreiman 
I think that error is actually form roll mode without any public events, It is fixed in the master brach.
Dose it work if you set that event to public

Reaper can also generate MTC and LTC

**Comment by viktorfreiman** [comment]
If I set the Event to public in it's setting tab I don't see the error from before. But it still did not work.
The clock starts but takes it from system time.

BTW I found a python project that generates mtc.
https://github.com/viktorfreiman/timecode_tools

**Comment by alex-Arc** [comment]
my bad
there was a bug forcing it to use NTP

here is a new build with it fixed
https://www.dropbox.com/t/xL6voLTnWaEJkyMn

**Comment by viktorfreiman** [comment]
@alex-Arc I have now tested your latest build and it works good with MTC
![y0fQP7V5pl](https://github.com/cpvalente/ontime/assets/46821238/2eb75569-24d4-4e56-9c62-08259d5172e3)

Is there a timeframe if/when the NTP/MTC patch will go in to main branch?

BTW I am working a script to realtime convert LTC to MTC

**Comment by alex-Arc** [comment]
@viktorfreiman Good to see that you got it to work. We can't promise anything time wise, sorry.
Is it behaving as you expected? (not free running and so one)
Is there any edge cases you foresee?

**Comment by viktorfreiman** [comment]
@alex-Arc Yea right now it works as expected and the clock stops when the MTC stops.
It feels like there is a delay ~0.3s-0.5s between ontime and what piXtimecode shows but I see it as a non-issue.
I just want to setup on a laptop and have it run on input.
I will do some more long time testing with it and I will update how it goes.

**Comment by viktorfreiman** [comment]
I have found a bug.

When I play the MTC of a previous event it does not jump back to the currect event.
The clock is currect but I need to stop roll mode and start it again to make it jump back.

It works good when going forward.

BTW I have now a working realtime ltc2mtc converter in node https://github.com/viktorfreiman/audio-demo/blob/main/ltc2mtc.js
Thx @alex-Arc your mtc reader code helped me alot with getting the bits right

![explorer_BUXiAZBz39](https://github.com/cpvalente/ontime/assets/46821238/7efb0e7d-6682-4b14-87e0-7429964bab34)

**Comment by alex-Arc** [comment]
@viktorfreiman thank you very much for the report :)

**Comment by alex-Arc** [comment]
@viktorfreiman I had some problems with skipping frames 
so depending one how much of the decoding logic you used, you might want to take a look at this new version
https://github.com/cpvalente/ontime/pull/584/commits/f517a31d23a5dc978ad08e87ef6af44f29b04689 
also switch to https://www.npmjs.com/package/@julusian/midi from who we know to be reliable

**Comment by viktorfreiman** [comment]
Thanks @alex-Arc for the tip, will definitely check it out. Is it possible to get a new windows build with your latest commits?

**Comment by alex-Arc** [comment]
sure, I will try to get something to you after the skip back stuff is fixed

**Comment by cpvalente** [comment]
Hi @viktorfreiman, jumping in here for a quick question. is there anything we could do to help users like you being able to make your own builds of the apps?

I am happy to clarify the documentation if needed
https://github.com/cpvalente/ontime/blob/master/DEVELOPMENT.md

**Comment by MilkMGN** [comment]
Hi @viktorfreiman We're running into quite a few issues gettubg tge MTC beta to work. MTC is coming in over rtpMIDI and the output is set to the device that uses. Tried also using a loopMIDI port as well but no dice. Any ideas/ a guide on how to set it up?

**Comment by alex-Arc** [comment]
Hey @MilkMGN are you trying out ontime or Viktor's ltc->mtc converter?
if it is Ontime for now a restart after changing the clock settings

**Comment by viktorfreiman** [comment]
@MilkMGN I am working on documenting my ltc2mtc better and making it easier to use. What are using for sending MTC over rtpmidi? If you are using windows to receive you need the rtpmidi driver. https://www.tobias-erichsen.de/software/rtpmidi.html Then you need to select the it in ontime.

My tip is to try with pixtimecode to get a second option if things are working. https://apps.microsoft.com/detail/9MT05F4N77XZ

**Comment by MilkMGN** [comment]
> Hey @MilkMGN are you trying out ontime or Viktor's ltc->mtc converter?
> 
> if it is Ontime for now a restart after changing the clock settings 

Hahaha it's been a long week already. Sorry, trying your ontime build.

**Comment by MilkMGN** [comment]
![image](https://github.com/cpvalente/ontime/assets/42798255/20b439d8-1e0c-44f5-93c0-96931cf2396e)
We are currently having an issue where timecodes are not triggering or correlating to the event, for example we have an event (Bluey X Deck the halls) that is set at 05:00:00 and the timecode is corrosponding to this, however when the event is loaded it either wont start or skips down multiple events with no seeming pattern. does anyone know what we are doing wrong to cause this. thanks for all your help so far!

**Comment by viktorfreiman** [comment]
@alex-Arc I had the big show last week a it worked fantastic. Your latest version fixed also the bug when operator view loses follow. Keep up the good work and I am looking forward if you can get MTC into main.

@cpvalente I hade some problems with turbo and pnpm but I need to retry and document what went wrong. Will keep you posted with new issue if needed.

**Comment by alex-Arc** [comment]
@viktorfreiman we are looking at maybe not driving the internal clock external but setting it as an option per event 
would love your feedback while we figure out how it best could work
https://github.com/cpvalente/ontime/pull/701

**Comment by viktorfreiman** [comment]
(All times are in HH:MM:SS:MS)

A problem I see with mixing show timecode sync (external) and wallclock (internal) in the same project is what you do when you get a time collision.

Say it's 09:01:12:00 and you have a Soundcheck but then light wants to test song 2 with backtrack. Lights starts the tracks and then sends 02:00:00:00 to ontime. Is the idea to abort the soundcheck and jump stright to Song 2?

I my mind I want then to have two separated ontime projects and just run then om diffrent ports. One for the show, syncing externaly (Song1, Song2) and one for the wallclock(Open doors, Soundcheck).

I really appreciate all the work you guys do.

**Comment by cpvalente** [comment]
We have investigated this and there was some user enthusiasm.

however I don’t see that this plays well with the rest of the app.

For the outlined use case where we have events which are triggered from an external timer source, the auxiliary timer should be the way to go.

Will mark this as won’t do for now to welcome feedback and close the issue eventually
