### ISSUE TITLE
Docker: Currently provided instructions are impossible

### ISSUE THREAD

**Issue by MilkMGN** [cpvalente/ontime#536]
Hello.

Currently, the guide on the README.MD, it states:

> [Headless run️](https://github.com/cpvalente/ontime#headless-run%EF%B8%8F)
> You can self-host and run Ontime in a docker image. The run command will:
> 
> expose the necessary ports (listed in the Dockerfile)
> mount a local file to persist your data (in the example: $(pwd)/local-data)
> the image name getontime/ontime
> The docker image is in [available Docker Hub at getontime/ontime](https://hub.docker.com/r/getontime/ontime)
> 
> `docker pull getontime/ontime`
> and use the included docker compose to get started
> 
> `docker-compose up`
> Related information available [in the docs](https://ontime.gitbook.io/v2/additional-notes/use-in-raspberry-pi)

This does not work, as pulling a docker image does not pull it into your current directory, so no way to run the included `docker-compose.yml`. I may be wrong, I am unexperienced in Docker, but there does not seem to be a way to run headless currently, at least not well documented.

**Comment by cpvalente** [comment]
Hi @MilkMGN, thank you for reaching out

I am not aware of any issues with the docker image. 

Either way, what you describe is not specific to Ontime, but just how to work with any docker image. You can pass to the docker-compose command a path to the file if you are not currently in the directory. 
You will likely be better served by the docker documentation in this case

There are also some handy docker UIs that might facilitate the process for you


Meanwhile, I will double-check that there are no issues with the docker release

**Comment by MilkMGN** [comment]
> Hi @MilkMGN, thank you for reaching out
> 
> I am not aware of any issues with the docker image.
> 
> Either way, what you describe is not specific to Ontime, but just how to work with any docker image. You can pass to the docker-compose command a path to the file if you are not currently in the directory. You will likely be better served by the docker documentation in this case
> 
> There are also some handy docker UIs that might facilitate the process for you
> 
> Meanwhile, I will double-check that there are no issues with the docker release

Hey, yes, the correct instructions are on the [Docker Hub](https://hub.docker.com/r/getontime/ontime).

So maybe an updating of the readme.md instructions is in order?
