### ISSUE TITLE
Bug: Backstage View on iPads

### ISSUE THREAD

**Issue by hrueger** [cpvalente/ontime#538]
We often have views on iPads, because lots of people have them around and they are very handy to take with you. However, the backstage view has a slight layout problem:
![grafik](https://github.com/cpvalente/ontime/assets/18656830/21c1a7d0-79c6-492b-873d-5882a1a1e9f7)
As you can see, the stage timer overlaps with the text, the qr code overlaps with the list of events and the backstage message overflows the screen.

**Comment by cpvalente** [comment]
This has been fixed in v3
