### ISSUE TITLE
Feature: (Simple) Drag-and-Drop WYSIWYG Layout Builder

### ISSUE THREAD

**Issue by hrueger** [cpvalente/ontime#539]
We often need custom layouts, however, the time at productions is usually very limited so unfortunately we cannot code them.
It would be great to have a (very simple) drag and drop builder for layouts where you can just add the widgets you need (progress bar, timer, message, event block, info, etc) and save that layout.

**Comment by hrueger** [comment]
A possible implementation could look like this:
- We use this library: https://github.com/react-grid-layout/react-grid-layout
- and the settings from [this example](https://react-grid-layout.github.io/react-grid-layout/examples/6-dynamic-add-remove.html)
- Each box contains a dropdown to pick the widget to be displayed (store an id for each widget type)
- When pressing a save button, an array is built with the width, height, x, y and type of each widget and is saved in the project
- To display the view we just need to load that array, instanciate the grid layout while setting all elements to [static](https://react-grid-layout.github.io/react-grid-layout/examples/5-static-elements.html) and render the respective widget inside the box depending on the stored widget id

**Comment by cpvalente** [comment]
Hi, Thank you for your suggestion.

I fear that the components are not responsive enough for this. For us to be able to implement it this way there has to be some pre-work done in making all components responsive, we could also look whether the react-grid-layout allows us to have a minimum size defined per component.

How do you suggest we distribute this? would these custom layouts be part of the project file?

**Comment by cpvalente** [comment]
Hi @hrueger , I am afraid I don't have much of an opinion at this moment.
In my mind, we are many steps away from having to think about this details

Making the components fully responsive alone could take several weeks of work.

I am sorry if this is not the answer you were looking for. Once we are ready to take the WYSIWYG test I will put some more thought into it, but I do not see it in a realistic near timeline.

As for #530 , there is almost no code needed to achieve it, the express server is ready, we just need to make a new directory and add it to the files served. If this is helpful to you, you are welcome to try it out

**Comment by hrueger** [comment]
Hey, no worries. It is already great to have this listed as an issue here. I don't expect anyone to just go for it and implement all my (sometimes quite complex) feature requests.

**Comment by cpvalente** [comment]
Closing this as not part of the roadmap for v3
