### ISSUE TITLE
Improve in app help

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#54]
There should be more clarity in the application about how it works.
We will make a PR focusing on that, it would be nice to gather some ideas here

- [ ] Add documentation in app
- [x] Add tooltips on buttons? (Not sure about this, as it might clutter interface)

### Add documentation in app?
What format could this take? 
Currently all the [documentation is in gitbook](https://app.gitbook.com/cpvalente/ontime). However in my experience, a lot of production machines are offline.
I am careful of cluttering the application with elements that could hurt its performance and portability.

I imagine that every component could have a small help button that would display some hints on the usage (text only) as well as a link to the relevant gitbook page
Quick sketch 
![inapp help](https://user-images.githubusercontent.com/34649812/144485811-bc06e46d-fccf-4538-a589-cb744b3f0f96.jpg)

### Add tooltips on buttons
Not a big fan of this approach. As a user of similar software, I believe it becomes harmful to experienced users by creating distracting changes in the layout. This is why the tooltips only exist on navigation help, which you woudlnt be using in a live scenario anyway.
Thoughts? Happy to be wrong

And for further documentation see #51  and #52

**Comment by xztraz** [comment]
tooltip was just my first idea and the first thing i look at when i forgot what a button does.

some ways to make tooltips less cluttering is using a delay on the tooltips. or make tooltips on/off. n00b mode or what you want to call it :)
a help button, sure but often you just need a small hint.
just throwing some thoughts around and i see the point with cluttering changing interfaces. 

guis should be self explanatory but it's not that easy all the time :)

**Comment by cpvalente** [comment]
sure, I appreciate the help. Lets try some stuff and see how it goes

**Comment by chabad360** [comment]
I've been looking at this tool and will probably start using it in the near future.

Just to add my two cents: I would think a delayed tool tip would be very helpful, especially because some icons don't really explain their meaning well. I don't think a lot of people are going to check the docs before they use this, so I would probably be good make everything as self explanatory as possible.

(btw, it seems to work fine on linux)

**Comment by cpvalente** [comment]
Thank you for your input @chabad360. Both good points.
Can you help me pinpoint which icons could be revised? 

I will add a section about build since the pipeline is about to become slighly more complex. Would you be using the app in linux?

**Comment by chabad360** [comment]
I think #51 is pretty good for that, I know that specifically the "bring show to current time" (blue one with clock) button caught me by surprise when I clicked it. 

Regarding Linux, I will probably be spending more time setting up the show than actually running it on Linux. (It would probably be best if the build pipeline was basically just `yarn build && yarn run` in the root directory)

**Comment by cpvalente** [comment]
tooltips and some better wording of help released as #88 
I will leave the issue open for now
