### ISSUE TITLE
Feature: Useful / descriptive names for rundown exports

### ISSUE THREAD

**Issue by hrueger** [cpvalente/ontime#540]
Currewntly, all exported rundown files are called `rundown.json`. This makes a second renaming step necessary, at least if you don't want to end up with tons of unnamed and unsorted rundown files in your download folder ;-)

New naming proposal: `[yyyy-mm-dd] [project name].json`

**Comment by cpvalente** [comment]
This is a good suggestion, but should be implemented as part of an overarching task to improve the project file system as described in #374

**Comment by cpvalente** [comment]
Closing this as it is part of another task
