### ISSUE TITLE
Bug: Events in Backstage View blink if their properties change

### ISSUE THREAD

**Issue by hrueger** [cpvalente/ontime#541]
If you change the note of an event which is currently playing and view it in the backstage view while blurring the focus of the note field, the event blinks. This is because of the code [here](https://github.com/cpvalente/ontime/blob/2f74293505d4f496cf257aeb69b955b3d5dcab72/apps/client/src/features/viewers/backstage/Backstage.tsx#L52-L61). However, this should only happen if the event itself changes.

**Comment by alex-Arc** [comment]
I also get the slide in animation, witch is a bit disorienting
https://github.com/cpvalente/ontime/assets/19875125/bd2fa59c-f494-4038-b473-c99ec43ea61e

The notification is ok but maybe a more subtle puseling
https://codepen.io/FlorinPop17/pen/drJJzK

**Comment by cpvalente** [comment]
Hi @hrueger , what is the status here?
I see some related changes were merged, but it seems that it didnt address the issue you mentioned?

Would you like to offer a solution? it seems like there might be a pretty straightforward one available

**Comment by hrueger** [comment]
Can the react `useEffect` hook only fire on value changes, or do we need to cache the previous value and check for string equality?

**Comment by cpvalente** [comment]
> Can the react `useEffect` hook only fire on value changes, or do we need to cache the previous value and check for string equality?

It could be pretty straightforward to create a hook which keeps the value from a previous render in a ref, you can then see if the value of the selected has changed.

**Comment by hrueger** [comment]
Sounds good, this is probably far outside of my react skills though 😁

**Comment by cpvalente** [comment]
Hu @hrueger , I believe you might be underestimating yourself.

the hook I described could be written like

```ts
import { useEffect, useRef } from 'react';

export function usePrevious<T>(value: T): T | undefined {
  const ref = useRef<T>();

  useEffect(() => {
    ref.current = value;
  }, [value]);

  return ref.current;
}
```

the gist of it is that we use a `ref`, which does not trigger re-renders and has stable value

we would keep the id of the event here, and in the `useEffect` compare the `previousId` to the `newId`, if they are different, we trigger the animation you have created

**Comment by hrueger** [comment]
Hm, to be honest, I don't completely understand what is happening here ;-)
I come from Angular and I'm now using Svelte, which both use a different change detection method than those hooks.
Anyway, I have to admit that currently I don't have time available to work on this :-| Sorry for that.

**Comment by cpvalente** [comment]
We havent been able to identify the described issue. 
It could have been fixed as a side effect of some other change

Closing this to give us a better overview of work to be done
