### ISSUE TITLE
Feat: Print view of rundown / PDF Export

### ISSUE THREAD

**Issue by hrueger** [cpvalente/ontime#542]
It would be great to be able to export the rundown to a printable format directly. For the first step, printing would be totally fine, at least in my opionion. This should not be too complicated:
- A new view has to be build with a printer-friendly css stylesheet (white background, no / very few colored boxes, etc)
- Printing via `window.print()` if running in the browser and via `win.webContents.print()` if in electron. The first might also work in electron, we'd have to test that.
- If we open that view in a new window, we can close that immediately after printing.

**Comment by cpvalente** [comment]
Closing this as not part of v3
