### ISSUE TITLE
Feature: Interactive Notifications for Interactive Views

### ISSUE THREAD

**Issue by hrueger** [cpvalente/ontime#545]
A view could be marked as interactive. This could either happen through some configuration (the settings of each view) or be automatically detecting that the device has a touchscreen (does that make sense?)
Then, interactive notifications could be sent through the editor:
- Optional Title
- Message
- Type: "Confirmation" | "Question"

The notification then pops up on all interactive views. If it is a confirmation, we only have an "OK" / "Dismiss" Button. If it is a question, we should have "Yes" and "No" buttons.

We do need to decide what happens to multiple responses and how they are displayed.

**Comment by cpvalente** [comment]
Hi @hrueger , at this point we feel this doesnt provide value to enough of our user base to be a priority.

On the other hand, this is a very straightforward feature and we could consider a PR

**Comment by cpvalente** [comment]
Closing this as not part of v3
