### ISSUE TITLE
Bug: Cannot leave Cue Sheet view

### ISSUE THREAD

**Issue by hrueger** [cpvalente/ontime#546]
The cue sheet is the only view without the navigation button which is displayed on hover. I'm not sure if this is intended, but we had a couple of users who clicked on the cue sheet by accident and needed support on how to get back because it was different than the other views.

**Comment by cpvalente** [comment]
The cuesheet and the editor view are production views and different from the rest
Perhaps the real fix is to remove the cuesheet from the navigation menu in the first place

What do you think?

**Comment by hrueger** [comment]
Makes sense 👍

**Comment by asharonbaltazar** [comment]
@cpvalente Can you please outline the necessary changes for this issue?
