### ISSUE TITLE
Docker image: can't set a PIN for editor view.

### ISSUE THREAD

**Issue by ivmoiseev** [cpvalente/ontime#550]
Hi!

I run Ontime v2.9.0 in a docker image and have an issue.
When I go to settings page and try to set a PIN, i get an error:
**Error saving settings: Forbidden: "Can`t change port when running inside docker"**

But Ontime is running on default 4001 port and I don't touch this setting.
Can you help me?

**Comment by cpvalente** [comment]
Hi @ivmoiseev, thank you for bringing this to my attention.
This is indeed a bug with the logic and will be fixed in the next release.
