### ISSUE TITLE
Samsung TV Browser

### ISSUE THREAD

**Issue by Richie-63** [cpvalente/ontime#552]
Why can´t I see the full program-view on my Samsung TV Browser? There is only a symbol to be seen...??

**Comment by cpvalente** [comment]
Hi, can you please attach more information to the ticket?
What TV model, what resolution, maybe an image of what you see?

**Comment by Richie-63** [comment]
Samsung M5 Smart Monitor

**Comment by cpvalente** [comment]
Thank you @Richie-63 
At that resolution and with the Samsung browser (based in Chromium as far as I can tell), I see no obvious reason for issues.

Are you able to attach an image of what you see?

**Comment by alex-Arc** [comment]
![IMG_20231024_133107](https://github.com/cpvalente/ontime/assets/19875125/dbb394b5-2380-4a5c-8227-3cbacd5c382e)
![IMG_20231024_133125](https://github.com/cpvalente/ontime/assets/19875125/3b1cb73c-0fa6-4c6b-b7dd-522288938172)
![IMG_20231024_133141](https://github.com/cpvalente/ontime/assets/19875125/1517888e-a7d5-4a26-90be-e3e4fd442a1c)
![IMG_20231024_133155](https://github.com/cpvalente/ontime/assets/19875125/435c003a-a7f5-4c1d-930f-c065a84e0e32)
![IMG_20231024_133359](https://github.com/cpvalente/ontime/assets/19875125/9c23c52d-e802-4031-a588-ff9e1e08f7f2)

**Comment by Richie-63** [comment]
> Thank you @Richie-63 At that resolution and with the Samsung browser (based in Chromium as far as I can tell), I see no obvious reason for issues.
> 
> Are you able to attach an image of what you see?

.. I try to get a screenshot - it is based on my school. s a teacher I want to run this system with WLAN: The Smart Monitor runs with WLAN and should show the different cases (PiP, presenter, watch,..etc ....) with the given URLs:
![grafik](https://github.com/cpvalente/ontime/assets/116575686/d75820d3-09ff-4f19-be07-32971c2c82ce)

**Comment by Richie-63** [comment]
> i did a quick test on a Samsung Smart TV the only one i ad trouble with was the op view ![IMG_20231024_133107](https://user-images.githubusercontent.com/19875125/277645415-dbb394b5-2380-4a5c-8227-3cbacd5c382e.jpg) ![IMG_20231024_133125](https://user-images.githubusercontent.com/19875125/277645420-3b1cb73c-0fa6-4c6b-b7dd-522288938172.jpg) ![IMG_20231024_133141](https://user-images.githubusercontent.com/19875125/277645424-1517888e-a7d5-4a26-90be-e3e4fd442a1c.jpg) ![IMG_20231024_133155](https://user-images.githubusercontent.com/19875125/277645426-435c003a-a7f5-4c1d-930f-c065a84e0e32.jpg) ![IMG_20231024_133359](https://user-images.githubusercontent.com/19875125/277645427-9c23c52d-e802-4031-a588-ff9e1e08f7f2.jpg)

which URLs do you write within the Browser-window?

**Comment by alex-Arc** [comment]
Hey @Richie-63 
the same URLs that you describe
if you run on windows remember to allow incoming connections through your firewall

**Comment by Richie-63** [comment]
I think, the problem is the "old" (Browser-)software: 
- We have 1 Smart-monitor with Software 3.x --> no function!!!
- We have 1 Smart-monitor with Software 5.x --> it runs!!!

Which Version do you have?

**Comment by alex-Arc** [comment]
not really sure how to find the version number, but it was purchased this spring so probably the newest version
are you able to update it?

**Comment by alex-Arc** [comment]
there are 3 files here, if possible please test them all
https://www.dropbox.com/t/X4PtHSSe46LWTISD

**Comment by Richie-63** [comment]
Thank you very much!!!!!!!!!!!!!!!!

 

*	How should I go on now with these files?
*	Where to load? Where to install?

 

Best regards!

Richie

 

Von: Alex Christoffer Rasmussen ***@***.***> 
Gesendet: Freitag, 27. Oktober 2023 13:23
An: cpvalente/ontime ***@***.***>
Cc: Richie-63 ***@***.***>; Mention ***@***.***>
Betreff: Re: [cpvalente/ontime] Samsung TV Browser (Issue #552)

 

there are 3 files here, if possible please test them all
https://www.dropbox.com/t/X4PtHSSe46LWTISD

**Comment by alex-Arc** [comment]
hey @Richie-63 
- **master** this is the default build
- **legacy** should enable legacy support
- **samsung** specifically adds older samsung borwsers to the list

yes please try each install on the "sending" computer and see if your older smart TV can load the page

**Comment by cpvalente** [comment]
Hi @Richie-63 , have you got any feedback for us on whether this fixed your issue?

**Comment by Richie-63** [comment]
.. the problem still exists - no function on the screens with Software No 3.x

**Comment by cpvalente** [comment]
Hi @Richie-63 , @alex-Arc has been making some tests and I feel that the the software version is too far behind for us to support. It looks like we would need to downgrade to chrome 47 (current is 121)
You can see the results of compatibility down to v63 in [the PR here](https://github.com/cpvalente/ontime/pull/611)

This is likely not what you hoped to hear and I will try and find ways to increase the compatibility of the views, but that wont happen at this time unfortunately
