### ISSUE TITLE
Feature : manage sound when the timer reaches a certain time

### ISSUE THREAD

**Issue by CPASimUSante** [cpvalente/ontime#557]
This tool is great, but to be 100% usable for us, we would need to be able to attach a sound (choosable from a bank - folder) to potentially each timer, that would be played at least when the countdown reaches 0 for instance (or in a more advanced manner at a defined point of the timer : 10 second before the end, play a 10s horn sound).

For instance, I could have :
```
timer 1, sound 1
timer 2, sound 1
timer 3, sound 2
timer 1, sound 1
...
```

Would it be something you could consider adding ?
Thank you

**Comment by cpvalente** [comment]
Hi @CPASimUSante, thank you for reaching out.

We have had similar feature requests in the past, see #163 
As I mentioned then, the nature of Ontime makes it difficult to have this be useful for a large part of users without several layers of customisation (at minimum, which machine plays the sound and which sound is played)

In my opinion as a video engineer, this is best achieved by using an integration, you route the ontime data or leverage companion to trigger any side effects you may want. This also means that you have complete control over what happens and are not dependent on Ontime's implementation

For this reason I am reluctant that this is a good addition the application, but will leave the issue around so users have a chance to weigh in

**Comment by CPASimUSante** [comment]
hello @cpvalente , thank you for the quick reply.

I understand that in your use case, you don't need integrated sound addition, since you can rely on external sources (and maybe even have a person managing the sound part, while you focus obn the video side).

However, I am interested in your tool for our project, but in our setup, there would be about 50 tablets synchronised in 25 rooms in 3  separate buildings. We would like to use it for an exam, where each student and examiner could look at the timers to estimate the time left (sessions of about 8 minutes). Since they are focused on the exam, the display only would be not enough, a sound reminder should  tell them the session has ended or is about to end.
So, the programmable timer series and the tablet synchronization are 100% what we expect but without the sound, it is not usable for this project.

Thank you anyways

**Comment by cpvalente** [comment]
No problem, thank you for reaching out and I am sorry you didnt get the answer you were looking for
The project is open source, and there is always a possibility that someone else has a similar requirement and would be eager to implement

I will leave the issue open for that reason and to help gauge the users interest in this feature
