### ISSUE TITLE
New languange

### ISSUE THREAD

**Issue by nscpro** [cpvalente/ontime#559]
I would like to translate a new language, but how can I do it?

**Comment by alex-Arc** [comment]
hey @nscpro 
if possible follow these steps to set up local development https://github.com/cpvalente/ontime/blob/master/DEVELOPMENT.md 
and then make a new file here apps/client/src/translation/languages/??.ts

if you are new to all of this let me know and we can figure something out

**Comment by cpvalente** [comment]
Hi @nscpro , there isnt much else we can do here to move forwards.
You can add a language yourself by creating a new translation file and registering it into the TranslationProvider

If you would like this to be included in Ontime you can send help us by translating the text provided by Alex. We will make sure it gets added to the next release

```
  'common.end_time': 'End Time',
  'common.expected_finish': 'Expected Finish',
  'common.now': 'Now',
  'common.next': 'Next',
  'common.public_message': 'Public message',
  'common.start_time': 'Start Time',
  'common.stage_timer': 'Stage Timer',
  'common.started_at': 'Started At',
  'common.time_now': 'Time now',
  'countdown.ended': 'Event ended at',
  'countdown.running': 'Event running',
  'countdown.select_event': 'Select an event to follow',
  'countdown.to_start': 'Time to start',
  'countdown.waiting': 'Waiting for event start',
  'countdown.overtime': 'in overtime',
```

I will leave this open for a while longer before closing
