### ISSUE TITLE
Enabling Roll Mode leads to WS In Error

### ISSUE THREAD

**Issue by lebaston100** [cpvalente/ontime#560]
I'm trying to use roll mode but when clicking the roll button i just get a "WS IN: TypeError: Cannot read properties of null (reading 'id')" Error in the Log and no timer is started. I've tested it with both of the latest stable and the beta on a completely new project with just a single event in it. Don't know of any log files i could provide, so if there is anything you need to investigate this further just let me know.
![image](https://github.com/cpvalente/ontime/assets/26111114/3648657a-9166-477b-8497-77880b0bd10a)

**Comment by alex-Arc** [comment]
Hi @lebaston100  I think if found the bug
can you try and see if it works if you set the event to public?

**Comment by lebaston100** [comment]
Yes, it seems to work if the event is set public.

**Comment by alex-Arc** [comment]
Great it should be fixed when #561 gets merged
after we find all the places were this might also happen
