### ISSUE TITLE
Docker hub instructions are out of date.

### ISSUE THREAD

**Issue by kyelewis** [cpvalente/ontime#563]
The docker hub page https://hub.docker.com/r/getontime/ontime
is the top result here for `ontime docker`, but unfortunately instructions are out of date.

If they are followed the database will be lost when the docker instance is recreated.

(Also the gitbook link is broken at the bottom of the instructions.)

**Comment by cpvalente** [comment]
Hi @kyelewis , thank you for bringing this to my attention.

I am unaware of any issues with the docker image,
the shared volume is created when you run `docker compose`, running the docker instance itself should reuse the database available or create a new one. is this not what you experience?

**Comment by kyelewis** [comment]
Hi,

The issue is with this part of the docker hub instruction/;

```    
volumes:
      - "./ontime-db:/server/preloaded-db"
```

My expectation is that using the example, the database will be saved there, but this directory stays empty-
perhaps there is other missing instruction or assumption?

**Comment by saadbruno** [comment]
I had the same issue. Fixed by adding:

```
    volumes:
      - "./data:/external/db"
 ```

**Comment by cpvalente** [comment]
Hi @kyelewis , apologies for the slow replies, I need to try and find out what can have changed which would have broken this flow

According to @saadbruno it seems that we are providing the incorrect directory, are you able to confirm that his solution works?

**Comment by cpvalente** [comment]
We have revised this and updated the docs, thank you for bringing this up
