### ISSUE TITLE
autoscaling of post area a bit weird

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#57]
small window
![image](https://user-images.githubusercontent.com/25690871/144588840-628864ec-e1aa-494b-95d0-e8df8aee7308.png)

big window
![image](https://user-images.githubusercontent.com/25690871/144588997-b0c2e1ab-30b4-44a5-9f4c-97502b5a8404.png)

**Comment by cpvalente** [comment]
Fixed
