### ISSUE TITLE
Timezone in docker

### ISSUE THREAD

**Issue by nscpro** [cpvalente/ontime#574]
"Time now" get UTC time, not Timezone..If I put TZ=Tallinn/Europe..it show time 00:28:13 not 02:28:13

**Comment by cpvalente** [comment]
> "Time now" get UTC time, not Timezone..If I put TZ=Tallinn/Europe..it show time 00:28:13 not 02:28:13

Hi @nscpro , thank you for reaching out

I assume that you are in docker. 
It is important to note that ontime uses the system time. The setting of the timezone happens in the system, not in the app. We also are not aware of any issues with the app or docker compose 

That means that you should be debugging the timezone in your container. This should be pretty straightforward, I assume that there is just an issue of misspelling. See this reference 

https://manpages.ubuntu.com/manpages/focal/man3/DateTime::TimeZone::Catalog.3pm.html

Hope this helps

**Comment by cpvalente** [comment]
Hi @nscpro , do you have any follow ups here? Did you manage to get things to work?
I will leave this open for a while longer and close soon.
You are still welcome to re-open or create a new issue. Otherwise feel free to reach out on email (see website) and we can help you out
