### ISSUE TITLE
Roll mode issues

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#58]
Few issues in roll mode.

if the start time is the day after end time, and start time is earlier than now. Roll mode dismisses the event
eg. 
Now: 19:30
Event Start: 19:20
Event Finish 16:10

If the start time is the day after end time, and both are later than now. An error occurs unable to find `DAY_MS of undefined at getSelectionByRoll`
eg.
Now: 19:34
Event Start 19:40
Event End: 19:35

**Comment by cpvalente** [comment]
One more before closing up, it looks like the timer is one second ahead while running in roll mode
Lots of stuff over at issue #42 https://github.com/cpvalente/ontime/issues/42#issuecomment-995312156

**Comment by cpvalente** [comment]
Fixed with 2751ed3

**Comment by xztraz** [comment]
works! rc5+log
