### ISSUE TITLE
2.21.3 macOS-arm64 does not launch

### ISSUE THREAD

**Issue by JamesClick** [cpvalente/ontime#630]
Hey there,

It appears that the arm64 build of 2.21.3 (downloaded from GitHub) does not launch. Testing on M1 Pro running macOS 14.0.

<img width="372" alt="image" src="https://github.com/cpvalente/ontime/assets/15151345/7e36e942-30ac-4205-9981-84f5e54f3bee">

**Comment by cpvalente** [comment]
Hi @JamesClick , thank you for reaching out.

The app is not signed, since this means a paid process. You can read about it [in the Apple docs](https://support.apple.com/en-us/HT202491)

For now, you can use the intel release (the one downloaded when you click the macOS download on the website) or you can bypass gatekeeper to run the arm version
This is a common problem for free applications and not unique to ontime, you should be able to find several guides on how to do so

Hope this helps

**Comment by jwetzell** [comment]
I could try signing a ARM Mac build to see if the issue goes away. Not sure if it just needs signed or if it would also need to go through the notary process. I've got a few electron apps that I work on that do sign/notarize their Mac builds you could see if those produce this same error message.

**Comment by cpvalente** [comment]
Hi @jwetzell , I dont maintain any other electron apps and the process is slightly mysterious to me. 

To what I can infer from the docs, signing should be enough, but I am unsure on how I can provide certificates to the CI without a paid developer account. If you are able to help it would be greatly appreciated

**Comment by jwetzell** [comment]
@cpvalente @JamesClick [here is a link](https://we.tl/t-n8m8qBpKSM) to a signed version of the v2.21.3 tag both x64 and arm64 builds.

**Comment by cpvalente** [comment]
thank you @jwetzell , do you maybe have some availability to help us get ontime signed?

**Comment by jwetzell** [comment]
Yeah, electron-builder handles pretty much handles the hard part of signing/notarizing. The other part is giving in to Apple's $99 developer account fee so you can get the certificates necessary to hand off to electron-builder.

**Comment by cpvalente** [comment]
Closing this for now since there is not much we can do right now to improve the situation

**Comment by jwetzell** [comment]
@cpvalente If you ever get an Apple developer account I can assist with any troubles in setting up the signing/notarizing.

**Comment by cpvalente** [comment]
Hi @jwetzell 

I am currently working on signing and notarizing Ontime's distribution for MacOS.
However without much luck

This work is happening on a separate, private repo to avoid exposing information while I run tests. If you are available we could try and find a way to communicate. Either over email at mail@getontime.no or on the [video engineering discord](https://discord.gg/SffckvCX)

In short, the signing process works well and I have verified that the assets get signed. However the notarization step fails with a `Unexpected token E in JSON at position 0` error as described here https://github.com/electron/notarize/issues/186 (stack trace under)
I have attempted lowering the `electron-notarize` version as suggested with no luck. 

I am pretty confident that the configuration of electron is correct and I have double-checked all secrets
My current estimation is that there is some issue with configuration and the error is unhelpful

Would you maybe have some availability to help?

```
    • signing         file=dist/mac-arm64/ontime.app platform=darwin type=distribution identity=... provisioningProfile=none
    ⨯ Unexpected token E in JSON at position 0  failedTask=build stackTrace=SyntaxError: Unexpected token E in JSON at position 0
  SyntaxError: Unexpected token E in JSON at position 0
      at JSON.parse (<anonymous>)
      at /Users/runner/work/ontime-signing/ontime-signing/node_modules/.pnpm/@electron+notarize@2.2.1/node_modules/@electron/notarize/src/notarytool.ts:79:25
      at Generator.next (<anonymous>)
      at fulfilled (/Users/runner/work/ontime-signing/ontime-signing/node_modules/.pnpm/@electron+notarize@2.2.1/node_modules/@electron/notarize/lib/notarytool.js:28:58)
```
