### ISSUE TITLE
Improve HTTP API

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#641]
We would like the HTTP API to take advantage of the integration controller to be as capable as the other APIs

This means:
- HTTP API should be made of GET methods
- We would extend the `playback` endpoint to call integrationController
- Data should be translated before reaching controller

**Comment by alex-Arc** [comment]
what path should it take /ontime/api or just /api or a 3. option?

**Comment by cpvalente** [comment]
I believe the second version is sufficient since the hostname would potentially already be ontime

`https://ontime:4001/api/ `or `https://192.168.10.1:4001/api/`
