### ISSUE TITLE
Feature Request: option to hide seconds in views

### ISSUE THREAD

**Issue by echalupka** [cpvalente/ontime#649]
Feature Request: support ?seconds=false on all views

**Comment by cpvalente** [comment]
Hi @echalupka , thank you for getting involved
Would this only apply to the running timer or all other time fields?

**Comment by echalupka** [comment]
All time fields; clock, count up timer, and count down timer. Thanks!
________________________________

**Comment by echalupka** [comment]
There should maybe also be a flag on timers to show seconds/hide hours under a certain amount of time, say under 2 minutes?
________________________________

**Comment by cpvalente** [comment]
## The Task

We would like to be able to configure whether the seconds are shown in the views
This should apply to both clocks and timer data

We decided to affect only passive views:
- Timer
- Minimal
- Clock
- Countdown
- Public
- Backstage
- Studio Clock

## Implementation Notes

We would do this using the [View Parameters](https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/viewers/timer/Timer.tsx#L137) for each affected view

In the case of clocks, this is [already abstracted](https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/viewers/timer/Timer.tsx#L89) so the change should be straightforward, just a matter of adding the new variable to the format object

For the timer, there is [an abstraction in place](https://github.com/cpvalente/ontime/blob/master/apps/client/src/features/viewers/timer/Timer.tsx#L116), but it currently does not accept a parameter for suppressing seconds. the change should be simple

**Comment by cpvalente** [comment]
Hi @echalupka , we decided to try and provide user definable format strings such as hh:mm:ss

Since this needs some extra work and documentation, we will merge it to v3

**Comment by echalupka** [comment]
@cpvalente This is great!

**Comment by cpvalente** [comment]
Done in v3 with #696
