### ISSUE TITLE
Studio View - On Air does not change to reflect OnTime status

### ISSUE THREAD

**Issue by juzz197** [cpvalente/ontime#662]
The 'On Air' in the Studio view does not reflect the status of OnTime.

I think this is due to both states being set to the same colour:

color: var(--studio-idle, #c53030);
color: var(--studio-active, #c53030);

Version 2.24.8 in Docker on Raspberry Pi 
Studio View checked on Safari (17.2) and Firefox (120.0.1) on MacOS (14.2)

**Comment by cpvalente** [comment]
Hi @juzz197 ,

Thank you for bringing this to my attention, we will push a fix to the next release
