### ISSUE TITLE
Visual Bug: Rundown editor

### ISSUE THREAD

**Issue by kellhogs** [cpvalente/ontime#676]
![image](https://github.com/cpvalente/ontime/assets/19673098/224dd802-f7fe-46ee-9465-db7543580c0d)

When trying to edit an event that is in the "past" in the current rundown you get this visual bug and are not able to access the options that are behind the other element.

The opacity change for the "past" rundown entry is most likely to cause this issue.

**Comment by alex-Arc** [comment]
what ontime version and browser are you on?
seams to be working in chrome and firefox both in the v3 and master branch
![image](https://github.com/cpvalente/ontime/assets/19875125/2128f0c4-2ec7-464b-b5f3-ceabb0b1241f)

**Comment by kellhogs** [comment]
I'm in the master branch on Chrome. But you have the wrong dropdown. I'm talking about the options dropdown with the three dots in the upper right

**Comment by alex-Arc** [comment]
ah my bad, I see it now
![image](https://github.com/cpvalente/ontime/assets/19875125/bb73ba72-2a03-4fc6-a432-024039913708)


somehow is works if the event is set to skip
![image](https://github.com/cpvalente/ontime/assets/19875125/4891d26d-b03c-4fb9-81bc-7cd5616b18cf)

**Comment by kellhogs** [comment]
I think that is because the opacity change is not applied if the event is skipped
![image](https://github.com/cpvalente/ontime/assets/19673098/1da75663-b29d-4779-8d9e-64d487ecdf5a)
