### ISSUE TITLE
ViewParamsEditor save defult

### ISSUE THREAD

**Issue by alex-Arc** [cpvalente/ontime#691]
when checking for the default value we are using `includes` witch means that something like `title` and `subtitle` will both be evaluated true

@asharonbaltazar do you have an idea on how to fix this? Would it break thing to just use a `==`

This is needed for the new Lower Thirds #665 

https://github.com/cpvalente/ontime/blob/40bede200cf7011ea3c5d0fb053e76377c276722/apps/client/src/common/components/view-params-editor/ViewParamsEditor.tsx#L30

**Comment by asharonbaltazar** [comment]
Have you tried using a strict regex?

**Comment by alex-Arc** [comment]
what do you think about this
https://github.com/cpvalente/ontime/pull/665/commits/a1ebc77ecf6ebdccadecd3b41e461f955d06d18a

**Comment by asharonbaltazar** [comment]
Left a comment. Thank you so much!

**Comment by alex-Arc** [comment]
is this something we should fix in v2 as well or are there maybe no collisions there?

**Comment by cpvalente** [comment]
Hey @alex-Arc. The operator view is the only place I know that could have a similar issue.
If the operator view has this bug we should fix in v2, otherwise I am unaware of any issues that need resolving in v2
