### ISSUE TITLE
httpAPI onAir => bad request

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#70]
rc5 (unofficial)

ok http://127.0.0.1:4001/playback/start

ok http://127.0.0.1:4001/playback/pause

ok http://127.0.0.1:4001/playback/stop

ok http://127.0.0.1:4001/playback/roll

ok http://127.0.0.1:4001/playback/previous

ok http://127.0.0.1:4001/playback/next

ok http://127.0.0.1:4001/playback/reload

ok http://127.0.0.1:4001/playback/unload

NOK  http://127.0.0.1:4001/playback/onAir
Turn On Air flag ON 
![image](https://user-images.githubusercontent.com/25690871/146646308-ed73db99-675f-41b1-bc56-2105b679fe62.png)

ok http://127.0.0.1:4001/playback/offAir

**Comment by xztraz** [comment]
```
curl -v 'http://192.168.1.200:4001/playback/onAir'
* About to connect() to 192.168.1.200 port 4001 (#0)
*   Trying 192.168.1.200...
* Connected to 192.168.1.200 (192.168.1.200) port 4001 (#0)
> GET /playback/onAir HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.1.200:4001
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: text/plain; charset=utf-8
< Content-Length: 11
< ETag: W/"b-EFiDB1U+dmqzx9Mo2UjcZ1SJPO8"
< Date: Sat, 18 Dec 2021 15:24:55 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host 192.168.1.200 left intact
Bad Request
```

**Comment by cpvalente** [comment]
good catch, typo.
Fixed in feature branch and will be good for release

**Comment by xztraz** [comment]
rc5_v2 OK Verified
