### ISSUE TITLE
pushing roll mode with no items in list throws exeption

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#71]
![image](https://user-images.githubusercontent.com/25690871/146659145-0cbb8ece-5185-43ea-9bc7-116e0e0ed698.png)
rc5_v2(unofficial)

**Comment by cpvalente** [comment]
Thank you. Fixed in feat branch 6f443f0
Will be ready for next release

**Comment by xztraz** [comment]
verified. works in rc5
