### ISSUE TITLE
Import doesn't import User fields

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#713]
Steps to repeat:
1. Download the [Ontime rundown demo](https://docs.google.com/spreadsheets/d/1TYZhAELRFQa_2QBO8Q651fMHdem6AXmFLjEDoksJd8Y/edit#gid=0)
2. Click the Import Project File button (2nd from the top)
3. Make sure everything is named correctly, including Worksheet name and User Fields (I used the names from the XLS file)
4. Import

Notice that any data from User Fields is not brought in, by viewing /cuesheet

**Comment by cpvalente** [comment]
Thank you, @tcconway. I apologise for this oversight.
