### ISSUE TITLE
Is it possible to import a block Type

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#714]
When importing a show from XLS, is it possible to import a type: Block?

**Comment by cpvalente** [comment]
HI @tcconway, thank you again.

This is not possible currently, but it should
We assume everything in the rundown is an event. 

Do you have a suggestion on how we can flag to Ontime that a particular row is a block? I was hoping to avoid yet another column `isBlock` 😓

**Comment by tcconway** [comment]
I thought I was being clever and noticed that during import it shows "Type", so I created a column "Type" with the type "Block" and that obviously didn't work ;-)

What about repurposing "timer type" and rename it to be "type", and then add "block" as an option for that column?

**Comment by cpvalente** [comment]
## Context

Users import data from spreadsheets, the data in the spreadsheet is used to populate the array of events in the rundown.
Currently any entry (row) in the spreadsheet is considered as an event. Ontime takes the fields it knows and pre-populates / ignores the rest

It would be useful for users to be able to have more control over this import. ie: being able to import other event types and prevent something from being imported

## The task

We decided to use the Timer Type column to flag to the parser the event type.
This means:
- [known Timer Types](https://github.com/cpvalente/ontime/blob/master/packages/types/src/definitions/TimerType.type.ts#L1) for events would result in an event entry
- a timer type "block" would result in a block entry
- an unknown timer type would result in that row being skipped

The parsing logic can be found [here](https://github.com/cpvalente/ontime/blob/master/apps/server/src/utils/parser.ts#L50).

**Comment by cpvalente** [comment]
This has been done as part of v3 in #735

**Comment by tcconway** [comment]
So excited! Thanks all!!
