### ISSUE TITLE
Message fields jumps cursor to end of text input box

### ISSUE THREAD

**Issue by tcconway** [cpvalente/ontime#718]
It looks like you can't type mid-string in either the "Public", "Lower third", and "Timer" message boxes.

Steps to repeat:
1. Type something in one of the three message boxes 
2. Click mid string anywhere, or at the beginning of the typed text.
3. Start typing. As soon as you do, the cursor jumps to the end of the previously typed string.

With this bug, it means you can't fix a typo without re-typing the entire string, or deleting text back to where the typo is.

Thanks for looking!

**Comment by cpvalente** [comment]
Good and bad news. I am hoping this has been improved, but you will need to wait for v3

**Comment by tcconway** [comment]
All good news!
