### ISSUE TITLE
Feature: Add option to add event/delay/etc at END of list or custom insert location

### ISSUE THREAD

**Issue by TracyPeterson** [cpvalente/ontime#745]
Currently only allowed to "add event at start" and this is not ideal.  If there was only one option for where to insert a new event, the END of the rundown is where I would want them, but in an ideal world I'd like to be able to select an event and add any new items directly after that one.

**Comment by alex-Arc** [comment]
Hey, thanks for taking your time to come up with suggestions for improving the app.

These buttons are available at the end of your rundown, if you click the they will create a event/delay/block there
![image](https://github.com/cpvalente/ontime/assets/19875125/d0b1dc21-2685-43dc-9675-7f11041574a7)

and if you enable quick entry
![image](https://github.com/cpvalente/ontime/assets/19875125/b9b2322b-2473-48f5-99c7-7b56fb5e6465)

they will also appear bellow the event you have selected, that allows you to insert an event
![image](https://github.com/cpvalente/ontime/assets/19875125/b7cfe031-4662-4c18-b936-2e300d803a9b)

dos this help your use case or where you thinking of something else?

**Comment by TracyPeterson** [comment]
Thanks for answering, I just found these and came back to edit my request, but ill note here that the UI can be improved by adding the options to the "+Event" button at the top of the rundown.  This button draws attention as the primary method of input, not as an optional "top entry" button.

Maybe change the label on the button, it's position, it's difference to the rest, something to id it as a "top button" and not a default event button.

**Comment by cpvalente** [comment]
Hi @TracyPeterson , thank you for this.
The design is largely changed in v3. You can see the ongoing work and latest draft here
https://github.com/cpvalente/ontime/pull/738

I think everyone wins in having intuitive UIs. If you were confused, others would too.
Perhaps you would be interested in helping us with UI? The current draft is still not final in any shape, but shows the direction we are taking the app in the new version

**Comment by cpvalente** [comment]
Hi @TracyPeterson, v3 is in open alpha now and you are welcome to take a look and provide feedback

https://github.com/cpvalente/ontime/releases

Since this issue is mostly related to poor UX and this specific part of the UI has been changed. I will be closing the ticket so that new suggestions can relate to the newest versions
