### ISSUE TITLE
cuelist roll mode issue

### ISSUE THREAD

**Issue by Sound-Techniker** [cpvalente/ontime#757]
hello,
I'm currently testing ontime at a carnival party.
my cue list starts at 18:30 and ends at 00:45.
when i activate the roll mode, the cue list does not start with the first cue in my list but with the first cue after zero o'clock. In addition, the time delays are not included in the next cue. maybe I'm using it wrong?

many thanks for the development and the support

**Comment by cpvalente** [comment]
Hi @Sound-Techniker , thank you for reaching out.

I am unsure if I follow your case, but hopefully, these clarifications can help.

Roll mode will run your rundown automatically against the system clock (wall clock).
This means that the running event will be whatever running event is scheduled at that time, regardless of its order in the rundown.

Perhaps what you are after is an automation that can run your events in order from when you start? You can achieve that by setting the `End Action` of every event to `start next`.

Does this help?

**Comment by Sound-Techniker** [comment]
hi 
thanks for the quick reply.
yes i am aware that the roll mode should automatically run the cues at the appropriate time... but unfortunately this is not the case. 
the order is not correct... I can take a picture of this at work tonight
 i can gladly provide the rundown.

**Comment by cpvalente** [comment]
Thank you! 

I am not aware of issues with the roll mode so it is great that you bring this up.

If you can provide screenshots it would be fantastic. Make sure that the system time is included in the screenshot as well.

Thank you again

**Comment by Sound-Techniker** [comment]
![photo_2024-02-03_20-44-52](https://github.com/cpvalente/ontime/assets/48445427/747dc4e8-6a68-48c9-8ba9-c0d113931f4d)
![photo_2024-02-03_20-45-01](https://github.com/cpvalente/ontime/assets/48445427/2fd844d2-bdf9-4506-ac46-1c0d88df1161)
![photo_2024-02-03_20-45-06](https://github.com/cpvalente/ontime/assets/48445427/a75d928f-cd0a-4691-a7cf-4fae837d567e)

**Comment by Sound-Techniker** [comment]
by the way i downloaded and installed today ontime.

**Comment by cpvalente** [comment]
thank you @Sound-Techniker. this is interesting, do you mind emailing your project file to mail@getontime.no?

**Comment by Sound-Techniker** [comment]
i have send you the rundown

**Comment by cpvalente** [comment]
Hi @Sound-Techniker , thank you for this.
I have found the issue with your rundown and will make a patch

Meanwhile, I wonder what was the source for the data? Was this data entered in Ontime or somewhere else (in excel?)

I believe you can fix the issue by temporarily assigning the end time of the `Künstliche Intelligenz` event to `00:10:00` and then reassigning to `00:17:00`

**Comment by Sound-Techniker** [comment]
Yes i used your template to import the data per excel. I dont know if i have accidental set the wrong data format!?

thank you for your support
