### ISSUE TITLE
import(upload) borken

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#82]
version: ontime-win64 rc0.5.0 aliases + logging + anywhere

importing excel or json gives
![image](https://user-images.githubusercontent.com/25690871/148129988-a3defce8-b157-4149-b32d-5f717658e9d7.png)

**Comment by xztraz** [comment]
[ontime-excel.xlsx](https://github.com/cpvalente/ontime/files/7810644/ontime-excel.xlsx)
test excel

**Comment by cpvalente** [comment]
fixed with #83

**Comment by xztraz** [comment]
still timezone issues

and if entering a space instead of a visible char in "is it public" its interpreted as its public
