### ISSUE TITLE
Docker for v3.0.0-alpha.2 — Fails to Start

### ISSUE THREAD

**Issue by bxtdvd** [cpvalente/ontime#833]
Hello!

I was looking to test the new v3 in a Docker container, but it fails to start — apparently due to a Node version mismatch in the Docker config.

I'm getting an error of "unhandled rejection ReferenceError: structuredClone is not defined".

Some quick Googling seems to indicate that Node 17+ is required to use structuredClone, but the config on Docker Hub is calling for Node 16.20.2. I'm not a Docker expert by any means, but hopefully that just means the Dockerfile needs a bit of updating for the new version.

Thanks!
--David

**Comment by cpvalente** [comment]
Hi David,

Thank you very much for this.
I will pull the versions from docker and make a fix. The plan is to have the next alpha version this weekend

Sorry about this

Meanwhile you are welcome to test out v3 in the desktop, feedback is appreciated

**Comment by cpvalente** [comment]
Hi @bxtdvd , the newest release seems to run fine in docker. thank you for the headsup
Would you mind confirming that it works on your side?

**Comment by bxtdvd** [comment]
I can confirm that v.3.0.0-alpha.3 now starts on my docker setup. Thanks for the fix!
