### ISSUE TITLE
http api to enable/disable presenter, public, and low3 screen message

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#84]
something that we would use, is the presenter screen, to inform if there is a incoming interview and ask the speakers  to round off and hand over.

a message like "Interview NOW!" for a hand over off and maybe "Interview in a minute"
if the message was also settable via the api that would be even more useful.

this way we could do some scripting in the mixer/companion or similar to send out a message to involved parties automatically. even a countdown if message is changable via api.

if we mount a mobile screen on the eng camera we could even get a synced countdown and also inform the interviewer when to round of. they are not always listening to intercom while interviewing

**Comment by cpvalente** [comment]
with companion this can be easily achieved with websockets to replicate the functionality in the **Message Control** panel:

### set custom overlay on timer views (presenter / stage / speaker)
**address**: set-timer-text 
**value**: string
**address**: set-timer-visible
**value**: true / false

### set custom overlay on public views
**address**: set-public-text 
**value**: string
**address**: set-public-visible
**value**: true / false

### set custom overlay on lower third view
**address**: set-lower-text 
**value**: string
**address**: set-lower-visible
**value**: true / false

As of an HTTP API, that would need some further design. I will leave the issue open and prioritise it if it gets some traction.
Depending on the outcomes of #40 this could be in a near ish future timeline

**Comment by cpvalente** [comment]
Will close this issue for now. Feel free to reopen if there is any development here
