### ISSUE TITLE
"Time now" stops at 23:59:59

### ISSUE THREAD

**Issue by bxtdvd** [cpvalente/ontime#844]
I've been testing the v3.0.0-alpha2 at a multi-day conference this week...

We've noticed that the "time now" seems to get stuck at 23:59:59 overnight. We have to reboot the app to get accurate time-of-day again.

**Comment by cpvalente** [comment]
Thank you again @bxtdvd , I have made a fix and it will be included in the next release.

**Comment by cpvalente** [comment]
Hi @bxtdvd , could you please double-check the newest alpha release? this has been fixed, we have also made some improvements to the displaying of multi-day planning. It would be great to have your feedback

**Comment by bxtdvd** [comment]
I let this run overnight and I can confirm it's now fixed. Thanks!
