### ISSUE TITLE
colorize events

### ISSUE THREAD

**Issue by xztraz** [cpvalente/ontime#86]
the backstage panel and editor could have colorized events to differentiate different event types/teams.

ex
interview team has orange
pre recorded video segments purple.
speaker segments yellow
and so on.

excel import could read the color of a cell.

**Comment by cpvalente** [comment]
This would tie capabilities of the app to an excel workflow, or mean that the event should have a colour def in app.
One for the backlog, I will leave the issue open to see if it gets some traction

**Comment by je71175** [comment]
I expect this would be a lot of work but definitely something I would find useful.  FYI this is the bees knees platform for show running sheets https://shoflo.tv/rundown/

**Comment by cpvalente** [comment]
Sounds good to me.
@je71175 are you able to make a description of features you are missing? Ontime covers a few industries and use cases and will probably never match the feature set of a specific enterprise solution but I am happy to get feedback

**Comment by je71175** [comment]
https://docs.google.com/spreadsheets/d/18HCENK_tgl_vxCgByy4xGsCt_shkaJZdBbJEBG6qwZI/edit?usp=sharing

Some thoughts in the google sheet link.
1. a sample of one of our cue sheets
2. idea of how to use the excel import to set cue color and also setup custom fields 
3. idea of a new webpage to display the show cue, in a similar way to the example in 1.

**Comment by je71175** [comment]
Hi,

A simple workflow would be to use the excel import to setup (and populate) the custom fields in the onTime internal database, along with UI functionality to add/remove/edit custom fields (not the field data).  These custom fields would be available for all cues in this event.

Yes, I had imagined a separate cue sheet screen available via web browser (not UI), and this would display the cue sheet grid, similar to the example cue sheets - rows and columns.  The **custom field data could be edited in this view**, and columns resized or hidden.  The use case here is the team running the show.  For example, if I am the show caller, I want to see all fields, but if I am audio, i would hide the video, lighting, etc - columns not relevant to me.  I would then edit/input my audio cue notes directly into this screen (via browser).  The concept here is same as a live edit multi-user google sheet.
Lastly, this view would also need to reflect the current show status - active cue, running/paused, time remaining etc, and the green bar highlighted row was just for example.
thanks!

**Comment by cpvalente** [comment]
Sounds good, I have been planning to add a separate interface for data entry. Looks like this could tie well in an issue.

**Comment by cpvalente** [comment]
The feature is available for preview in #105.
As of now it is only possible to add colours with the import of data via excel.

Improvements in the event design will make this possible inapp in the future
