### ISSUE TITLE
Feature Request: Concurrent Events

### ISSUE THREAD

**Issue by jpk6789** [cpvalente/ontime#868]
I am currently scheduling a workshop with a presentation schedule. Ontime works quite well for that but in particular schedule, there are some concurrent events (breakout sessions) and I have not found an option for that in Ontime, yet.

So it would be nice to have the option to define such concurrent events. On the backstage / public view, they should be presented as linked / concurrent events (e.g. side by side or in one box with separators in between).

**Comment by alex-Arc** [comment]
Hey
I'm sorry to say that this will most likely not happen, the complexity would explode for us.

in your case you could look into running multiple instances on different ports, and you could use the main instance to trigger the breakout rooms.

**Comment by cpvalente** [comment]
Closing this as we are trying to clarify the roadmap forwards.
If you feel that there is information to consider, please feel free to reopen or create a new issue
