### ISSUE TITLE
Improvements on delay input

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#89]
We are looking for some improvements on how we enter delays
- [x] Ability to have negative delays (time ahead)
- [ ] Could we have a nicer workflow for adding delays? Roll back to slider from the earlier versions?
- [x] Show a more self explanatory note field as suggested in #55  (15 minutes delayed - 15 minutes ahead)
- [ ] Show somewhere the running time compared to local (1:25min behind)

**Comment by je71175** [comment]
Yes to negative values 
I like the + - 1 and + - 5 minute buttons on the timer control.  Same could be used for quickly setting a delay value!

**Comment by cpvalente** [comment]
Some of these were released as part of #96.
Adding a slider for time input didnt pass user tests.

Delay usage should probably be restructured with the timekeeping, this is something that i will be looking at separately together with some roll mode improvements and potentially a mode for continuous playback

Most importantly: negative delays are a go.
