### ISSUE TITLE
Show seconds for schedule in operator view

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#894]
Currently the operator view displays some of the information of the rundown.
Amongst this information is the schedule start and end. This time is formatted to be shown in `HH:MM`

![Screenshot 2024-04-16 at 21 00 39](https://github.com/cpvalente/ontime/assets/34649812/0ea382a6-4f65-422c-8123-c5022b2ff784)

The issue task is to add an option to the view parameters, which allows the scheduled times to be displayed with a given formatting string, such as `HH:MM:SS` or `HH:MM A`
The starting point for the options can be found here
https://github.com/cpvalente/ontime/blob/master/apps/client/src/common/components/view-params-editor/constants.ts#L454
https://github.com/cpvalente/ontime/blob/70c93a69feec81809116048224d6bf99e2407949/apps/client/src/features/operator/operator-event/OperatorEvent.tsx#L80

Similar logic already exists in the formatting of the clock
https://github.com/cpvalente/ontime/blob/70c93a69feec81809116048224d6bf99e2407949/apps/client/src/features/viewers/common/clock-time/ClockTime.tsx#L22

**Comment by asharonbaltazar** [comment]
Closing the issue because feature already exists
