### ISSUE TITLE
Automatic start/end time adjust

### ISSUE THREAD

**Issue by ddavehauser** [cpvalente/ontime#912]
Hello,
im currently testing if the software is working for our use cases.
We have to rearrange the schedule pretty often, this is working fine so far.

A button to update all the start/end times according to the new schedule, removing any overlaps/empty spots while keeping the duration would be great.

Adjusting them manually for 50+ cues is annoying :/

Thank you!

**Comment by ddavehauser** [comment]
Hey @cpvalente ,
I was testing V2. Just downloaded V3, its looking great and has exactly the functionality im looking for!
The first real-world test will be in 2 weeks, i guess there will be some coffee for you ;)

**Comment by cpvalente** [comment]
Hi @ddavehauser , how was your test?

I was wondering if we can close this ticket?

**Comment by cpvalente** [comment]
Closing this issue for now, please feel free to reopen
