### ISSUE TITLE
Remove Luxon as a dependency

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#914]
When starting the development of Ontime, it was expected that date handling would be a large part of the business logic so we added `Luxon` as a dependency

However Ontime does not have concept of dates, all times are handled in milliseconds.
Currently we have [a single function ](https://github.com/cpvalente/ontime/blob/master/packages/utils/src/date-utils/timeFormatting.ts#L79) that leverages `Luxon` to format strings using a user given format. It feels that it is not worth the price we pay in bundle size.

The issue task is to investigate the possibility of rewriting the format logic without `Luxon` and ideally without external libraries. Although finding a smaller library could be a sufficient improvement

**Comment by CharalambosMakridakis** [comment]
I would like to fix this issue.

**Comment by cpvalente** [comment]
Hi @CharalambosMakridakis, thank you for volunteering your time.

If you can help with the issue it is very much appreciated. I just realised that the function does not have tests. I suggest that is a good place to start so we dont lose behaviour

Feel free to open a PR and ping me for help as you need

**Comment by CharalambosMakridakis** [comment]
Hi,

yeah, I saw that the function does not have any tests yet.
I am going to add them in [timeFormatting.test.ts](https://github.com/cpvalente/ontime/blob/master/packages/utils/src/date-utils/timeFormatting.test.ts).

**Comment by CharalambosMakridakis** [comment]
Hi @cpvalente,

somehow the issue has not been closed.

And thanks for appreciating my fix!

**Comment by cpvalente** [comment]
Definitely appreciate your help.
It is a shame we dont have any small tasks right now, it would be great to continue having your contribution if you have availability.

As for the issue, it auto-closes if you use a closing keyword in your PR comment
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

I will close it manually for now, 
Thank you again
