### ISSUE TITLE
database is not saved persistent in docker volume

### ISSUE THREAD

**Issue by jochenfroehlich-gk** [cpvalente/ontime#931]
if we configure the docker compose file as shown in the documentation:
      volumes:
      - "./ontime-db:/external/db/"
      - "./ontime-styles:/external/styles/"

and we recreate the container the database is lost. it seams that the mapping inside the container is wrong.

we are running [v3.0.0-beta.3] in docker on ubuntu 22.04

Can you please advise.

**Comment by alex-Arc** [comment]
Hey
The compose file on [docker hub](https://hub.docker.com/r/getontime/ontime) is referencing v2 while we are in beta
so pulling `image: getontime/ontime:latest` will result in you getting Ontime v2

you need to pull getontime/ontime:v3.0.0-beta.3 to get the beta

if you already have that, then inside the container the apps working directory is `/external` here you have
- `/external/styles/override.css`  this is the override style sheet
- `/external/projects/`  here the the individual db files for each project are located
- `/external/external/` is the path that is searched if you go to ontimeip:4001/external
      eg `http://localhost:4001/external/demo/` is the demo

**Comment by cpvalente** [comment]
Hi @jochenfroehlich-gk, did you manage to fix this?
@alex-Arc , lets sync up on how to update the docs for this

**Comment by jochenfroehlich-gk** [comment]
Yepp I was able to fix it. Thanks
________________________________
