### ISSUE TITLE
Downloading any project (json or csv) always the default "db" project 

### ISSUE THREAD

**Issue by lukestein** [cpvalente/ontime#944]
Installation is Docker on Synology NAS.

Using either "Download" or "Export CSV Rundown" in the Manage Projects settings pane always results in downloading the default "db" project. The filename of the downloaded file is correct, but the contents are wrong. Please see short attached video (sound on) for demo of the problem:

https://github.com/cpvalente/ontime/assets/44452336/74d164fd-716f-43b6-89a4-e6ba5fc81035

**Comment by cpvalente** [comment]
HI @lukestein , thank you for bringing this to our attention.

I will take a look and we will follow up with a release
