### ISSUE TITLE
OSC Output "base 10:" Error

### ISSUE THREAD

**Issue by Jorkim** [cpvalente/ontime#953]
Hi,

first i have to say i really like ontime. Especially the new v.3 version.
But i have a problem since i have started using it (v.2)

When i use the OSC Output to trigger Ableton Live v.11 (via the plugin AbletonOSC) i get a base 10 error.

to trigger a cue in ableton i have to use the command: `/live/clip/fire track_id clip_id`

in the case of triggering the 1 column in the first 1 row i have to use: `/live/clip/fire 0 0` but it looks like if ontime is converting these integers to a string because of the space inbetween. 

When i just use `/live/clip/fire 0` i am only getting an out of range error but it leaves the command as an integer.

This occours for all inputs with more than one variable.
This is the exact error message: `/live/error,Error handling OSC message: invalid literal for int() with base 10: '0 0'`

When i use the console from the AbletonOSC plugin to send an OSC message to Ableton averything works as it should with exactly the same command.

Thanks for your help.

**Comment by cpvalente** [comment]
Hi @Jorkim, thank you for this.

I had a quick test and found that you are correct.
the payload is treated as a string in that case.
<img width="755" alt="Screenshot 2024-05-11 at 09 16 45" src="https://github.com/cpvalente/ontime/assets/34649812/bab9ce02-15be-4bbd-8d75-88b47476a238">

I also see several threads in different apps about similar issues, so I guess this may be a common implementation problem.

We will take a look from our side

**Comment by cpvalente** [comment]
Hi @Jorkim , could you please test out the new beta and give us some feedback on the behaviour?
Betas need to be downloaded from the release page here
https://github.com/cpvalente/ontime/releases/tag/v3.1.0-beta.1

**Comment by Jorkim** [comment]
Hi,
it looks like everything is working so far. Ive not found any problems with it.
I will let you now if i encounter any problems.
Thanks for your help and work.
