### ISSUE TITLE
Manage Projects > Load and Rename buttons don't work (Docker 3.0.1)

### ISSUE THREAD

**Issue by lukestein** [cpvalente/ontime#964]
*Installation*: v3.0.1 via Docker (Synology NAS). Note this is a "clean" installation; no external files left over from 3.0.0.

---

- **Loading** projects doesn't seem to work.
- **Renaming** projects doesn't seem to work.

See demo here (video has no sound), noting I also attempted several times to reload the page after running the "load" command:
https://github.com/cpvalente/ontime/assets/44452336/af932422-38b2-4f0d-8fd7-a6d62f0ee996

**Comment by cpvalente** [comment]
Hi @lukestein , thank you again for this.
I appreciate your patience and apologise for the bumpy start

I will push a quick release that fixes the regression
