### ISSUE TITLE
Release 3.0.1 doesn't show correct version under About > Current Version 

### ISSUE THREAD

**Issue by lukestein** [cpvalente/ontime#968]
*Installation*: v3.0.2 via Docker (Synology NAS)

---

Can confirm that the new release seems to successfully fix #964. 🎉

The release seems to still show the old version number under About > Current Version, which therefore also triggers the update notification.

This screenshot is from a 3.0.**2** installation:
<img width="552" alt="image" src="https://github.com/cpvalente/ontime/assets/44452336/d629d8d5-eded-4437-87d2-9448b2e95548">

Probably just needs another bump as in #961.

**Comment by cpvalente** [comment]
Thank you @lukestein , I have re-triggered the deployment and the new artifact should have the correct version number

**Comment by lukestein** [comment]
Closed by #969

**Comment by lukestein** [comment]
Closed by #969
