### ISSUE TITLE
Studio clock support for special characters

### ISSUE THREAD

**Issue by cpvalente** [cpvalente/ontime#97]
rc5_v2(unofficial)
![image](https://user-images.githubusercontent.com/25690871/146659426-b3cfbf59-604c-49a0-a701-e55154ff4d5e.png)
* adding delay doesn't change the countdown timer bellow clock.

* font does not support some special chars. ÅÄÖ for example. it's ok but just noted.
![image](https://user-images.githubusercontent.com/25690871/146659664-428c5393-c4b0-4ac1-857c-49cc5658b0de.png)

List updates times now! great!
Next item text under clock autoscales. Nice!!  (needs a bit of centering covered in graphics couple of posts above)

_Originally posted by @xztraz in https://github.com/cpvalente/ontime/issues/42#issuecomment-997308179_

**Comment by cpvalente** [comment]
We are marking this as Good First Issue to allow collaborators to take this task.
In short, we have a large user base in countries with extended alphabets (nordic and Germanic mostly). We would like to make sure the font here can support some special characters, such as the Norwegian Å Ø Æ

**Comment by alex-Arc** [comment]
maybe the we could switch to a 8-bit like font
https://www.cdnfonts.com/minecraftia.font
![image](https://github.com/cpvalente/ontime/assets/19875125/f2729b35-eea6-4a67-964d-85e4a0339d4c)

**Comment by cpvalente** [comment]
Hi @alex-Arc, thank you for this.
I am not too sure of the readability of that font, but I think it is a good alternative.

I wonder if the better alternative is to use a normal font. for everything but the time.
What do you think?

**Comment by alex-Arc** [comment]
I feel a bit like this clock  is mostly a coolness factor 😉  
but yes a normal font would also be fine
