### ISSUE TITLE
Background colors (`?key=`) in more views, and actually support transparency rather than drawing on opaque black canvas?

### ISSUE THREAD

**Issue by lukestein** [cpvalente/ontime#976]
Related to #162 :

- The `?key=` argument takes an 8-digit hex code as if supporting an alpha/transparency, but seems to be drawn on top of a black background so the page doesn't wind up rendering transparent. My use case is that I like to overlay timers in OBS or Electron Capture as in [this demo](https://www.youtube.com/watch?v=2BvBerQfX_0) and this screenshot (not ontime)
<img width="956" alt="image" src="https://github.com/cpvalente/ontime/assets/44452336/012ad3d6-a733-4ca4-94f3-ffbad990d04c">

- The `?key=` argument is only supported in `/minimal` and `/clock`. Could it be easily added to at least `/timer`? (Honestly wouldnt' look bad for public, countdown, backstage for visual consistency)

**Comment by cpvalente** [comment]
Thank you @lukestein , this is a good suggestion.

Meanwhile to get the key in OBS you need to override the CSS to set the body background color to transparent
See the docs https://docs.getontime.no/quick-tips/lower-thirds-in-obs/

**Comment by lukestein** [comment]
> Meanwhile to get the key in OBS you need to override the CSS to set the body background color to transparent
> 
> See the docs https://docs.getontime.no/quick-tips/lower-thirds-in-obs/

Thanks for this pointer (which I'd somehow missed)

However, I can't get obs to successfully eliminate the background with a CSS override. May be user error.

**Comment by cpvalente** [comment]
Hm,

I did a quick test now in `/minimal` and the combination of setting both the background in the body and the key value to `#00000000` seemed to result in a transparent background

Having said this, I havent tested this in OBS and I am not sure this still works.
@alex-Arc , do you have time to sanity check?

**Comment by lukestein** [comment]
Nothing doing for me (again, may be user error):
https://github.com/cpvalente/ontime/assets/44452336/e2dd0bf6-24bb-407a-9367-62e2a8711d0c

**Comment by cpvalente** [comment]
> Nothing doing for me (again, may be user error):
> 
> https://github.com/cpvalente/ontime/assets/44452336/e2dd0bf6-24bb-407a-9367-62e2a8711d0c

I will take a look. 

A workaround for now could be to set the key colour to something you can key (green or full black)

But this should work and I will see what is happening

**Comment by alex-Arc** [comment]
the bacgound color line in index.scss is preventing the transparent background

![image](https://github.com/cpvalente/ontime/assets/19875125/1e3a1392-0754-428a-b87c-0ff2cdf02940)

if i change that to rgba(0,0,0,0) it works

![image](https://github.com/cpvalente/ontime/assets/19875125/a78e17a1-dd0e-4fec-bea5-b59d5e153988)

**Comment by lukestein** [comment]
Just noting there may have been some correspondence with Jef (mentioned around 34m [here](https://youtu.be/vI-iF-W1mow?si=A9BdImC1HzsbwyCG)) about this question
