### ISSUE TITLE
Expected End of timeline is not calculated correctly

### ISSUE THREAD

**Issue by ekordas** [cpvalente/ontime#984]
Installation: current master(dae6f84af0dd25c390b9e762ab963f118ca0c0e1) on linux

Steps to Reproduce:
- Create one event starting at 20:00 with a duration of 1hour
- Start the Event

Now the Expected End in the Editor Header will display wrong times
Starting the event at 19:45 will result in a Expected End of 21:15
Starting the event at 20:15 will result in a Expected End of 20:45

The expected End of the current Event in the playback area is displayed correctly

**Comment by cpvalente** [comment]
Thank you @ekordas for the bug report and for the proposed fix 🤩
