### ISSUE TITLE
Feature Request: Display multiple custom fields in operator view

### ISSUE THREAD

**Issue by Ashtlind** [cpvalente/ontime#991]
Hi team!

We are really enjoying playing with v3. We would love to see the ability to show multiple custom fields in the operator view much like the cuesheet view. Feel this would be an excellent view option to display in a view switcher multiview box or something similar for quick glance info.

**Comment by cpvalente** [comment]
> We are really enjoying playing with v3. We would love to see the ability to show multiple custom fields in the operator view much like the cuesheet view. Feel this would be an excellent view option to display in a view switcher multiview box or something similar for quick glance info.


Hi @Ashtlind 

Thank you for reaching out.

We try to approach the creation of views with a "different views for different jobs" mentality.
In this case, would you kind clarifying how the cuesheet view does not enable the workflow that you are after?

The operator view is not particularly well suited for multiple subscriptions (custom fields) but if we can assert that there is a gap in the feature set I am happy to consider an extension or a new view

**Comment by Ashtlind** [comment]
Hi @cpvalente 

Thanks so much for your reply.

Totally understand that. We are hoping for something similar to the shoflo display view, this is ideal for using within a camera multiview layout. (Example of this being used below)
It makes a really easy point of reference for the whole team on where we are in the rundown and the next few items (not just the next one but looking a few ahead also is ideal)

We are looking for something that can display the relevant info in a really easy to read and un-cluttered format with quite a large font size. We have found the backstage view to have a bit much info on it and the cuesheet isn't super easy to read multiple columns at a glance in a small window. This would be super helpful as there would be multiple operators seeing this view to be able to have multiple custom fields shown.

Here is showflow's layout
https://shoflo.tv/display-view/
![image](https://github.com/cpvalente/ontime/assets/19161455/f8cc8969-6feb-45c9-9591-899d6c498c6f)


In this screenshot you can see shoflow's display view in the camera multiview underneath cam 13.

![image](https://github.com/cpvalente/ontime/assets/19161455/c5ff2d53-7d31-46b2-823b-1d696d28594d)



I really like the way the operater view would look for this, here is a mockup:
![image](https://github.com/cpvalente/ontime/assets/19161455/7732e356-6d73-4827-8938-805941b97366)


Compared to the current cuesheet look at a high zoom ratio:
![image](https://github.com/cpvalente/ontime/assets/19161455/07dd73c6-ad8e-44b6-a0ab-bb3afbc156bc)


Hopefully this helps clear up some of our thoughts

**Comment by alex-Arc** [comment]
I have also been thinking about this
And like the idea

Something like this for the parameter UI would be nice
https://www.npmjs.com/package/chakra-react-select

And your mockup for the rundown is also how I imagine it

**Comment by cpvalente** [comment]
Hi @Ashtlind 

We have added the possibility to select several custom fields since v3.2.0
Could you please provide us some feedback?

We would like to close this issue as the task described has been completed. You are welcome to open more issues with eventual improvement suggestions

**Comment by Ashtlind** [comment]
Hi @cpvalente!

Thanks heaps! Looks really great!

This is what it is looking like in our use case, we did a few css overrides for our view to make it useable in the tiny box. And did a few tweaks for colour visibility in the custom fields like adding the background colour solid behind them as I was finding it hard to read on the red. Super happy with this feature guys! Great work! If this sort of style for a multiview box could be useful for anyone else I'll pop it below, not sure where it should live though. Happy to leave that in your capable hands.

![image](https://github.com/cpvalente/ontime/assets/19161455/6ff9ee67-f9d6-44ab-96e1-c1dce576531b)

![20240619_103235](https://github.com/cpvalente/ontime/assets/19161455/2b34dd5b-c9cb-402c-b1e2-677f568c5cec)


`body { background-color: rgba(0, 0, 0, 0); margin: 0px auto; overflow: hidden; }

._mainField_1itqp_99 {font-size: 7rem; font-weight: bold; line-height: 1; margin-top: 2rem;}

._statusBar_18vt1_10 {
	display: none;
}

._cue_1itqp_89 {display: none;}

._schedule_1itqp_50 {font-size: 5rem; opacity: 0.5;}

._runningTime_1itqp_123 {font-size: 5rem; opacity: 1;}

._fields_1itqp_136 {font-size: 5rem; margin-bottom: 3rem;}

._fields_1itqp_136 ._field_1itqp_136 {margin-right: 0px !important; padding-left: 1.5rem; padding-right: 1.5rem;}

._fields_1itqp_136 ._value_1itqp_156 {padding-left: 1.5rem; padding-right: 1rem; margin-right: 2rem; background-color: #202020;}

._secondaryField_1itqp_106 {font-size: 5rem; float:left;}

._operatorEvents_t3nwq_17 {padding:none;}

._event_1itqp_55 {column-gap: 3rem;}`

**Comment by cpvalente** [comment]
Hi @Ashtlind really great feedback and I like your changes

Unfortunately, the way that our app is made, it means that you will lose your overrides every time a new release is out. The hashes (eg `_fields_1itqp_136`) are generated at build time and will always be different.
In other views, we use standard CSS to facilitate user override, but in production views (editor, cuesheet and operator) the complexity is higher and we need the flexibility and performance benefits.

Maybe there is a workaround for fuzzy matching CSS selectors in some extension, if meanwhile we find out that many users are looking to customise this, we can look for alternatives. 

Meanwhile: we have incorporated the addition of background text into Ontime and will be in the next release
